/**
 * Custom Components Registry
 * 
 * UI identities for custom components: Card, Badge, Modal, Alert, Tooltip, Accordion, Tabs, Breadcrumb
 */

import type { UiIdentity } from '../types';

export const COMMON_COMPONENTS = {
  CARD: {
    CONTAINER: {
      id: 'UI_COMMON_COMPONENTS_CARD_CONTAINER',
      path: 'common.components.card.container',
      description: 'Card container',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    IMAGE: {
      id: 'UI_COMMON_COMPONENTS_CARD_IMAGE',
      path: 'common.components.card.image',
      description: 'Card image',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TITLE: {
      id: 'UI_COMMON_COMPONENTS_CARD_TITLE',
      path: 'common.components.card.title',
      description: 'Card title',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DESCRIPTION: {
      id: 'UI_COMMON_COMPONENTS_CARD_DESCRIPTION',
      path: 'common.components.card.description',
      description: 'Card description',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ACTION: {
      id: 'UI_COMMON_COMPONENTS_CARD_ACTION',
      path: 'common.components.card.action',
      description: 'Card action button',
      category: 'action' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  BADGE: {
    CONTAINER: {
      id: 'UI_COMMON_COMPONENTS_BADGE_CONTAINER',
      path: 'common.components.badge.container',
      description: 'Badge container',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TEXT: {
      id: 'UI_COMMON_COMPONENTS_BADGE_TEXT',
      path: 'common.components.badge.text',
      description: 'Badge text',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  MODAL: {
    DIALOG: {
      id: 'UI_COMMON_COMPONENTS_MODAL_DIALOG',
      path: 'common.components.modal.dialog',
      description: 'Modal dialog',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TITLE: {
      id: 'UI_COMMON_COMPONENTS_MODAL_TITLE',
      path: 'common.components.modal.title',
      description: 'Modal title',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CONTENT: {
      id: 'UI_COMMON_COMPONENTS_MODAL_CONTENT',
      path: 'common.components.modal.content',
      description: 'Modal content',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CLOSE_BUTTON: {
      id: 'UI_COMMON_COMPONENTS_MODAL_CLOSE',
      path: 'common.components.modal.close-button',
      description: 'Modal close button',
      category: 'action' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CONFIRM_BUTTON: {
      id: 'UI_COMMON_COMPONENTS_MODAL_CONFIRM',
      path: 'common.components.modal.confirm-button',
      description: 'Modal confirm button',
      category: 'action' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CANCEL_BUTTON: {
      id: 'UI_COMMON_COMPONENTS_MODAL_CANCEL',
      path: 'common.components.modal.cancel-button',
      description: 'Modal cancel button',
      category: 'action' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  ALERT: {
    CONTAINER: {
      id: 'UI_COMMON_COMPONENTS_ALERT_CONTAINER',
      path: 'common.components.alert.container',
      description: 'Alert container',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TITLE: {
      id: 'UI_COMMON_COMPONENTS_ALERT_TITLE',
      path: 'common.components.alert.title',
      description: 'Alert title',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    MESSAGE: {
      id: 'UI_COMMON_COMPONENTS_ALERT_MESSAGE',
      path: 'common.components.alert.message',
      description: 'Alert message',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CLOSE_BUTTON: {
      id: 'UI_COMMON_COMPONENTS_ALERT_CLOSE',
      path: 'common.components.alert.close-button',
      description: 'Alert close button',
      category: 'action' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  TOOLTIP: {
    CONTAINER: {
      id: 'UI_COMMON_COMPONENTS_TOOLTIP_CONTAINER',
      path: 'common.components.tooltip.container',
      description: 'Tooltip container',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TEXT: {
      id: 'UI_COMMON_COMPONENTS_TOOLTIP_TEXT',
      path: 'common.components.tooltip.text',
      description: 'Tooltip text',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  ACCORDION: {
    CONTAINER: {
      id: 'UI_COMMON_COMPONENTS_ACCORDION_CONTAINER',
      path: 'common.components.accordion.container',
      description: 'Accordion container',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ITEM: {
      id: 'UI_COMMON_COMPONENTS_ACCORDION_ITEM',
      path: 'common.components.accordion.item',
      description: 'Accordion item',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SUMMARY: {
      id: 'UI_COMMON_COMPONENTS_ACCORDION_SUMMARY',
      path: 'common.components.accordion.summary',
      description: 'Accordion summary',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CONTENT: {
      id: 'UI_COMMON_COMPONENTS_ACCORDION_CONTENT',
      path: 'common.components.accordion.content',
      description: 'Accordion content',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  TABS: {
    CONTAINER: {
      id: 'UI_COMMON_COMPONENTS_TABS_CONTAINER',
      path: 'common.components.tabs.container',
      description: 'Tabs container',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TAB_LIST: {
      id: 'UI_COMMON_COMPONENTS_TABS_TAB_LIST',
      path: 'common.components.tabs.tab-list',
      description: 'Tabs list',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TAB: {
      id: 'UI_COMMON_COMPONENTS_TABS_TAB',
      path: 'common.components.tabs.tab',
      description: 'Tab button',
      category: 'action' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    PANEL: {
      id: 'UI_COMMON_COMPONENTS_TABS_PANEL',
      path: 'common.components.tabs.panel',
      description: 'Tab panel',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  BREADCRUMB: {
    CONTAINER: {
      id: 'UI_COMMON_COMPONENTS_BREADCRUMB_CONTAINER',
      path: 'common.components.breadcrumb.container',
      description: 'Breadcrumb container',
      category: 'container' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ITEM: {
      id: 'UI_COMMON_COMPONENTS_BREADCRUMB_ITEM',
      path: 'common.components.breadcrumb.item',
      description: 'Breadcrumb item',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    LINK: {
      id: 'UI_COMMON_COMPONENTS_BREADCRUMB_LINK',
      path: 'common.components.breadcrumb.link',
      description: 'Breadcrumb link',
      category: 'navigation' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SEPARATOR: {
      id: 'UI_COMMON_COMPONENTS_BREADCRUMB_SEPARATOR',
      path: 'common.components.breadcrumb.separator',
      description: 'Breadcrumb separator',
      category: 'display' as const,
      feature: 'common',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
} as const;

export const COMPONENTS_IDENTITIES = [
  ...Object.values(COMMON_COMPONENTS.CARD),
  ...Object.values(COMMON_COMPONENTS.BADGE),
  ...Object.values(COMMON_COMPONENTS.MODAL),
  ...Object.values(COMMON_COMPONENTS.ALERT),
  ...Object.values(COMMON_COMPONENTS.TOOLTIP),
  ...Object.values(COMMON_COMPONENTS.ACCORDION),
  ...Object.values(COMMON_COMPONENTS.TABS),
  ...Object.values(COMMON_COMPONENTS.BREADCRUMB),
] as readonly UiIdentity[];
