/**
 * Form Elements Registry
 *
 * UI identities for form elements: form, input, textarea, select, option, button, label, fieldset, legend, checkbox, radio, switch
 */

import type { UiIdentity } from '../types';

export const COMMON_FORMS = {
  FORM: {
    id: 'UI_COMMON_FORMS_FORM',
    path: 'common.forms.form',
    lifecycle: 'active',
    description: 'Generic form element',
    category: 'container' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  INPUT: {
    id: 'UI_COMMON_FORMS_INPUT',
    path: 'common.forms.input',
    lifecycle: 'active',
    description: 'Generic input field',
    category: 'input' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  TEXTAREA: {
    id: 'UI_COMMON_FORMS_TEXTAREA',
    path: 'common.forms.textarea',
    lifecycle: 'active',
    description: 'Generic textarea field',
    category: 'input' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  SELECT: {
    id: 'UI_COMMON_FORMS_SELECT',
    path: 'common.forms.select',
    lifecycle: 'active',
    description: 'Generic select dropdown',
    category: 'input' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  OPTION: {
    id: 'UI_COMMON_FORMS_OPTION',
    path: 'common.forms.option',
    lifecycle: 'active',
    description: 'Generic select option',
    category: 'input' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  BUTTON: {
    id: 'UI_COMMON_FORMS_BUTTON',
    path: 'common.forms.button',
    lifecycle: 'active',
    description: 'Generic button',
    category: 'action' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  LABEL: {
    id: 'UI_COMMON_FORMS_LABEL',
    path: 'common.forms.label',
    lifecycle: 'active',
    description: 'Generic form label',
    category: 'display' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  FIELDSET: {
    id: 'UI_COMMON_FORMS_FIELDSET',
    path: 'common.forms.fieldset',
    lifecycle: 'active',
    description: 'Generic fieldset',
    category: 'container' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  LEGEND: {
    id: 'UI_COMMON_FORMS_LEGEND',
    path: 'common.forms.legend',
    lifecycle: 'active',
    description: 'Generic fieldset legend',
    category: 'display' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  CHECKBOX: {
    id: 'UI_COMMON_FORMS_CHECKBOX',
    path: 'common.forms.checkbox',
    lifecycle: 'active',
    description: 'Generic checkbox',
    category: 'input' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  RADIO: {
    id: 'UI_COMMON_FORMS_RADIO',
    path: 'common.forms.radio',
    lifecycle: 'active',
    description: 'Generic radio button',
    category: 'input' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
  SWITCH: {
    id: 'UI_COMMON_FORMS_SWITCH',
    path: 'common.forms.switch',
    lifecycle: 'active',
    description: 'Generic switch toggle',
    category: 'input' as const,
    feature: 'common',
    version: '1.0.0',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
} as const,
} as const;

export const FORMS_IDENTITIES = [...Object.values(COMMON_FORMS)] as readonly UiIdentity[];
