/** Authentication UI identities */
export const AUTH = {
  SHARED: {
    PAGE: {
      id: 'UI_AUTH_SHARED_PAGE',
      path: 'auth.shared.layout.page',
      lifecycle: 'active',
      description: 'Auth page root container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HERO: {
      id: 'UI_AUTH_SHARED_HERO',
      path: 'auth.shared.layout.hero',
      lifecycle: 'active',
      description: 'Auth hero panel',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    BRAND_ROW: {
      id: 'UI_AUTH_SHARED_BRAND_ROW',
      path: 'auth.shared.display.brand-row',
      lifecycle: 'active',
      description: 'Auth brand row',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    BRAND_ICON: {
      id: 'UI_AUTH_SHARED_BRAND_ICON',
      path: 'auth.shared.display.brand-icon',
      lifecycle: 'active',
      description: 'Auth brand icon',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HERO_QUOTE_ELEMENT: {
      id: 'UI_AUTH_SHARED_HERO_QUOTE_ELEMENT',
      path: 'auth.shared.display.hero-quote-element',
      lifecycle: 'active',
      description: 'Auth hero blockquote element',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    HERO_QUOTE_BLOCK: {
      id: 'UI_AUTH_SHARED_HERO_QUOTE',
      path: 'auth.shared.display.hero-quote-block',
      lifecycle: 'active',
      description: 'Auth hero quote block',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HERO_HIGHLIGHTS: {
      id: 'UI_AUTH_SHARED_HERO_HIGHLIGHTS',
      path: 'auth.shared.display.hero-highlights',
      lifecycle: 'active',
      description: 'Auth hero highlights row',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HERO_DECOR: {
      id: 'UI_AUTH_SHARED_HERO_DECOR',
      path: 'auth.shared.layout.hero-decor',
      lifecycle: 'active',
      description: 'Auth hero decorative background',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HIGHLIGHT_SECURITY: {
uuid: '962b50b3-69e1-5882-b8a3-835d2180bf1c',
      id: 'UI_AUTH_SHARED_HIGHLIGHT_SECURITY',
      path: 'auth.shared.display.highlight-security',
      lifecycle: 'active',
      description: 'Auth hero security highlight',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HIGHLIGHT_PHONE: {
uuid: '45bf5147-6dca-5e80-a573-bc690491d692',
      id: 'UI_AUTH_SHARED_HIGHLIGHT_PHONE',
      path: 'auth.shared.display.highlight-phone',
      lifecycle: 'active',
      description: 'Auth hero phone highlight',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HIGHLIGHT_ENCRYPTED: {
uuid: 'b5badb5b-63bf-5074-9afb-9b9112ec494a',
      id: 'UI_AUTH_SHARED_HIGHLIGHT_ENCRYPTED',
      path: 'auth.shared.display.highlight-encrypted',
      lifecycle: 'active',
      description: 'Auth hero encryption highlight',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    FORM_CARD: {
      id: 'UI_AUTH_SHARED_FORM_CARD',
      path: 'auth.shared.layout.form-card',
      lifecycle: 'active',
      description: 'Auth form card container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    MOBILE_BRAND: {
      id: 'UI_AUTH_SHARED_MOBILE_BRAND',
      path: 'auth.shared.display.mobile-brand',
      lifecycle: 'active',
      description: 'Auth mobile brand header',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PHONE_PLACEHOLDER: {
uuid: '74c75fb6-6f83-5ad1-a0dd-09043ee5462f',
      id: 'UI_AUTH_SHARED_PHONE_PLACEHOLDER',
      path: 'auth.shared.phone-placeholder',
      lifecycle: 'active',
      description: 'Auth phone input placeholder',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PASSWORD_PLACEHOLDER: {
uuid: '20ca7187-6cdb-500e-9a3e-c5dd0435a9dc',
      id: 'UI_AUTH_SHARED_PASSWORD_PLACEHOLDER',
      path: 'auth.shared.password-placeholder',
      lifecycle: 'active',
      description: 'Auth password input placeholder',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
  },
  LOGIN: {
    HEADING: {
uuid: 'c54deede-f606-5c7b-b214-9f3c733474c1',
      id: 'UI_AUTH_LOGIN_HEADING',
      path: 'auth.login.display.heading',
      lifecycle: 'active',
      description: 'Login page heading',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUBHEADING: {
uuid: '60c7edec-65c6-56b7-a181-27aef7180451',
      id: 'UI_AUTH_LOGIN_SUBHEADING',
      path: 'auth.login.display.subheading',
      lifecycle: 'active',
      description: 'Login page subheading',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HERO_QUOTE: {
uuid: '1ad2037f-db43-57f8-9748-9f713cf0352a',
      id: 'UI_AUTH_LOGIN_HERO_QUOTE',
      path: 'auth.login.display.hero-quote',
      lifecycle: 'active',
      description: 'Login hero quote',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HERO_FOOTER: {
uuid: '8437fd7a-76db-5bd7-a29a-ce645906a1b1',
      id: 'UI_AUTH_LOGIN_HERO_FOOTER',
      path: 'auth.login.display.hero-footer',
      lifecycle: 'active',
      description: 'Login hero footer',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PHONE_INPUT: {
uuid: 'dc25839f-b4f2-5f9a-bb4b-fc15b69586e8',
      id: 'UI_AUTH_LOGIN_PHONE_INPUT',
      path: 'auth.login.form.phone-input',
      lifecycle: 'active',
      description: 'Login phone input',
      category: 'input',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PHONE_INPUT_LABEL: {
      id: 'UI_AUTH_LOGIN_PHONE_INPUT_LABEL',
      path: 'auth.login.display.phone-input-label',
      lifecycle: 'active',
      description: 'Login phone input label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PASSWORD_INPUT: {
uuid: '93d1b686-6299-5719-94b5-bbe4c13f9197',
      id: 'UI_AUTH_LOGIN_PASSWORD_INPUT',
      path: 'auth.login.form.password-input',
      lifecycle: 'active',
      description: 'Login password input',
      category: 'input',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PASSWORD_INPUT_LABEL: {
      id: 'UI_AUTH_LOGIN_PASSWORD_INPUT_LABEL',
      path: 'auth.login.display.password-input-label',
      lifecycle: 'active',
      description: 'Login password input label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FORGOT_PASSWORD: {
uuid: '8771d585-21d5-51cc-bb1b-910f1ae955f6',
      id: 'UI_AUTH_LOGIN_FORGOT_PASSWORD',
      path: 'auth.login.form.forgot-password-link',
      lifecycle: 'active',
      description: 'Login forgot password link',
      category: 'navigation',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    TOGGLE_PASSWORD: {
uuid: '4cea7814-285f-59e5-b886-88860889399f',
      id: 'UI_AUTH_LOGIN_TOGGLE_PASSWORD',
      path: 'auth.login.toggle-password-visibility',
      lifecycle: 'active',
      description: 'Login toggle password visibility',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUBMIT_BUTTON: {
uuid: 'daaef5f8-7bd6-5be7-b540-defa4ad196b1',
      id: 'UI_AUTH_LOGIN_SUBMIT',
      path: 'auth.login.form.submit-button',
      lifecycle: 'active',
      description: 'Login submit button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUBMITTING_BUTTON: {
uuid: '1679e034-605c-5f77-a5a1-1db657580559',
      id: 'UI_AUTH_LOGIN_SUBMITTING',
      path: 'auth.login.submitting-button',
      lifecycle: 'active',
      description: 'Login submitting button label',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    GUEST_LOGIN: {
uuid: '11c1d460-3543-51e1-81a8-73f65fbfa30f',
      id: 'UI_AUTH_LOGIN_GUEST',
      path: 'auth.login.actions.guest-login-button',
      lifecycle: 'active',
      description: 'Login guest button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SIGNUP_LINK: {
uuid: '6a903f45-fd9e-56a8-86c3-61234587bbf6',
      id: 'UI_AUTH_LOGIN_SIGNUP_LINK',
      path: 'auth.login.actions.signup-link',
      lifecycle: 'active',
      description: 'Login signup link',
      category: 'navigation',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SIGNUP_LINK_BUTTON: {
      id: 'UI_AUTH_LOGIN_SIGNUP_LINK_BUTTON',
      path: 'auth.login.actions.signup-link-button',
      lifecycle: 'active',
      description: 'Login signup link button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SIGNUP_DIVIDER: {
uuid: '1157333a-96f5-5559-b177-52ec1295ab3b',
      id: 'UI_AUTH_LOGIN_SIGNUP_DIVIDER',
      path: 'auth.login.display.signup-divider',
      lifecycle: 'active',
      description: 'Login signup divider label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUCCESS_HEADING: {
uuid: 'e1b13cea-7b58-5a63-9490-ea10db7a5dd1',
      id: 'UI_AUTH_LOGIN_SUCCESS_HEADING',
      path: 'auth.login.display.success-heading',
      lifecycle: 'active',
      description: 'Login success heading',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUCCESS_DESCRIPTION: {
uuid: '9383019e-718f-56ab-9d3f-0920d2a10a5d',
      id: 'UI_AUTH_LOGIN_SUCCESS_DESCRIPTION',
      path: 'auth.login.display.success-description',
      lifecycle: 'active',
      description: 'Login success description',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SIGNIN_AGAIN: {
uuid: '2b915385-0009-5b76-a965-be63639a33c4',
      id: 'UI_AUTH_LOGIN_SIGNIN_AGAIN',
      path: 'auth.login.actions.signin-again-button',
      lifecycle: 'active',
      description: 'Login sign in again button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
  },
  REGISTRATION: {
    BRAND_NAME: {
uuid: '4ecf8039-11c1-5808-b0d8-c48fb4f66c9e',
      id: 'UI_AUTH_REGISTRATION_BRAND_NAME',
      path: 'auth.registration.brand-name',
      lifecycle: 'active',
      description: 'Registration brand name',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    HEADING: {
uuid: '2b72275a-5d33-5b4d-bb6f-bd80fd4d5293',
      id: 'UI_AUTH_REGISTRATION_HEADING',
      path: 'auth.registration.heading',
      lifecycle: 'active',
      description: 'Registration hero heading',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    DESCRIPTION: {
uuid: 'a2e038ce-c60a-56b1-8c42-afd07192831b',
      id: 'UI_AUTH_REGISTRATION_DESCRIPTION',
      path: 'auth.registration.description',
      lifecycle: 'active',
      description: 'Registration hero description',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    TITLE: {
uuid: '864c7832-f232-5f91-9240-6f288dca5b3f',
      id: 'UI_AUTH_REGISTRATION_TITLE',
      path: 'auth.registration.title',
      lifecycle: 'active',
      description: 'Registration form title',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    CARD_DESCRIPTION: {
uuid: '325e1cd3-ecfd-5572-a498-8fcd6eb9a2cc',
      id: 'UI_AUTH_REGISTRATION_CARD_DESCRIPTION',
      path: 'auth.registration.card-description',
      lifecycle: 'active',
      description: 'Registration form description',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PHONE_INPUT: {
uuid: 'a1fed973-0ee2-517c-8c71-b511dc3a4a02',
      id: 'UI_AUTH_REGISTRATION_PHONE_INPUT',
      path: 'auth.registration.phone-input',
      lifecycle: 'active',
      description: 'Registration phone input',
      category: 'input',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PHONE_INPUT_LABEL: {
      id: 'UI_AUTH_REGISTRATION_PHONE_INPUT_LABEL',
      path: 'auth.registration.display.phone-input-label',
      lifecycle: 'active',
      description: 'Registration phone input label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PHONE_VERIFICATION_SECTION: {
      id: 'UI_AUTH_REGISTRATION_PHONE_VERIFICATION_SECTION',
      path: 'auth.registration.layout.phone-verification-section',
      lifecycle: 'active',
      description: 'Registration phone verification section',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    VERIFY_BUTTON: {
uuid: '7598a99a-b039-526d-bd4e-f504b16dfe2f',
      id: 'UI_AUTH_REGISTRATION_VERIFY_BUTTON',
      path: 'auth.registration.verify-button',
      lifecycle: 'active',
      description: 'Registration verify phone button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    EDIT_BUTTON: {
uuid: 'c7dc86f9-88e1-5e1a-b9ce-22e7e93e69e8',
      id: 'UI_AUTH_REGISTRATION_EDIT_BUTTON',
      path: 'auth.registration.edit-button',
      lifecycle: 'active',
      description: 'Registration edit phone button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    OTP_LABEL: {
uuid: '55dc966c-7955-5b5f-84e2-782eabe8ae41',
      id: 'UI_AUTH_REGISTRATION_OTP_LABEL',
      path: 'auth.registration.otp-label',
      lifecycle: 'active',
      description: 'Registration OTP label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    OTP_DESCRIPTION: {
uuid: '3f273638-fcbf-588b-99e9-625a0c5888bd',
      id: 'UI_AUTH_REGISTRATION_OTP_DESCRIPTION',
      path: 'auth.registration.otp-description',
      lifecycle: 'active',
      description: 'Registration OTP description',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    OTP_INPUT: {
uuid: '911d441a-5b04-5445-929d-4af406c29e2f',
      id: 'UI_AUTH_REGISTRATION_OTP_INPUT',
      path: 'auth.registration.otp-input',
      lifecycle: 'active',
      description: 'Registration OTP input',
      category: 'input',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
      repeatable: true,
} as const,
    RESEND_BUTTON: {
uuid: 'bb4df5a4-f94c-51c3-9111-ff3efb834165',
      id: 'UI_AUTH_REGISTRATION_RESEND_BUTTON',
      path: 'auth.registration.resend-button',
      lifecycle: 'active',
      description: 'Registration OTP resend button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    VERIFY_OTP_BUTTON: {
uuid: '3b0a97fb-b5b8-52f6-b7c7-0371a4ba7214',
      id: 'UI_AUTH_REGISTRATION_VERIFY_OTP',
      path: 'auth.registration.verify-otp-button',
      lifecycle: 'active',
      description: 'Registration verify OTP button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PHONE_VERIFIED: {
uuid: '9afd2ced-6741-533c-8b5e-18af5206418e',
      id: 'UI_AUTH_REGISTRATION_PHONE_VERIFIED',
      path: 'auth.registration.phone-verified-message',
      lifecycle: 'active',
      description: 'Registration phone verified message',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PASSWORD_INPUT: {
uuid: '44b2b3d2-8d19-5133-8732-c708bb730df1',
      id: 'UI_AUTH_REGISTRATION_PASSWORD_INPUT',
      path: 'auth.registration.password-input',
      lifecycle: 'active',
      description: 'Registration password input',
      category: 'input',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PASSWORD_INPUT_LABEL: {
      id: 'UI_AUTH_REGISTRATION_PASSWORD_INPUT_LABEL',
      path: 'auth.registration.display.password-input-label',
      lifecycle: 'active',
      description: 'Registration password input label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CONFIRM_PASSWORD_INPUT: {
uuid: 'c8277664-0566-5611-b32a-97825b994e47',
      id: 'UI_AUTH_REGISTRATION_CONFIRM_PASSWORD',
      path: 'auth.registration.confirm-password-input',
      lifecycle: 'active',
      description: 'Registration confirm password input',
      category: 'input',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    CONFIRM_PASSWORD_INPUT_LABEL: {
      id: 'UI_AUTH_REGISTRATION_CONFIRM_PASSWORD_INPUT_LABEL',
      path: 'auth.registration.display.confirm-password-input-label',
      lifecycle: 'active',
      description: 'Registration confirm password input label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    EMAIL_INPUT: {
uuid: '7748b67f-a8ca-5024-abff-50cd06e17032',
id: 'UI_AUTH_REGISTRATION_EMAIL_INPUT',
      path: 'auth.registration.email-input',
      lifecycle: 'active',
      description: 'Registration email input (optional)',
      category: 'input',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-21',
      updatedAt: '2026-06-21',
} as const,
    EMAIL_INPUT_LABEL: {
id: 'UI_AUTH_REGISTRATION_EMAIL_INPUT_LABEL',
      path: 'auth.registration.display.email-input-label',
      lifecycle: 'active',
      description: 'Registration email input label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-21',
      updatedAt: '2026-06-21',
} as const,
    TOGGLE_PASSWORD: {
uuid: '68273140-e384-5b9b-9241-946ab3302f4d',
      id: 'UI_AUTH_REGISTRATION_TOGGLE_PASSWORD',
      path: 'auth.registration.toggle-password-visibility',
      lifecycle: 'active',
      description: 'Registration toggle password visibility',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    CONTINUE_BUTTON: {
uuid: 'a964dbc5-4234-55bc-816d-c2077331e58e',
      id: 'UI_AUTH_REGISTRATION_CONTINUE',
      path: 'auth.registration.continue-button',
      lifecycle: 'active',
      description: 'Registration continue button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    CONFIRM_TOGGLE_PASSWORD: {
      id: 'UI_AUTH_REGISTRATION_CONFIRM_TOGGLE_PASSWORD',
      path: 'auth.registration.toggle-confirm-password-visibility',
      lifecycle: 'active',
      description: 'Registration confirm password toggle visibility',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PASSWORD_STRENGTH: {
uuid: 'cd056997-595b-5918-91d9-c04df6798496',
      id: 'UI_AUTH_REGISTRATION_PASSWORD_STRENGTH',
      path: 'auth.registration.password-strength-label',
      lifecycle: 'active',
      description: 'Registration password strength label',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PASSWORD_STRENGTH_CONTAINER: {
      id: 'UI_AUTH_REGISTRATION_PASSWORD_STRENGTH_CONTAINER',
      path: 'auth.registration.layout.password-strength-container',
      lifecycle: 'active',
      description: 'Registration password strength container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STRENGTH_WEAK: {
      id: 'UI_AUTH_REGISTRATION_STRENGTH_WEAK',
      path: 'auth.registration.strength-weak',
      lifecycle: 'active',
      description: 'Password strength weak',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    STRENGTH_FAIR: {
      id: 'UI_AUTH_REGISTRATION_STRENGTH_FAIR',
      path: 'auth.registration.strength-fair',
      lifecycle: 'active',
      description: 'Password strength fair',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    STRENGTH_GOOD: {
      id: 'UI_AUTH_REGISTRATION_STRENGTH_GOOD',
      path: 'auth.registration.strength-good',
      lifecycle: 'active',
      description: 'Password strength good',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    STRENGTH_STRONG: {
      id: 'UI_AUTH_REGISTRATION_STRENGTH_STRONG',
      path: 'auth.registration.strength-strong',
      lifecycle: 'active',
      description: 'Password strength strong',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    REQ_MIN_LENGTH: {
uuid: '9d7afff3-a2d9-5e40-b2cb-509d4aeb07a2',
      id: 'UI_AUTH_REGISTRATION_REQ_MIN',
      path: 'auth.registration.req-min-length',
      lifecycle: 'active',
      description: 'Password requirement min length',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    REQ_UPPERCASE: {
      id: 'UI_AUTH_REGISTRATION_REQ_UPPER',
      path: 'auth.registration.req-uppercase',
      lifecycle: 'active',
      description: 'Password requirement uppercase',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    REQ_LOWERCASE: {
uuid: 'aea145a6-37e5-5029-961b-2ee8e1f1595b',
      id: 'UI_AUTH_REGISTRATION_REQ_LOWER',
      path: 'auth.registration.req-lowercase',
      lifecycle: 'active',
      description: 'Password requirement lowercase',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    REQ_NUMBER: {
uuid: '13d0a784-7c3f-573d-8318-160ac157d603',
      id: 'UI_AUTH_REGISTRATION_REQ_NUMBER',
      path: 'auth.registration.req-number',
      lifecycle: 'active',
      description: 'Password requirement number',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    REQ_SPECIAL: {
uuid: '79396ddc-0990-592f-86f9-1f12ba280d65',
      id: 'UI_AUTH_REGISTRATION_REQ_SPECIAL',
      path: 'auth.registration.req-special',
      lifecycle: 'active',
      description: 'Password requirement special char',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    VERIFYING_OTP: {
uuid: '54c78009-400c-5916-9ea4-998b723cb518',
      id: 'UI_AUTH_REGISTRATION_VERIFYING_OTP',
      path: 'auth.registration.verifying-otp-button',
      lifecycle: 'active',
      description: 'Registration verifying OTP button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUBMITTING_BUTTON: {
uuid: '0674e208-4ab7-5bcd-a071-4ef250f59f2f',
      id: 'UI_AUTH_REGISTRATION_SUBMITTING',
      path: 'auth.registration.submitting-button',
      lifecycle: 'active',
      description: 'Registration submitting button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PHONE_REQUIRED: {
uuid: '94739038-3c4f-5c81-b19e-4eaebc2358d7',
      id: 'UI_AUTH_REGISTRATION_PHONE_REQUIRED',
      path: 'auth.registration.phone-required-notice',
      lifecycle: 'active',
      description: 'Registration phone verification required notice',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUBMIT_BUTTON: {
uuid: 'd9ad77f4-fa94-5b1d-9c1e-921e2a94949f',
      id: 'UI_AUTH_REGISTRATION_SUBMIT',
      path: 'auth.registration.submit-button',
      lifecycle: 'active',
      description: 'Registration submit button',
      category: 'action',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SIGNIN_LINK: {
uuid: '89f7b3b7-4e1f-5a54-b585-3c997944e5de',
      id: 'UI_AUTH_REGISTRATION_SIGNIN_LINK',
      path: 'auth.registration.signin-link',
      lifecycle: 'active',
      description: 'Registration sign in link',
      category: 'navigation',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SIGNIN_PROMPT: {
uuid: 'e7342b91-ba9f-5612-91db-82ebfc351e8c',
      id: 'UI_AUTH_REGISTRATION_SIGNIN_PROMPT',
      path: 'auth.registration.signin-prompt',
      lifecycle: 'active',
      description: 'Registration sign in prompt',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUCCESS_HEADING: {
uuid: 'dab3ef8e-1b17-5f75-b73c-bf2c566325ab',
      id: 'UI_AUTH_REGISTRATION_SUCCESS_HEADING',
      path: 'auth.registration.success-heading',
      lifecycle: 'active',
      description: 'Registration success heading',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SUCCESS_DESCRIPTION: {
uuid: 'ecb64d3a-8163-5609-bb32-d374b3fbeec3',
      id: 'UI_AUTH_REGISTRATION_SUCCESS_DESCRIPTION',
      path: 'auth.registration.success-description',
      lifecycle: 'active',
      description: 'Registration success description',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
  },

  SHELL: {
    EMAIL_FIELD_WRAPPER: {
id: 'UI_AUTH_STRUCTURE_EMAIL_FIELD_WRAPPER',
      path: 'auth.dom.registration.email-field-wrapper',
      lifecycle: 'active',
      description: 'Structural element for email field wrapper',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-21',
      updatedAt: '2026-06-21',
} as const,
    EMAIL_FIELD_INPUT_WRAPPER: {
id: 'UI_AUTH_STRUCTURE_EMAIL_FIELD_INPUT_WRAPPER',
      path: 'auth.dom.registration.email-field-input-wrapper',
      lifecycle: 'active',
      description: 'Structural element for email input wrapper',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-21',
      updatedAt: '2026-06-21',
} as const,
    EMAIL_ERROR: {
id: 'UI_AUTH_STRUCTURE_EMAIL_ERROR',
      path: 'auth.dom.registration.email-error',
      lifecycle: 'active',
      description: 'Structural element for email error message',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-21',
      updatedAt: '2026-06-21',
} as const,
    REGISTRATION_BRAND_NAME_WRAPPER_L23: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_BRAND_NAME_WRAPPER_L23',
      path: 'auth.dom.auth-hero.registration-brand-name-wrapper-l23',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/AuthHero.tsx:23',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_BRAND_NAME_WRAPPER_L24: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_BRAND_NAME_WRAPPER_L24',
      path: 'auth.dom.auth-hero.registration-brand-name-wrapper-l24',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/AuthHero.tsx:24',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_BRAND_NAME_WRAPPER_L28: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_BRAND_NAME_WRAPPER_L28',
      path: 'auth.dom.auth-hero.registration-brand-name-wrapper-l28',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/AuthHero.tsx:28',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SHARED_HIGHLIGHT_SECURITY_WRAPPER_L50: {
      id: 'UI_AUTH_STRUCTURE_SHARED_HIGHLIGHT_SECURITY_WRAPPER_L50',
      path: 'auth.dom.auth-hero.shared-highlight-security-wrapper-l50',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/AuthHero.tsx:50',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SHARED_HIGHLIGHT_SECURITY_WRAPPER_L51: {
      id: 'UI_AUTH_STRUCTURE_SHARED_HIGHLIGHT_SECURITY_WRAPPER_L51',
      path: 'auth.dom.auth-hero.shared-highlight-security-wrapper-l51',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/AuthHero.tsx:51',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SHARED_HIGHLIGHT_PHONE_WRAPPER_L55: {
      id: 'UI_AUTH_STRUCTURE_SHARED_HIGHLIGHT_PHONE_WRAPPER_L55',
      path: 'auth.dom.auth-hero.shared-highlight-phone-wrapper-l55',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/AuthHero.tsx:55',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SHARED_HIGHLIGHT_ENCRYPTED_WRAPPER_L59: {
      id: 'UI_AUTH_STRUCTURE_SHARED_HIGHLIGHT_ENCRYPTED_WRAPPER_L59',
      path: 'auth.dom.auth-hero.shared-highlight-encrypted-wrapper-l59',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/AuthHero.tsx:59',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SUCCESS_HEADING_WRAPPER_L58: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_SUCCESS_HEADING_WRAPPER_L58',
      path: 'auth.dom.login-page-content.login-success-heading-wrapper-l58',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:56',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SUCCESS_HEADING_WRAPPER_L61: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_SUCCESS_HEADING_WRAPPER_L61',
      path: 'auth.dom.login-page-content.login-success-heading-wrapper-l61',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:59',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_HEADING_WRAPPER_L80: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_HEADING_WRAPPER_L80',
      path: 'auth.dom.login-page-content.login-heading-wrapper-l80',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:78',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_HEADING_CONTAINER_L84: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_HEADING_CONTAINER_L84',
      path: 'auth.dom.login-page-content.login-heading-container-l84',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:82',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_HEADING_WRAPPER_L87: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_HEADING_WRAPPER_L87',
      path: 'auth.dom.login-page-content.login-heading-wrapper-l87',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:85',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_GUEST_LOGIN_WRAPPER_L95: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_GUEST_LOGIN_WRAPPER_L95',
      path: 'auth.dom.login-page-content.login-guest-login-wrapper-l95',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:93',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_PHONE_INPUT_WRAPPER_L100: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_PHONE_INPUT_WRAPPER_L100',
      path: 'auth.dom.login-page-content.login-phone-input-wrapper-l100',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:98',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_PHONE_INPUT_WRAPPER_L105: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_PHONE_INPUT_WRAPPER_L105',
      path: 'auth.dom.login-page-content.login-phone-input-wrapper-l105',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:103',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_PHONE_INPUT_SPAN_L106: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_PHONE_INPUT_SPAN_L106',
      path: 'auth.dom.login-page-content.login-phone-input-span-l106',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:104',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_HEADING_WRAPPER_L112: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_HEADING_WRAPPER_L112',
      path: 'auth.dom.login-page-content.login-heading-wrapper-l112',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:110',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_PASSWORD_INPUT_WRAPPER_L122: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_PASSWORD_INPUT_WRAPPER_L122',
      path: 'auth.dom.login-page-content.login-password-input-wrapper-l122',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:120',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_PASSWORD_INPUT_WRAPPER_L123: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_PASSWORD_INPUT_WRAPPER_L123',
      path: 'auth.dom.login-page-content.login-password-input-wrapper-l123',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:121',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_PASSWORD_INPUT_WRAPPER_L134: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_PASSWORD_INPUT_WRAPPER_L134',
      path: 'auth.dom.login-page-content.login-password-input-wrapper-l134',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:132',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_HEADING_WRAPPER_L141: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_HEADING_WRAPPER_L141',
      path: 'auth.dom.login-page-content.login-heading-wrapper-l141',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:139',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SIGNUP_DIVIDER_WRAPPER_L171: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_SIGNUP_DIVIDER_WRAPPER_L171',
      path: 'auth.dom.login-page-content.login-signup-divider-wrapper-l171',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:169',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SIGNUP_DIVIDER_WRAPPER_L172: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_SIGNUP_DIVIDER_WRAPPER_L172',
      path: 'auth.dom.login-page-content.login-signup-divider-wrapper-l172',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:170',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SIGNUP_DIVIDER_WRAPPER_L173: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_SIGNUP_DIVIDER_WRAPPER_L173',
      path: 'auth.dom.login-page-content.login-signup-divider-wrapper-l173',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:171',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SIGNUP_DIVIDER_WRAPPER_L174: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_SIGNUP_DIVIDER_WRAPPER_L174',
      path: 'auth.dom.login-page-content.login-signup-divider-wrapper-l174',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:172',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SIGNUP_DIVIDER_WRAPPER_L176: {
      id: 'UI_AUTH_STRUCTURE_LOGIN_SIGNUP_DIVIDER_WRAPPER_L176',
      path: 'auth.dom.login-page-content.login-signup-divider-wrapper-l176',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/LoginPageContent.tsx:174',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    OTP_INPUT_L63: {
      id: 'UI_AUTH_STRUCTURE_OTP_INPUT_L63',
      path: 'auth.dom.otp-input.otp-input-l63',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/OtpInput.tsx:63',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LABELIDENTITY_WRAPPER_L37: {
      id: 'UI_AUTH_STRUCTURE_LABELIDENTITY_WRAPPER_L37',
      path: 'auth.dom.password-input.labelidentity-wrapper-l37',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordInput.tsx:37',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LABELIDENTITY_WRAPPER_L41: {
      id: 'UI_AUTH_STRUCTURE_LABELIDENTITY_WRAPPER_L41',
      path: 'auth.dom.password-input.labelidentity-wrapper-l41',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordInput.tsx:41',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PASSWORD_INPUT_L48: {
      id: 'UI_AUTH_STRUCTURE_PASSWORD_INPUT_L48',
      path: 'auth.dom.password-input.password-input-l48',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordInput.tsx:48',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PASSWORD_STRENGTH_WRAPPER_L41: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PASSWORD_STRENGTH_WRAPPER_L41',
      path: 'auth.dom.password-strength.registration-password-strength-wrapper-l41',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordStrength.tsx:41',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PASSWORD_STRENGTH_WRAPPER_L44: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PASSWORD_STRENGTH_WRAPPER_L44',
      path: 'auth.dom.password-strength.registration-password-strength-wrapper-l44',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordStrength.tsx:44',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PASSWORD_STRENGTH_WRAPPER_L54: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PASSWORD_STRENGTH_WRAPPER_L54',
      path: 'auth.dom.password-strength.registration-password-strength-wrapper-l54',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordStrength.tsx:54',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PASSWORD_STRENGTH_CONTAINER_L56: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PASSWORD_STRENGTH_CONTAINER_L56',
      path: 'auth.dom.password-strength.registration-password-strength-container-l56',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordStrength.tsx:56',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_WRAPPER_L59: {
      id: 'UI_AUTH_STRUCTURE_KEY_WRAPPER_L59',
      path: 'auth.dom.password-strength.key-wrapper-l59',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PasswordStrength.tsx:59',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PHONE_INPUT_WRAPPER_L88: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PHONE_INPUT_WRAPPER_L88',
      path: 'auth.dom.phone-verification.registration-phone-input-wrapper-l88',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:88',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PHONE_INPUT_WRAPPER_L92: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PHONE_INPUT_WRAPPER_L92',
      path: 'auth.dom.phone-verification.registration-phone-input-wrapper-l92',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:92',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PHONE_INPUT_WRAPPER_L93: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PHONE_INPUT_WRAPPER_L93',
      path: 'auth.dom.phone-verification.registration-phone-input-wrapper-l93',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:93',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PHONE_INPUT_SPAN_L94: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PHONE_INPUT_SPAN_L94',
      path: 'auth.dom.phone-verification.registration-phone-input-span-l94',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:94',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PHONE_VERIFICATION_L131: {
      id: 'UI_AUTH_STRUCTURE_PHONE_VERIFICATION_L131',
      path: 'auth.dom.phone-verification.phone-verification-l131',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:131',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_OTP_LABEL_WRAPPER_L139: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_OTP_LABEL_WRAPPER_L139',
      path: 'auth.dom.phone-verification.registration-otp-label-wrapper-l139',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:139',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_OTP_LABEL_WRAPPER_L143: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_OTP_LABEL_WRAPPER_L143',
      path: 'auth.dom.phone-verification.registration-otp-label-wrapper-l143',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:143',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PHONE_VERIFICATION_L156: {
      id: 'UI_AUTH_STRUCTURE_PHONE_VERIFICATION_L156',
      path: 'auth.dom.phone-verification.phone-verification-l156',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:156',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_OTP_LABEL_WRAPPER_L158: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_OTP_LABEL_WRAPPER_L158',
      path: 'auth.dom.phone-verification.registration-otp-label-wrapper-l158',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/PhoneVerification.tsx:158',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_SUCCESS_HEADING_WRAPPER_L65: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_SUCCESS_HEADING_WRAPPER_L65',
      path: 'auth.dom.registration-page-content.registration-success-heading-wrapper-l65',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:63',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_SUCCESS_HEADING_WRAPPER_L68: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_SUCCESS_HEADING_WRAPPER_L68',
      path: 'auth.dom.registration-page-content.registration-success-heading-wrapper-l68',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:66',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_TITLE_WRAPPER_L85: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_TITLE_WRAPPER_L85',
      path: 'auth.dom.registration-page-content.registration-title-wrapper-l85',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:83',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_TITLE_CONTAINER_L89: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_TITLE_CONTAINER_L89',
      path: 'auth.dom.registration-page-content.registration-title-container-l89',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:87',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_TITLE_WRAPPER_L92: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_TITLE_WRAPPER_L92',
      path: 'auth.dom.registration-page-content.registration-title-wrapper-l92',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:90',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PHONE_REQUIRED_WRAPPER_L100: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PHONE_REQUIRED_WRAPPER_L100',
      path: 'auth.dom.registration-page-content.registration-phone-required-wrapper-l100',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:98',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PHONE_REQUIRED_WRAPPER_L103: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PHONE_REQUIRED_WRAPPER_L103',
      path: 'auth.dom.registration-page-content.registration-phone-required-wrapper-l103',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:101',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_PHONE_REQUIRED_WRAPPER_L117: {
      id: 'UI_AUTH_STRUCTURE_REGISTRATION_PHONE_REQUIRED_WRAPPER_L117',
      path: 'auth.dom.registration-page-content.registration-phone-required-wrapper-l117',
      lifecycle: 'active',
      description: 'Structural element at src/components/auth/RegistrationPageContent.tsx:115',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SUCCESS_PAGE: {
      id: 'UI_AUTH_LOGIN_SUCCESS_PAGE',
      path: 'auth.dom.login-page-content.login-success-page',
      lifecycle: 'active',
      description: 'Login success page container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGIN_SUCCESS_FORM_CARD: {
      id: 'UI_AUTH_LOGIN_SUCCESS_FORM_CARD',
      path: 'auth.dom.login-page-content.login-success-form-card',
      lifecycle: 'active',
      description: 'Login success form card container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_SUCCESS_PAGE: {
      id: 'UI_AUTH_REGISTRATION_SUCCESS_PAGE',
      path: 'auth.dom.registration-page-content.registration-success-page',
      lifecycle: 'active',
      description: 'Registration success page container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_SUCCESS_FORM_CARD: {
      id: 'UI_AUTH_REGISTRATION_SUCCESS_FORM_CARD',
      path: 'auth.dom.registration-page-content.registration-success-form-card',
      lifecycle: 'active',
      description: 'Registration success form card container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PASSWORD_FIELD_WRAPPER: {
      id: 'UI_AUTH_SHELL_PASSWORD_FIELD_WRAPPER',
      path: 'auth.dom.password-input.password-field-wrapper',
      lifecycle: 'active',
      description: 'Password field wrapper container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PASSWORD_FIELD_INPUT_WRAPPER: {
      id: 'UI_AUTH_SHELL_PASSWORD_FIELD_INPUT_WRAPPER',
      path: 'auth.dom.password-input.password-field-input-wrapper',
      lifecycle: 'active',
      description: 'Password field input wrapper container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CONFIRM_PASSWORD_FIELD_WRAPPER: {
      id: 'UI_AUTH_SHELL_CONFIRM_PASSWORD_FIELD_WRAPPER',
      path: 'auth.dom.password-input.confirm-password-field-wrapper',
      lifecycle: 'active',
      description: 'Confirm password field wrapper container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CONFIRM_PASSWORD_FIELD_INPUT_WRAPPER: {
      id: 'UI_AUTH_SHELL_CONFIRM_PASSWORD_FIELD_INPUT_WRAPPER',
      path: 'auth.dom.password-input.confirm-password-field-input-wrapper',
      lifecycle: 'active',
      description: 'Confirm password field input wrapper container',
      category: 'container',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CONFIRM_PASSWORD_ERROR: {
      id: 'UI_AUTH_SHELL_CONFIRM_PASSWORD_ERROR',
      path: 'auth.dom.password-input.confirm-password-error',
      lifecycle: 'active',
      description: 'Confirm password field error message',
      category: 'display',
      feature: 'auth',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },} as const;

export type AuthUiIdentity = typeof AUTH;
