/** DevTools registry identities */
export const DEVTOOLS = {
  UI_INSPECTOR: {
    PAGE: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PAGE_CONTAINER',
        path: 'devtools.inspector.page.container',
        lifecycle: 'active',
        description: 'Standalone UI Inspector page root container at src/app/devtools/ui-inspector/page.tsx',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    HEADER: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_HEADER_CONTAINER',
        path: 'devtools.inspector.header.container',
        lifecycle: 'active',
        description: 'UI Inspector top toolbar container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TITLE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_HEADER_TITLE',
        path: 'devtools.inspector.header.title',
        lifecycle: 'active',
        description: 'UI Inspector page title',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ROUTE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_ROUTE_LABEL',
        path: 'devtools.inspector.route.label',
        lifecycle: 'active',
        description: 'Target route dropdown label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ROUTE_SELECT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_ROUTE_SELECT',
        path: 'devtools.inspector.route.select',
        lifecycle: 'active',
        description: 'Target route dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ROUTE_OPTION: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_ROUTE_OPTION',
        path: 'devtools.inspector.route.option',
        lifecycle: 'active',
        description: 'Target route dropdown option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      REFRESH_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_REFRESH_BUTTON',
        path: 'devtools.inspector.refresh.button',
        lifecycle: 'active',
        description: 'Refresh iframe scan button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      OPEN_TAB_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_OPEN_TAB_BUTTON',
        path: 'devtools.inspector.open.tab',
        lifecycle: 'active',
        description: 'Open inspected target route in a new browser tab',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    STATUS: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_CONTAINER',
        path: 'devtools.inspector.status.container',
        lifecycle: 'active',
        description: 'Inspector connection and scan status bar',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      IFRAME_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_IFRAME_VALUE',
        path: 'devtools.inspector.status.iframe',
        lifecycle: 'active',
        description: 'Iframe ready or loading status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCAN_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_SCAN_VALUE',
        path: 'devtools.inspector.status.scan',
        lifecycle: 'active',
        description: 'Last scan timestamp status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COUNT_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_COUNT_VALUE',
        path: 'devtools.inspector.status.count',
        lifecycle: 'active',
        description: 'Scanned element count status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      URL_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_URL_VALUE',
        path: 'devtools.inspector.status.url',
        lifecycle: 'active',
        description: 'Current iframe target URL status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    WORKSPACE: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_WORKSPACE_CONTAINER',
        path: 'devtools.inspector.workspace.container',
        lifecycle: 'active',
        description: 'Main workspace split container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    SIDEBAR: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_CONTAINER',
        path: 'devtools.inspector.sidebar.container',
        lifecycle: 'active',
        description: 'Inspector sidebar with filters and element list',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SEARCH_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SEARCH_LABEL',
        path: 'devtools.inspector.search.label',
        lifecycle: 'active',
        description: 'Search input label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SEARCH_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SEARCH_INPUT',
        path: 'devtools.inspector.search.input',
        lifecycle: 'active',
        description: 'Search by uuid/id/path/feature',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_FEATURE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_FEATURE_LABEL',
        path: 'devtools.inspector.feature.label',
        lifecycle: 'active',
        description: 'Feature filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_FEATURE_SELECT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_FEATURE_SELECT',
        path: 'devtools.inspector.feature.select',
        lifecycle: 'active',
        description: 'Feature filter dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_FEATURE_OPTION: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_FEATURE_OPTION',
        path: 'devtools.inspector.feature.option',
        lifecycle: 'active',
        description: 'Feature filter option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      FILTER_TAG_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_TAG_LABEL',
        path: 'devtools.inspector.tag.label',
        lifecycle: 'active',
        description: 'Tag type filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_TAG_SELECT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_TAG_SELECT',
        path: 'devtools.inspector.tag.select',
        lifecycle: 'active',
        description: 'Tag type filter dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_TAG_OPTION: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_TAG_OPTION',
        path: 'devtools.inspector.tag.option',
        lifecycle: 'active',
        description: 'Tag type filter option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      FILTER_LIFECYCLE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_LIFECYCLE_LABEL',
        path: 'devtools.inspector.lifecycle.label',
        lifecycle: 'active',
        description: 'Lifecycle filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_LIFECYCLE_SELECT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_LIFECYCLE_SELECT',
        path: 'devtools.inspector.lifecycle.select',
        lifecycle: 'active',
        description: 'Lifecycle filter dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_LIFECYCLE_OPTION: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_LIFECYCLE_OPTION',
        path: 'devtools.inspector.lifecycle.option',
        lifecycle: 'active',
        description: 'Lifecycle filter option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      FILTER_MISSING_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_MISSING_LABEL',
        path: 'devtools.inspector.missing.label',
        lifecycle: 'active',
        description: 'Missing source filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_MISSING_CHECKBOX: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_MISSING_CHECKBOX',
        path: 'devtools.inspector.missing.checkbox',
        lifecycle: 'active',
        description: 'Missing source filter checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIST: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_ELEMENT_LIST',
        path: 'devtools.inspector.list.container',
        lifecycle: 'active',
        description: 'Scanned element list container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIST_ITEM: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_ELEMENT_LIST_ITEM',
        path: 'devtools.inspector.list.item',
        lifecycle: 'active',
        description: 'Scanned element list item button',
        category: 'navigation',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      COUNT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_ELEMENT_COUNT',
        path: 'devtools.inspector.list.count',
        lifecycle: 'active',
        description: 'Filtered element count label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DISPLAY_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DISPLAY_LABEL',
        path: 'devtools.inspector.sidebar.display',
        lifecycle: 'active',
        description: 'Collapsible display section label in sidebar',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DATABASE_SECTION_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DATABASE_LABEL',
        path: 'devtools.inspector.sidebar.database',
        lifecycle: 'active',
        description: 'Collapsible database section label in sidebar',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTES_SECTION_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_ATTRIBUTES_LABEL',
        path: 'devtools.inspector.sidebar.attributes',
        lifecycle: 'active',
        description: 'Collapsible attributes section label in sidebar',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_ATTRIBUTES_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DBATTRS_LABEL',
        path: 'devtools.inspector.sidebar.dbattrs',
        lifecycle: 'active',
        description: 'Collapsible database and attributes section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_MANAGEMENT_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DBMGMT_LABEL',
        path: 'devtools.inspector.sidebar.dbmgmt',
        lifecycle: 'active',
        description: 'Collapsible database management section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCHEMA_EDITOR_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_SCHEMA_LABEL',
        path: 'devtools.inspector.sidebar.schema',
        lifecycle: 'active',
        description: 'Collapsible schema editor section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    DETAILS: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_CONTAINER',
        path: 'devtools.inspector.detail.container',
        lifecycle: 'active',
        description: 'Selected element details panel',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TITLE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_TITLE',
        path: 'devtools.inspector.detail.title',
        lifecycle: 'active',
        description: 'Details panel title',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      UUID_LABEL: {
uuid: '52ab65d2-15ad-5a83-930b-805c6f911f85',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_UUID_LABEL',
        path: 'devtools.inspector.uuid.label',
        lifecycle: 'active',
        description: 'UUID field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      UUID_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_UUID_VALUE',
        path: 'devtools.inspector.uuid.value',
        lifecycle: 'active',
        description: 'UUID field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STABLE_ID_LABEL: {
uuid: '21192078-251a-574f-ac19-ac5280bfb2c9',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_STABLE_ID_LABEL',
        path: 'devtools.inspector.stableid.label',
        lifecycle: 'active',
        description: 'Stable id field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STABLE_ID_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_STABLE_ID_VALUE',
        path: 'devtools.inspector.stableid.value',
        lifecycle: 'active',
        description: 'Stable id field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      PATH_LABEL: {
uuid: '374af8c6-3695-5db7-a475-0550c85490a9',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_PATH_LABEL',
        path: 'devtools.inspector.path.label',
        lifecycle: 'active',
        description: 'Identity path field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      PATH_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_PATH_VALUE',
        path: 'devtools.inspector.path.value',
        lifecycle: 'active',
        description: 'Identity path field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FEATURE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_FEATURE_LABEL',
        path: 'devtools.inspector.meta.feature-label',
        lifecycle: 'active',
        description: 'Feature field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FEATURE_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_FEATURE_VALUE',
        path: 'devtools.inspector.meta.feature-value',
        lifecycle: 'active',
        description: 'Feature field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIFECYCLE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_LIFECYCLE_LABEL',
        path: 'devtools.inspector.meta.lifecycle-label',
        lifecycle: 'active',
        description: 'Lifecycle field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIFECYCLE_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_LIFECYCLE_VALUE',
        path: 'devtools.inspector.meta.lifecycle-value',
        lifecycle: 'active',
        description: 'Lifecycle field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TAG_LABEL: {
uuid: 'a1a82465-df44-5e36-8d62-de57ee80ef00',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_TAG_LABEL',
        path: 'devtools.inspector.meta.tag-label',
        lifecycle: 'active',
        description: 'Tag field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TAG_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_TAG_VALUE',
        path: 'devtools.inspector.meta.tag-value',
        lifecycle: 'active',
        description: 'Tag field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_FILE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_FILE_LABEL',
        path: 'devtools.inspector.source.file-label',
        lifecycle: 'active',
        description: 'Source file field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_FILE_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_FILE_VALUE',
        path: 'devtools.inspector.source.file-value',
        lifecycle: 'active',
        description: 'Source file field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_COMPONENT_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_COMPONENT_LABEL',
        path: 'devtools.inspector.source.component-label',
        lifecycle: 'active',
        description: 'Source component field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_COMPONENT_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_COMPONENT_VALUE',
        path: 'devtools.inspector.source.component-value',
        lifecycle: 'active',
        description: 'Source component field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_LINE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_LINE_LABEL',
        path: 'devtools.inspector.source.line-label',
        lifecycle: 'active',
        description: 'Source line field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_LINE_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_LINE_VALUE',
        path: 'devtools.inspector.source.line-value',
        lifecycle: 'active',
        description: 'Source line field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INSTANCE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_INSTANCE_LABEL',
        path: 'devtools.inspector.instance.label',
        lifecycle: 'active',
        description: 'Instance id field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INSTANCE_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_INSTANCE_VALUE',
        path: 'devtools.inspector.instance.value',
        lifecycle: 'active',
        description: 'Instance id field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      IDENTITY_KEY_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_IDENTITY_KEY_LABEL',
        path: 'devtools.inspector.identity.label',
        lifecycle: 'active',
        description: 'Identity key field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      IDENTITY_KEY_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_IDENTITY_KEY_VALUE',
        path: 'devtools.inspector.identity.value',
        lifecycle: 'active',
        description: 'Identity key field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COPY_UUID_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_COPY_UUID_BUTTON',
        path: 'devtools.inspector.copy.uuid-button',
        lifecycle: 'active',
        description: 'Copy UUID button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COPY_PATH_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_COPY_PATH_BUTTON',
        path: 'devtools.inspector.copy.path-button',
        lifecycle: 'active',
        description: 'Copy identity path button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COPY_SOURCE_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_COPY_SOURCE_BUTTON',
        path: 'devtools.inspector.copy.source-button',
        lifecycle: 'active',
        description: 'Copy source location button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      HIGHLIGHT_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_HIGHLIGHT_BUTTON',
        path: 'devtools.inspector.preview.highlight',
        lifecycle: 'active',
        description: 'Highlight element in preview button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCROLL_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SCROLL_BUTTON',
        path: 'devtools.inspector.preview.scroll',
        lifecycle: 'active',
        description: 'Scroll to element in preview button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      EMPTY_MESSAGE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_EMPTY_MESSAGE',
        path: 'devtools.inspector.detail.empty',
        lifecycle: 'active',
        description: 'Empty selection message',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    LAYOUT: {
      RESIZER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_LAYOUT_RESIZER',
        path: 'devtools.inspector.layout.resizer',
        lifecycle: 'active',
        description: 'Sidebar width resize handle',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    PICK: {
      MODE_TOGGLE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PICK_MODE_TOGGLE',
        path: 'devtools.inspector.pick.toggle',
        lifecycle: 'active',
        description: 'Toggle mouse pick mode in preview iframe',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    SELECTED: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_SELECTED_CONTAINER',
        path: 'devtools.inspector.selected.container',
        lifecycle: 'active',
        description: 'Selected element summary container in sidebar',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    DATA: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_CONTAINER',
        path: 'devtools.inspector.data.container',
        lifecycle: 'active',
        description: 'Inspector data entry container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      DATABASE_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_DATABASE_LABEL',
        path: 'devtools.inspector.data.database',
        lifecycle: 'active',
        description: 'Database section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DATABASE_TOGGLE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_DATABASE_TOGGLE',
        path: 'devtools.inspector.db.toggle',
        lifecycle: 'active',
        description: 'Database enabled toggle',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF1_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF1_LABEL',
        path: 'devtools.inspector.inf1.label',
        lifecycle: 'active',
        description: 'Database inf1 field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF1_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF1_INPUT',
        path: 'devtools.inspector.inf1.input',
        lifecycle: 'active',
        description: 'Database inf1 text input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF2_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF2_LABEL',
        path: 'devtools.inspector.inf2.label',
        lifecycle: 'active',
        description: 'Database inf2 field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF2_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF2_INPUT',
        path: 'devtools.inspector.inf2.input',
        lifecycle: 'active',
        description: 'Database inf2 text input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF3_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF3_LABEL',
        path: 'devtools.inspector.inf3.label',
        lifecycle: 'active',
        description: 'Database inf3 field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF3_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF3_INPUT',
        path: 'devtools.inspector.inf3.input',
        lifecycle: 'active',
        description: 'Database inf3 text input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTES_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTES_LABEL',
        path: 'devtools.inspector.data.attributes',
        lifecycle: 'active',
        description: 'Attributes section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTES_TOGGLE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTES_TOGGLE',
        path: 'devtools.inspector.attr.toggle',
        lifecycle: 'active',
        description: 'Attributes enabled toggle',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE1_CHECKBOX: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE1_CHECKBOX',
        path: 'devtools.inspector.data.attribute1',
        lifecycle: 'active',
        description: 'Attribute 1 checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE1_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE1_LABEL',
        path: 'devtools.inspector.attr1.label',
        lifecycle: 'active',
        description: 'Attribute 1 checkbox label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE2_CHECKBOX: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE2_CHECKBOX',
        path: 'devtools.inspector.data.attribute2',
        lifecycle: 'active',
        description: 'Attribute 2 checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE2_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE2_LABEL',
        path: 'devtools.inspector.attr2.label',
        lifecycle: 'active',
        description: 'Attribute 2 checkbox label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE3_CHECKBOX: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE3_CHECKBOX',
        path: 'devtools.inspector.data.attribute3',
        lifecycle: 'active',
        description: 'Attribute 3 checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE3_LABEL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE3_LABEL',
        path: 'devtools.inspector.attr3.label',
        lifecycle: 'active',
        description: 'Attribute 3 checkbox label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SAVE_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_SAVE_BUTTON',
        path: 'devtools.inspector.data.save',
        lifecycle: 'active',
        description: 'Save inspector data to JSON file',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    DBMGMT: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBMGMT_CONTAINER',
        path: 'devtools.inspector.dbmgmt.container',
        lifecycle: 'active',
        description: 'Database management descriptions panel',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      DESC_TEXTAREA: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBMGMT_DESC_TEXTAREA',
        path: 'devtools.inspector.dbmgmt.desc',
        lifecycle: 'active',
        description: 'Description textarea in database management',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      SAVE_DESC_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBMGMT_SAVE_DESC',
        path: 'devtools.inspector.dbmgmt.save-desc',
        lifecycle: 'active',
        description: 'Save description button in database management',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
    },
    DBREF: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_CONTAINER',
        path: 'devtools.inspector.dbref.container',
        lifecycle: 'active',
        description: 'Database reference schema editor container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      SAVE_BUTTON: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_SAVE_BUTTON',
        path: 'devtools.inspector.dbref.save',
        lifecycle: 'active',
        description: 'Save database_ref.json schema file',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_SELECT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DB_SELECT',
        path: 'devtools.inspector.refdb.select',
        lifecycle: 'active',
        description: 'Database picker in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TABLE_SELECT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_TABLE_SELECT',
        path: 'devtools.inspector.reftb.select',
        lifecycle: 'active',
        description: 'Table picker in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COLUMN_SELECT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_COLUMN_SELECT',
        path: 'devtools.inspector.refcol.select',
        lifecycle: 'active',
        description: 'Column picker in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_AR_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DB_AR_INPUT',
        path: 'devtools.inspector.dbar.input',
        lifecycle: 'active',
        description: 'Arabic database name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_EN_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DB_EN_INPUT',
        path: 'devtools.inspector.dben.input',
        lifecycle: 'active',
        description: 'English database name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TABLE_AR_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_TABLE_AR_INPUT',
        path: 'devtools.inspector.tbar.input',
        lifecycle: 'active',
        description: 'Arabic table name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TABLE_EN_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_TABLE_EN_INPUT',
        path: 'devtools.inspector.tben.input',
        lifecycle: 'active',
        description: 'English table name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COLUMN_AR_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_COLUMN_AR_INPUT',
        path: 'devtools.inspector.colar.input',
        lifecycle: 'active',
        description: 'Arabic column name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COLUMN_EN_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_COLUMN_EN_INPUT',
        path: 'devtools.inspector.colen.input',
        lifecycle: 'active',
        description: 'English column name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ADD_DB: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_ADD_DB',
        path: 'devtools.inspector.adddb.action',
        lifecycle: 'active',
        description: 'Add database entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ADD_TABLE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_ADD_TABLE',
        path: 'devtools.inspector.addtb.action',
        lifecycle: 'active',
        description: 'Add table entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ADD_COLUMN: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_ADD_COLUMN',
        path: 'devtools.inspector.addcol.action',
        lifecycle: 'active',
        description: 'Add column entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DELETE_DB: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DELETE_DB',
        path: 'devtools.inspector.deldb.action',
        lifecycle: 'active',
        description: 'Delete database entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DELETE_TABLE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DELETE_TABLE',
        path: 'devtools.inspector.deltb.action',
        lifecycle: 'active',
        description: 'Delete table entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DELETE_COLUMN: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DELETE_COLUMN',
        path: 'devtools.inspector.delcol.action',
        lifecycle: 'active',
        description: 'Delete column entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    PREVIEW: {
      CONTAINER: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_CONTAINER',
        path: 'devtools.inspector.preview.container',
        lifecycle: 'active',
        description: 'Preview iframe container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      IFRAME: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_IFRAME',
        path: 'devtools.inspector.preview.iframe',
        lifecycle: 'active',
        description: 'Target page preview iframe',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      CONTROLS: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_CONTROLS',
        path: 'devtools.inspector.preview.controls',
        lifecycle: 'active',
        description: 'Preview size and zoom controls bar',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCROLL: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_SCROLL',
        path: 'devtools.inspector.preview.viewport',
        lifecycle: 'active',
        description: 'Scrollable preview viewport',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FRAME: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_FRAME',
        path: 'devtools.inspector.preview.frame',
        lifecycle: 'active',
        description: 'Resizable preview frame wrapper',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ZOOM_OUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_ZOOM_OUT',
        path: 'devtools.inspector.preview.zoom-out',
        lifecycle: 'active',
        description: 'Decrease preview zoom button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ZOOM_IN: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_ZOOM_IN',
        path: 'devtools.inspector.preview.zoom-in',
        lifecycle: 'active',
        description: 'Increase preview zoom button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ZOOM_VALUE: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_ZOOM_VALUE',
        path: 'devtools.inspector.preview.zoom',
        lifecycle: 'active',
        description: 'Preview zoom percentage input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      WIDTH_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_WIDTH_INPUT',
        path: 'devtools.inspector.preview.width',
        lifecycle: 'active',
        description: 'Preview frame width input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      HEIGHT_INPUT: {
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_HEIGHT_INPUT',
        path: 'devtools.inspector.preview.height',
        lifecycle: 'active',
        description: 'Preview frame height input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
  },
} as const;
