/** DevTools registry identities */
export const DEVTOOLS = {
  UI_INSPECTOR: {
    PAGE: {
      CONTAINER: {
uuid: '3e6bf0dc-c5cc-5aed-b003-9c529c9edd2b',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PAGE_CONTAINER',
        path: 'devtools.inspector.page.container',
        lifecycle: 'active',
        description: 'Standalone UI Inspector page root container at src/app/devtools/ui-inspector/page.tsx',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    HEADER: {
      CONTAINER: {
uuid: '255c562e-fc5b-51c7-b441-bb2438bdcc75',
id: 'UI_DEVTOOLS_UI_INSPECTOR_HEADER_CONTAINER',
        path: 'devtools.inspector.header.container',
        lifecycle: 'active',
        description: 'UI Inspector top toolbar container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TITLE: {
uuid: '0c5f1033-fa7d-55f6-ad8b-7c2d26631700',
id: 'UI_DEVTOOLS_UI_INSPECTOR_HEADER_TITLE',
        path: 'devtools.inspector.header.title',
        lifecycle: 'active',
        description: 'UI Inspector page title',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ROUTE_LABEL: {
uuid: '395d7741-ef14-5f76-951a-ea6f5c521314',
id: 'UI_DEVTOOLS_UI_INSPECTOR_ROUTE_LABEL',
        path: 'devtools.inspector.route.label',
        lifecycle: 'active',
        description: 'Target route dropdown label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ROUTE_SELECT: {
uuid: '0f00a1f1-7f73-50e0-a235-e11735e44d86',
id: 'UI_DEVTOOLS_UI_INSPECTOR_ROUTE_SELECT',
        path: 'devtools.inspector.route.select',
        lifecycle: 'active',
        description: 'Target route dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ROUTE_OPTION: {
uuid: '58f620b8-bdba-5fc1-97f9-2c2275342c63',
id: 'UI_DEVTOOLS_UI_INSPECTOR_ROUTE_OPTION',
        path: 'devtools.inspector.route.option',
        lifecycle: 'active',
        description: 'Target route dropdown option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      REFRESH_BUTTON: {
uuid: '3525455f-5494-5b9e-b0ab-62698edfdfe0',
id: 'UI_DEVTOOLS_UI_INSPECTOR_REFRESH_BUTTON',
        path: 'devtools.inspector.refresh.button',
        lifecycle: 'active',
        description: 'Refresh iframe scan button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      OPEN_TAB_BUTTON: {
uuid: '7beaff08-4635-51cf-9b2c-be6e88e64de5',
id: 'UI_DEVTOOLS_UI_INSPECTOR_OPEN_TAB_BUTTON',
        path: 'devtools.inspector.open.tab',
        lifecycle: 'active',
        description: 'Open inspected target route in a new browser tab',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    STATUS: {
      CONTAINER: {
uuid: '6ef1ab39-2641-5ba0-a65a-19dba02f794a',
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_CONTAINER',
        path: 'devtools.inspector.status.container',
        lifecycle: 'active',
        description: 'Inspector connection and scan status bar',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      IFRAME_VALUE: {
uuid: '26ad9de4-6b76-509b-a44a-ce36251665cd',
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_IFRAME_VALUE',
        path: 'devtools.inspector.status.iframe',
        lifecycle: 'active',
        description: 'Iframe ready or loading status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCAN_VALUE: {
uuid: 'c588e7d1-86a9-5482-8d0d-7e0fffef5068',
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_SCAN_VALUE',
        path: 'devtools.inspector.status.scan',
        lifecycle: 'active',
        description: 'Last scan timestamp status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COUNT_VALUE: {
uuid: 'bc790843-3405-53a6-b812-4795f812e1e8',
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_COUNT_VALUE',
        path: 'devtools.inspector.status.count',
        lifecycle: 'active',
        description: 'Scanned element count status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      URL_VALUE: {
uuid: 'd91ecc1d-6630-5248-bc44-455710a726fa',
id: 'UI_DEVTOOLS_UI_INSPECTOR_STATUS_URL_VALUE',
        path: 'devtools.inspector.status.url',
        lifecycle: 'active',
        description: 'Current iframe target URL status value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    WORKSPACE: {
      CONTAINER: {
uuid: '6a43c38c-5ec7-5087-b8b1-c4526b26e60d',
id: 'UI_DEVTOOLS_UI_INSPECTOR_WORKSPACE_CONTAINER',
        path: 'devtools.inspector.workspace.container',
        lifecycle: 'active',
        description: 'Main workspace split container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    SIDEBAR: {
      CONTAINER: {
uuid: '4b3bce01-fa7e-5a72-a504-57931cec20bc',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_CONTAINER',
        path: 'devtools.inspector.sidebar.container',
        lifecycle: 'active',
        description: 'Inspector sidebar with filters and element list',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SEARCH_LABEL: {
uuid: '3dff0d36-12e1-56bb-9e99-0a8cc70f9539',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SEARCH_LABEL',
        path: 'devtools.inspector.search.label',
        lifecycle: 'active',
        description: 'Search input label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SEARCH_INPUT: {
uuid: 'fdc8e69c-9696-5951-aff9-40ba7515f067',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SEARCH_INPUT',
        path: 'devtools.inspector.search.input',
        lifecycle: 'active',
        description: 'Search by uuid/id/path/feature',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_FEATURE_LABEL: {
uuid: '0d351ad1-851d-555c-bfad-e09f1ae895f2',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_FEATURE_LABEL',
        path: 'devtools.inspector.feature.label',
        lifecycle: 'active',
        description: 'Feature filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_FEATURE_SELECT: {
uuid: 'de50da61-b4ad-5dae-ad6c-c0a76b41034c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_FEATURE_SELECT',
        path: 'devtools.inspector.feature.select',
        lifecycle: 'active',
        description: 'Feature filter dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_FEATURE_OPTION: {
uuid: 'c0dd8da8-4d01-53db-93d6-df32e410713d',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_FEATURE_OPTION',
        path: 'devtools.inspector.feature.option',
        lifecycle: 'active',
        description: 'Feature filter option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      FILTER_TAG_LABEL: {
uuid: 'a471ed7f-35f8-54d2-83ce-cd413aabb0d4',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_TAG_LABEL',
        path: 'devtools.inspector.tag.label',
        lifecycle: 'active',
        description: 'Tag type filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_TAG_SELECT: {
uuid: '8f953f47-6900-52ec-bf6b-03f108791146',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_TAG_SELECT',
        path: 'devtools.inspector.tag.select',
        lifecycle: 'active',
        description: 'Tag type filter dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_TAG_OPTION: {
uuid: 'a59e94d2-61ce-575d-8960-82b876baf223',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_TAG_OPTION',
        path: 'devtools.inspector.tag.option',
        lifecycle: 'active',
        description: 'Tag type filter option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      FILTER_LIFECYCLE_LABEL: {
uuid: '739d400b-7691-5b5e-8437-fa75d43af060',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_LIFECYCLE_LABEL',
        path: 'devtools.inspector.lifecycle.label',
        lifecycle: 'active',
        description: 'Lifecycle filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_LIFECYCLE_SELECT: {
uuid: '32cc8633-6ca6-5ee8-b4c7-c625149e06c2',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_LIFECYCLE_SELECT',
        path: 'devtools.inspector.lifecycle.select',
        lifecycle: 'active',
        description: 'Lifecycle filter dropdown',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_LIFECYCLE_OPTION: {
uuid: 'c8b7c49e-55f2-5c19-9adc-e0dc80d3932f',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_LIFECYCLE_OPTION',
        path: 'devtools.inspector.lifecycle.option',
        lifecycle: 'active',
        description: 'Lifecycle filter option',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      FILTER_MISSING_LABEL: {
uuid: 'bb3996fb-b179-55a6-b1a2-e7490091f33c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_MISSING_LABEL',
        path: 'devtools.inspector.missing.label',
        lifecycle: 'active',
        description: 'Missing source filter label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FILTER_MISSING_CHECKBOX: {
uuid: '2bee80a2-f013-5c89-8661-8f041e82ab43',
id: 'UI_DEVTOOLS_UI_INSPECTOR_FILTER_MISSING_CHECKBOX',
        path: 'devtools.inspector.missing.checkbox',
        lifecycle: 'active',
        description: 'Missing source filter checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIST: {
uuid: '543a885e-b15a-5fc3-9a75-83fc77f81579',
id: 'UI_DEVTOOLS_UI_INSPECTOR_ELEMENT_LIST',
        path: 'devtools.inspector.list.container',
        lifecycle: 'active',
        description: 'Scanned element list container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIST_ITEM: {
uuid: 'a54f38d4-b4dc-508b-86f5-8af2c0264309',
id: 'UI_DEVTOOLS_UI_INSPECTOR_ELEMENT_LIST_ITEM',
        path: 'devtools.inspector.list.item',
        lifecycle: 'active',
        description: 'Scanned element list item button',
        category: 'navigation',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      COUNT: {
uuid: '1a72d6e9-2c94-5a6a-9951-cb6bd85f3b7c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_ELEMENT_COUNT',
        path: 'devtools.inspector.list.count',
        lifecycle: 'active',
        description: 'Filtered element count label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DISPLAY_LABEL: {
uuid: 'a91dd08d-358e-5dce-9001-06bf6cbabfa0',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DISPLAY_LABEL',
        path: 'devtools.inspector.sidebar.display',
        lifecycle: 'active',
        description: 'Collapsible display section label in sidebar',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DATABASE_SECTION_LABEL: {
uuid: '433ba2ee-c5c8-5a4f-9506-e1f04ff70309',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DATABASE_LABEL',
        path: 'devtools.inspector.sidebar.database',
        lifecycle: 'active',
        description: 'Collapsible database section label in sidebar',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTES_SECTION_LABEL: {
uuid: '566b2096-587b-5217-87aa-43cce9219765',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_ATTRIBUTES_LABEL',
        path: 'devtools.inspector.sidebar.attributes',
        lifecycle: 'active',
        description: 'Collapsible attributes section label in sidebar',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_ATTRIBUTES_LABEL: {
uuid: 'aa932a35-505c-5166-b551-fed7efbc6980',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DBATTRS_LABEL',
        path: 'devtools.inspector.sidebar.dbattrs',
        lifecycle: 'active',
        description: 'Collapsible database and attributes section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_MANAGEMENT_LABEL: {
uuid: 'fbc894c8-fd69-5d3d-a207-9a726f8d14b7',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_DBMGMT_LABEL',
        path: 'devtools.inspector.sidebar.dbmgmt',
        lifecycle: 'active',
        description: 'Collapsible database management section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCHEMA_EDITOR_LABEL: {
uuid: '92e74e9c-dcb0-5aad-b89d-36a645ea7617',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SIDEBAR_SCHEMA_LABEL',
        path: 'devtools.inspector.sidebar.schema',
        lifecycle: 'active',
        description: 'Collapsible schema editor section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    DETAILS: {
      CONTAINER: {
uuid: '16141077-f469-5674-83c9-4c91f9d24aee',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_CONTAINER',
        path: 'devtools.inspector.detail.container',
        lifecycle: 'active',
        description: 'Selected element details panel',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TITLE: {
uuid: 'dd0bb866-a1fb-537d-a1d9-2bb462698ff3',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_TITLE',
        path: 'devtools.inspector.detail.title',
        lifecycle: 'active',
        description: 'Details panel title',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      UUID_LABEL: {
uuid: '52ab65d2-15ad-5a83-930b-805c6f911f85',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_UUID_LABEL',
        path: 'devtools.inspector.uuid.label',
        lifecycle: 'active',
        description: 'UUID field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      UUID_VALUE: {
uuid: 'a2dbed0d-c3e8-5128-af57-61b7ddde6f02',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_UUID_VALUE',
        path: 'devtools.inspector.uuid.value',
        lifecycle: 'active',
        description: 'UUID field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STABLE_ID_LABEL: {
uuid: '21192078-251a-574f-ac19-ac5280bfb2c9',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_STABLE_ID_LABEL',
        path: 'devtools.inspector.stableid.label',
        lifecycle: 'active',
        description: 'Stable id field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STABLE_ID_VALUE: {
uuid: 'e0e7b88b-e9b7-56ac-bc4a-338d8a0037ee',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_STABLE_ID_VALUE',
        path: 'devtools.inspector.stableid.value',
        lifecycle: 'active',
        description: 'Stable id field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      PATH_LABEL: {
uuid: '374af8c6-3695-5db7-a475-0550c85490a9',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_PATH_LABEL',
        path: 'devtools.inspector.path.label',
        lifecycle: 'active',
        description: 'Identity path field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      PATH_VALUE: {
uuid: '7e072109-c59e-51c4-97b2-431326926fce',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_PATH_VALUE',
        path: 'devtools.inspector.path.value',
        lifecycle: 'active',
        description: 'Identity path field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FEATURE_LABEL: {
uuid: '0b162f7b-ef64-5798-84ff-4369de4c4576',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_FEATURE_LABEL',
        path: 'devtools.inspector.meta.feature-label',
        lifecycle: 'active',
        description: 'Feature field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FEATURE_VALUE: {
uuid: '2f31efd0-c415-53ab-8f7d-c68eb1661f79',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_FEATURE_VALUE',
        path: 'devtools.inspector.meta.feature-value',
        lifecycle: 'active',
        description: 'Feature field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIFECYCLE_LABEL: {
uuid: '9a096f91-9f4d-5f5a-8fa1-fae37d2cb8c4',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_LIFECYCLE_LABEL',
        path: 'devtools.inspector.meta.lifecycle-label',
        lifecycle: 'active',
        description: 'Lifecycle field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      LIFECYCLE_VALUE: {
uuid: '43e9f826-c552-57c5-92bf-df08056c9d4f',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_LIFECYCLE_VALUE',
        path: 'devtools.inspector.meta.lifecycle-value',
        lifecycle: 'active',
        description: 'Lifecycle field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TAG_LABEL: {
uuid: 'a1a82465-df44-5e36-8d62-de57ee80ef00',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_TAG_LABEL',
        path: 'devtools.inspector.meta.tag-label',
        lifecycle: 'active',
        description: 'Tag field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TAG_VALUE: {
uuid: '8ff63d62-9911-5339-864c-d3644748b483',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_TAG_VALUE',
        path: 'devtools.inspector.meta.tag-value',
        lifecycle: 'active',
        description: 'Tag field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_FILE_LABEL: {
uuid: '59ef6b7d-22e7-500e-a0cb-60b362f36b64',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_FILE_LABEL',
        path: 'devtools.inspector.source.file-label',
        lifecycle: 'active',
        description: 'Source file field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_FILE_VALUE: {
uuid: '570c95ca-1572-54a1-a44c-f3985512fdef',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_FILE_VALUE',
        path: 'devtools.inspector.source.file-value',
        lifecycle: 'active',
        description: 'Source file field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_COMPONENT_LABEL: {
uuid: '4bc7773c-104d-5a29-bfff-c37e23753673',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_COMPONENT_LABEL',
        path: 'devtools.inspector.source.component-label',
        lifecycle: 'active',
        description: 'Source component field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_COMPONENT_VALUE: {
uuid: '704e8897-6e8b-594e-8900-7211d3376d58',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_COMPONENT_VALUE',
        path: 'devtools.inspector.source.component-value',
        lifecycle: 'active',
        description: 'Source component field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_LINE_LABEL: {
uuid: 'ba3fa0d9-64c2-5c82-9b9d-bb17b8874c00',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_LINE_LABEL',
        path: 'devtools.inspector.source.line-label',
        lifecycle: 'active',
        description: 'Source line field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOURCE_LINE_VALUE: {
uuid: '1a035d3e-322f-587d-9487-b024114f1183',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_SOURCE_LINE_VALUE',
        path: 'devtools.inspector.source.line-value',
        lifecycle: 'active',
        description: 'Source line field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INSTANCE_LABEL: {
uuid: 'f3f6daca-de44-59cb-9d03-1c7cb0ede275',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_INSTANCE_LABEL',
        path: 'devtools.inspector.instance.label',
        lifecycle: 'active',
        description: 'Instance id field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INSTANCE_VALUE: {
uuid: 'efdfb035-2262-51e0-9ad6-e2d7c1190872',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_INSTANCE_VALUE',
        path: 'devtools.inspector.instance.value',
        lifecycle: 'active',
        description: 'Instance id field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      IDENTITY_KEY_LABEL: {
uuid: '4b61334b-1bfd-5a5e-bebb-d3d1002f2e5c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_IDENTITY_KEY_LABEL',
        path: 'devtools.inspector.identity.label',
        lifecycle: 'active',
        description: 'Identity key field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      IDENTITY_KEY_VALUE: {
uuid: '8f7efb60-5de3-5471-a623-86661c7b0fb7',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_IDENTITY_KEY_VALUE',
        path: 'devtools.inspector.identity.value',
        lifecycle: 'active',
        description: 'Identity key field value',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COPY_UUID_BUTTON: {
uuid: '69cfd201-7758-5794-a86c-3c373477e952',
id: 'UI_DEVTOOLS_UI_INSPECTOR_COPY_UUID_BUTTON',
        path: 'devtools.inspector.copy.uuid-button',
        lifecycle: 'active',
        description: 'Copy UUID button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COPY_PATH_BUTTON: {
uuid: '3e921ead-5022-55d0-bce9-4223e79990ce',
id: 'UI_DEVTOOLS_UI_INSPECTOR_COPY_PATH_BUTTON',
        path: 'devtools.inspector.copy.path-button',
        lifecycle: 'active',
        description: 'Copy identity path button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COPY_SOURCE_BUTTON: {
uuid: '1c30110b-044a-56f2-943b-48c1b90e5eb0',
id: 'UI_DEVTOOLS_UI_INSPECTOR_COPY_SOURCE_BUTTON',
        path: 'devtools.inspector.copy.source-button',
        lifecycle: 'active',
        description: 'Copy source location button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      HIGHLIGHT_BUTTON: {
uuid: '1934e6fe-b836-55a7-8322-54f8c5fda161',
id: 'UI_DEVTOOLS_UI_INSPECTOR_HIGHLIGHT_BUTTON',
        path: 'devtools.inspector.preview.highlight',
        lifecycle: 'active',
        description: 'Highlight element in preview button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCROLL_BUTTON: {
uuid: '2a774ed3-01f7-56c4-86f6-802929e7f26a',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SCROLL_BUTTON',
        path: 'devtools.inspector.preview.scroll',
        lifecycle: 'active',
        description: 'Scroll to element in preview button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      EMPTY_MESSAGE: {
uuid: '6b5f8681-dcae-5d1e-b309-b6affa839a3c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DETAILS_EMPTY_MESSAGE',
        path: 'devtools.inspector.detail.empty',
        lifecycle: 'active',
        description: 'Empty selection message',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    LAYOUT: {
      RESIZER: {
uuid: 'fa6cbe98-3435-52a9-ac9d-f1e2fc1df39b',
id: 'UI_DEVTOOLS_UI_INSPECTOR_LAYOUT_RESIZER',
        path: 'devtools.inspector.layout.resizer',
        lifecycle: 'active',
        description: 'Sidebar width resize handle',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    PICK: {
      MODE_TOGGLE: {
uuid: 'b36800c5-ed06-5b40-a92f-f957187d9072',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PICK_MODE_TOGGLE',
        path: 'devtools.inspector.pick.toggle',
        lifecycle: 'active',
        description: 'Toggle mouse pick mode in preview iframe',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    SELECTED: {
      CONTAINER: {
uuid: '6f049796-7d80-568f-8888-aec02c187f89',
id: 'UI_DEVTOOLS_UI_INSPECTOR_SELECTED_CONTAINER',
        path: 'devtools.inspector.selected.container',
        lifecycle: 'active',
        description: 'Selected element summary container in sidebar',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    DATA: {
      CONTAINER: {
uuid: '85023937-ce08-596e-bf4f-faf9364dbc00',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_CONTAINER',
        path: 'devtools.inspector.data.container',
        lifecycle: 'active',
        description: 'Inspector data entry container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      DATABASE_LABEL: {
uuid: 'a37b9dac-7be8-5903-b149-72e68b20c3e5',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_DATABASE_LABEL',
        path: 'devtools.inspector.data.database',
        lifecycle: 'active',
        description: 'Database section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DATABASE_TOGGLE: {
uuid: '3e50ac0e-af94-51ef-900d-6f24c346e63d',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_DATABASE_TOGGLE',
        path: 'devtools.inspector.db.toggle',
        lifecycle: 'active',
        description: 'Database enabled toggle',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF1_LABEL: {
uuid: 'ea93ad8b-59aa-5738-b3af-532dae9fc042',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF1_LABEL',
        path: 'devtools.inspector.inf1.label',
        lifecycle: 'active',
        description: 'Database inf1 field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF1_INPUT: {
uuid: 'f2fff441-c36b-5266-9e78-a78b36a6fe28',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF1_INPUT',
        path: 'devtools.inspector.inf1.input',
        lifecycle: 'active',
        description: 'Database inf1 text input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF2_LABEL: {
uuid: 'c1b0bbba-13b2-5e85-bda3-2ca0f89695b3',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF2_LABEL',
        path: 'devtools.inspector.inf2.label',
        lifecycle: 'active',
        description: 'Database inf2 field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF2_INPUT: {
uuid: '07db2c00-042c-5b03-8f13-b2cee7235889',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF2_INPUT',
        path: 'devtools.inspector.inf2.input',
        lifecycle: 'active',
        description: 'Database inf2 text input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF3_LABEL: {
uuid: 'e96881cd-03fc-5b92-aab5-36eb14d4d168',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF3_LABEL',
        path: 'devtools.inspector.inf3.label',
        lifecycle: 'active',
        description: 'Database inf3 field label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INF3_INPUT: {
uuid: '813f7a2b-f08f-5c18-9e3e-6021474d6876',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_INF3_INPUT',
        path: 'devtools.inspector.inf3.input',
        lifecycle: 'active',
        description: 'Database inf3 text input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTES_LABEL: {
uuid: 'bd1ed4c8-dc5e-528b-8ce2-d71e6076b8b1',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTES_LABEL',
        path: 'devtools.inspector.data.attributes',
        lifecycle: 'active',
        description: 'Attributes section label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTES_TOGGLE: {
uuid: '5ab365aa-f522-5d27-9570-6d2c316cf719',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTES_TOGGLE',
        path: 'devtools.inspector.attr.toggle',
        lifecycle: 'active',
        description: 'Attributes enabled toggle',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE1_CHECKBOX: {
uuid: 'd9b12725-ff90-58a8-8219-b69b3c9cfda6',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE1_CHECKBOX',
        path: 'devtools.inspector.data.attribute1',
        lifecycle: 'active',
        description: 'Attribute 1 checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE1_LABEL: {
uuid: '0e6d15c2-b07a-562d-8e92-2cc4777028bf',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE1_LABEL',
        path: 'devtools.inspector.attr1.label',
        lifecycle: 'active',
        description: 'Attribute 1 checkbox label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE2_CHECKBOX: {
uuid: '3cd3d8ca-8fec-5977-a81d-700c8baa8921',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE2_CHECKBOX',
        path: 'devtools.inspector.data.attribute2',
        lifecycle: 'active',
        description: 'Attribute 2 checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE2_LABEL: {
uuid: '5863eb33-ba6d-5fa0-a6f7-fc01bf71d9ce',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE2_LABEL',
        path: 'devtools.inspector.attr2.label',
        lifecycle: 'active',
        description: 'Attribute 2 checkbox label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE3_CHECKBOX: {
uuid: '4d7f2acf-3fe2-5692-9f73-929123a62edc',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE3_CHECKBOX',
        path: 'devtools.inspector.data.attribute3',
        lifecycle: 'active',
        description: 'Attribute 3 checkbox',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ATTRIBUTE3_LABEL: {
uuid: '74a226e8-a780-59eb-8322-4b3e71cca3d1',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_ATTRIBUTE3_LABEL',
        path: 'devtools.inspector.attr3.label',
        lifecycle: 'active',
        description: 'Attribute 3 checkbox label',
        category: 'display',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SAVE_BUTTON: {
uuid: '1c559c16-cb89-5abb-8b33-456ccb9d9db9',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DATA_SAVE_BUTTON',
        path: 'devtools.inspector.data.save',
        lifecycle: 'active',
        description: 'Save inspector data to JSON file',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    DBMGMT: {
      CONTAINER: {
uuid: 'ecc19778-822b-5165-9bd9-7dd20e29e3df',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBMGMT_CONTAINER',
        path: 'devtools.inspector.dbmgmt.container',
        lifecycle: 'active',
        description: 'Database management descriptions panel',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      DESC_TEXTAREA: {
uuid: 'b0eaa6f3-05cb-5762-9d7e-22c9a42e7dd0',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBMGMT_DESC_TEXTAREA',
        path: 'devtools.inspector.dbmgmt.desc',
        lifecycle: 'active',
        description: 'Description textarea in database management',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      SAVE_DESC_BUTTON: {
uuid: '9760b450-50aa-5fb5-9628-9e82c360c4cf',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBMGMT_SAVE_DESC',
        path: 'devtools.inspector.dbmgmt.save-desc',
        lifecycle: 'active',
        description: 'Save description button in database management',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
    },
    DBREF: {
      CONTAINER: {
uuid: 'cca11f36-c396-5841-951f-140859b94be3',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_CONTAINER',
        path: 'devtools.inspector.dbref.container',
        lifecycle: 'active',
        description: 'Database reference schema editor container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
        repeatable: true,
} as const,
      SAVE_BUTTON: {
uuid: 'fa606793-fe53-5204-811f-5af1e74b082a',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_SAVE_BUTTON',
        path: 'devtools.inspector.dbref.save',
        lifecycle: 'active',
        description: 'Save database_ref.json schema file',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_SELECT: {
uuid: 'f4171d1e-4116-5f15-a414-a51c9df93653',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DB_SELECT',
        path: 'devtools.inspector.refdb.select',
        lifecycle: 'active',
        description: 'Database picker in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TABLE_SELECT: {
uuid: '65313abe-6c0f-5dcb-9efc-0c585a4d7645',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_TABLE_SELECT',
        path: 'devtools.inspector.reftb.select',
        lifecycle: 'active',
        description: 'Table picker in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COLUMN_SELECT: {
uuid: '6da06882-0110-51f5-b515-39d01b8b9323',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_COLUMN_SELECT',
        path: 'devtools.inspector.refcol.select',
        lifecycle: 'active',
        description: 'Column picker in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_AR_INPUT: {
uuid: 'c3a49122-f077-5795-9550-270c6094fbff',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DB_AR_INPUT',
        path: 'devtools.inspector.dbar.input',
        lifecycle: 'active',
        description: 'Arabic database name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DB_EN_INPUT: {
uuid: 'aacd7682-8d8b-5955-bcb6-2d3c7712b9c7',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DB_EN_INPUT',
        path: 'devtools.inspector.dben.input',
        lifecycle: 'active',
        description: 'English database name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TABLE_AR_INPUT: {
uuid: 'd5f833c2-b384-5af7-b698-87d815e7efe5',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_TABLE_AR_INPUT',
        path: 'devtools.inspector.tbar.input',
        lifecycle: 'active',
        description: 'Arabic table name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      TABLE_EN_INPUT: {
uuid: '083ab8a2-1747-5f0f-b856-eca829bb3c45',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_TABLE_EN_INPUT',
        path: 'devtools.inspector.tben.input',
        lifecycle: 'active',
        description: 'English table name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COLUMN_AR_INPUT: {
uuid: '6e1896a6-50c5-55f5-9771-4a7067e7462f',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_COLUMN_AR_INPUT',
        path: 'devtools.inspector.colar.input',
        lifecycle: 'active',
        description: 'Arabic column name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COLUMN_EN_INPUT: {
uuid: '06152476-edd7-54b5-a9af-1290e4e2d1d7',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_COLUMN_EN_INPUT',
        path: 'devtools.inspector.colen.input',
        lifecycle: 'active',
        description: 'English column name input in schema editor',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ADD_DB: {
uuid: '21d4aa85-efe1-5d20-ab9e-7a67a3a6ba42',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_ADD_DB',
        path: 'devtools.inspector.adddb.action',
        lifecycle: 'active',
        description: 'Add database entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ADD_TABLE: {
uuid: 'f1ab9a85-bad6-5446-8645-92bbb50b211c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_ADD_TABLE',
        path: 'devtools.inspector.addtb.action',
        lifecycle: 'active',
        description: 'Add table entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ADD_COLUMN: {
uuid: 'f5610449-4ce0-5660-ad52-30ab95a5d6e2',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_ADD_COLUMN',
        path: 'devtools.inspector.addcol.action',
        lifecycle: 'active',
        description: 'Add column entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DELETE_DB: {
uuid: '167edbf3-f4a5-5aec-9116-759929414fb2',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DELETE_DB',
        path: 'devtools.inspector.deldb.action',
        lifecycle: 'active',
        description: 'Delete database entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DELETE_TABLE: {
uuid: '81e880af-e500-50ba-bef6-37b1a8979c4c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DELETE_TABLE',
        path: 'devtools.inspector.deltb.action',
        lifecycle: 'active',
        description: 'Delete table entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      DELETE_COLUMN: {
uuid: 'c6d766f7-d825-5afc-ae69-2d2d46066a32',
id: 'UI_DEVTOOLS_UI_INSPECTOR_DBREF_DELETE_COLUMN',
        path: 'devtools.inspector.delcol.action',
        lifecycle: 'active',
        description: 'Delete column entry in schema editor',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    PREVIEW: {
      CONTAINER: {
uuid: 'f9d852b9-1081-5492-9786-764321678b3c',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_CONTAINER',
        path: 'devtools.inspector.preview.container',
        lifecycle: 'active',
        description: 'Preview iframe container',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      IFRAME: {
uuid: 'e5b82bea-ad7c-515b-865d-5aa49d6817ed',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_IFRAME',
        path: 'devtools.inspector.preview.iframe',
        lifecycle: 'active',
        description: 'Target page preview iframe',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      CONTROLS: {
uuid: '973c4df4-f16f-5301-abca-5a46d6e178c3',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_CONTROLS',
        path: 'devtools.inspector.preview.controls',
        lifecycle: 'active',
        description: 'Preview size and zoom controls bar',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SCROLL: {
uuid: 'd940dd33-0c12-5bf6-ab91-d70586279508',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_SCROLL',
        path: 'devtools.inspector.preview.viewport',
        lifecycle: 'active',
        description: 'Scrollable preview viewport',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FRAME: {
uuid: '83597a5b-ef3d-594c-ae9f-46c9b645115a',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_FRAME',
        path: 'devtools.inspector.preview.frame',
        lifecycle: 'active',
        description: 'Resizable preview frame wrapper',
        category: 'container',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ZOOM_OUT: {
uuid: 'cd02455e-19ec-5bcf-a4b0-bfc425c158e5',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_ZOOM_OUT',
        path: 'devtools.inspector.preview.zoom-out',
        lifecycle: 'active',
        description: 'Decrease preview zoom button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ZOOM_IN: {
uuid: 'bd10ea55-8ca7-5bce-8456-2e9f8534ba00',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_ZOOM_IN',
        path: 'devtools.inspector.preview.zoom-in',
        lifecycle: 'active',
        description: 'Increase preview zoom button',
        category: 'action',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ZOOM_VALUE: {
uuid: '50085dd3-de1b-5cfa-9d9b-d2d101b0efb0',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_ZOOM_VALUE',
        path: 'devtools.inspector.preview.zoom',
        lifecycle: 'active',
        description: 'Preview zoom percentage input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      WIDTH_INPUT: {
uuid: '725d0919-4c07-5366-9c84-e07b8a26c4d8',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_WIDTH_INPUT',
        path: 'devtools.inspector.preview.width',
        lifecycle: 'active',
        description: 'Preview frame width input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      HEIGHT_INPUT: {
uuid: 'e565b1e6-bc25-509b-b132-2694aec1e371',
id: 'UI_DEVTOOLS_UI_INSPECTOR_PREVIEW_HEIGHT_INPUT',
        path: 'devtools.inspector.preview.height',
        lifecycle: 'active',
        description: 'Preview frame height input',
        category: 'input',
        feature: 'devtools',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
  },
} as const;
