/** Auto-split from registry.ts */
export const HOME = {
  LANGUAGE_SWITCHER: {
    ENGLISH_BUTTON: {
      id: 'UI_HOME_LANG_ENGLISH',
      path: 'home.language-switcher.buttons.english-button',
      description: 'English language switcher button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    ARABIC_BUTTON: {
      id: 'UI_HOME_LANG_ARABIC',
      path: 'home.language-switcher.buttons.arabic-button',
      description: 'Arabic language switcher button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
  },
  PROMO_BANNER: {
    CONTAINER: {
      id: 'UI_HOME_PROMO_BANNER_CONTAINER',
      path: 'home.promo-banner.layout.container',
      description: 'Promo banner section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CONTENT_WRAPPER: {
      id: 'UI_HOME_PROMO_BANNER_CONTENT_WRAPPER',
      path: 'home.promo-banner.layout.content-wrapper',
      description: 'Promo banner content wrapper',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ACTION_BUTTON: {
      id: 'UI_HOME_PROMO_BANNER_ACTION',
      path: 'home.promo-banner.actions.banner-button',
      description: 'Promo banner call-to-action button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    TITLE: {
      id: 'UI_HOME_PROMO_BANNER_TITLE',
      path: 'home.promo-banner.display.title',
      description: 'Promo banner main heading',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    DESCRIPTION: {
      id: 'UI_HOME_PROMO_BANNER_DESCRIPTION',
      path: 'home.promo-banner.display.description',
      description: 'Promo banner description text',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    LOGO: {
      id: 'UI_HOME_PROMO_BANNER_LOGO',
      path: 'home.promo-banner.display.logo',
      description: 'Promo banner logo image',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    DECORATIVE_BACKGROUND: {
      id: 'UI_HOME_PROMO_BANNER_DECORATIVE_BACKGROUND',
      path: 'home.promo-banner.decorative.background',
      description: 'Promo banner decorative background',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  CURATED_OFFERS: {
    CONTAINER: {
      id: 'UI_HOME_CURATED_OFFERS_CONTAINER',
      path: 'home.curated-offers.layout.container',
      description: 'Curated offers section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    HEADER: {
      id: 'UI_HOME_CURATED_OFFERS_HEADER',
      path: 'home.curated-offers.layout.header',
      description: 'Curated offers section header',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    PRODUCT_GRID: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_GRID',
      path: 'home.curated-offers.layout.product-grid',
      description: 'Curated offers product grid',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    PRODUCT_CARD: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_CARD',
      path: 'home.curated-offers.layout.product-card',
      description: 'Curated offers product card',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    PRODUCT_IMAGE_CONTAINER: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE_CONTAINER',
      path: 'home.curated-offers.layout.product-image-container',
      description: 'Curated offers product image container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    PRODUCT_INFO: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_INFO',
      path: 'home.curated-offers.layout.product-info',
      description: 'Curated offers product info section',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    PRICE_ROW: {
      id: 'UI_HOME_CURATED_OFFERS_PRICE_ROW',
      path: 'home.curated-offers.layout.price-row',
      description: 'Curated offers price row',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SHOW_MORE_CONTAINER: {
      id: 'UI_HOME_CURATED_OFFERS_SHOW_MORE_CONTAINER',
      path: 'home.curated-offers.layout.show-more-container',
      description: 'Curated offers show more button container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SHOW_MORE: {
      id: 'UI_HOME_CURATED_OFFERS_MORE',
      path: 'home.curated-offers.actions.show-more-button',
      description: 'Show more curated offers button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    ADD_TO_CART: {
      id: 'UI_HOME_CURATED_OFFERS_ADD_TO_CART',
      path: 'home.curated-offers.actions.add-to-cart-button',
      description: 'Add item to cart button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    ADD_TO_FAVORITES: {
      id: 'UI_HOME_CURATED_OFFERS_FAVORITE',
      path: 'home.curated-offers.actions.add-to-favorites-button',
      description: 'Add item to favorites button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    PRODUCT_IMAGE: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE',
      path: 'home.curated-offers.display.product-image',
      description: 'Product image in curated offers',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    CATEGORY_LABEL: {
      id: 'UI_HOME_CURATED_OFFERS_CATEGORY_LABEL',
      path: 'home.curated-offers.display.category-label',
      description: 'Product category label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    PRODUCT_TITLE: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_TITLE',
      path: 'home.curated-offers.display.product-title',
      description: 'Product title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    PRICE_LABEL: {
      id: 'UI_HOME_CURATED_OFFERS_PRICE_LABEL',
      path: 'home.curated-offers.display.price-label',
      description: 'Product price label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    SECTION_TITLE: {
      id: 'UI_HOME_CURATED_OFFERS_SECTION_TITLE',
      path: 'home.curated-offers.display.section-title',
      description: 'Curated offers section title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    PROMO_TAG: {
      id: 'UI_HOME_CURATED_OFFERS_PROMO_TAG',
      path: 'home.curated-offers.display.promo-tag',
      description: 'Curated offers promo tag',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
  },
  HERO_SLIDER: {
    CONTAINER: {
      id: 'UI_HOME_HERO_SLIDER_CONTAINER',
      path: 'home.hero-slider.layout.container',
      description: 'Hero slider section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SLIDER_TRACK: {
      id: 'UI_HOME_HERO_SLIDER_SLIDER_TRACK',
      path: 'home.hero-slider.layout.slider-track',
      description: 'Hero slider track container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SLIDE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE',
      path: 'home.hero-slider.layout.slide',
      description: 'Hero slider slide container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SLIDE_CONTENT: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_CONTENT',
      path: 'home.hero-slider.layout.slide-content',
      description: 'Hero slider slide content overlay',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    INDICATORS: {
      id: 'UI_HOME_HERO_SLIDER_INDICATORS',
      path: 'home.hero-slider.layout.indicators',
      description: 'Hero slider dot indicators',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SLIDE_IMAGE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_IMAGE',
      path: 'home.hero-slider.display.slide-image',
      description: 'Hero slider slide image',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    SLIDE_TITLE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_TITLE',
      path: 'home.hero-slider.display.slide-title',
      description: 'Hero slider slide title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    SLIDE_BADGE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_BADGE',
      path: 'home.hero-slider.display.slide-badge',
      description: 'Hero slider slide badge',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
  },
  CATEGORIES_GRID: {
    TOGGLE: {
      id: 'UI_HOME_CATEGORIES_GRID_TOGGLE',
      path: 'home.categories-grid.actions.toggle-button',
      description: 'Toggle categories grid layout button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    ITEM: {
      id: 'UI_HOME_CATEGORIES_GRID_ITEM',
      path: 'home.categories-grid.actions.category-button',
      description: 'Select category button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    CATEGORY_IMAGE: {
      id: 'UI_HOME_CATEGORIES_GRID_CATEGORY_IMAGE',
      path: 'home.categories-grid.display.category-image',
      description: 'Category image in grid',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    CATEGORY_NAME: {
      id: 'UI_HOME_CATEGORIES_GRID_CATEGORY_NAME',
      path: 'home.categories-grid.display.category-name',
      description: 'Category name label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    SECTION_TITLE: {
      id: 'UI_HOME_CATEGORIES_GRID_SECTION_TITLE',
      path: 'home.categories-grid.display.section-title',
      description: 'Categories section title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
  },
} as const;

// ============================================================================
// SPLASH PAGE IDENTIFIERS
// ============================================================================