/** Auto-split from registry.ts */
export const HOME = {
  LANGUAGE_SWITCHER: {
    ENGLISH_BUTTON: {
uuid: '38a914ca-716f-55bd-b177-54f00e0b2f1b',
      id: 'UI_HOME_LANG_ENGLISH',
      path: 'home.language-switcher.buttons.english-button',
      lifecycle: 'active',
      description: 'English language switcher button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    ARABIC_BUTTON: {
uuid: '8d25ea72-53a4-59a7-870e-8c741ca321e9',
      id: 'UI_HOME_LANG_ARABIC',
      path: 'home.language-switcher.buttons.arabic-button',
      lifecycle: 'active',
      description: 'Arabic language switcher button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },
  PROMO_BANNER: {
    CONTAINER: {
      id: 'UI_HOME_PROMO_BANNER_CONTAINER',
      path: 'home.promo-banner.layout.container',
      lifecycle: 'active',
      description: 'Promo banner section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    CONTENT_WRAPPER: {
      id: 'UI_HOME_PROMO_BANNER_CONTENT_WRAPPER',
      path: 'home.promo-banner.layout.content-wrapper',
      lifecycle: 'active',
      description: 'Promo banner content wrapper',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    ACTION_BUTTON: {
uuid: '0540ae86-babc-564b-a885-2620eb5d04ed',
      id: 'UI_HOME_PROMO_BANNER_ACTION',
      path: 'home.promo-banner.actions.banner-button',
      lifecycle: 'active',
      description: 'Promo banner call-to-action button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    TITLE: {
uuid: 'c537d012-980e-5205-8dc7-dfd4b4118a3f',
      id: 'UI_HOME_PROMO_BANNER_TITLE',
      path: 'home.promo-banner.display.title',
      lifecycle: 'active',
      description: 'Promo banner main heading',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    DESCRIPTION: {
uuid: '9dd0782e-d811-5ddd-885c-9364f6283a1b',
      id: 'UI_HOME_PROMO_BANNER_DESCRIPTION',
      path: 'home.promo-banner.display.description',
      lifecycle: 'active',
      description: 'Promo banner description text',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    LOGO: {
uuid: 'afb9f7fb-5e44-520e-8985-bc551f347208',
      id: 'UI_HOME_PROMO_BANNER_LOGO',
      path: 'home.promo-banner.display.logo',
      lifecycle: 'active',
      description: 'Promo banner logo image',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    DECORATIVE_BACKGROUND: {
      id: 'UI_HOME_PROMO_BANNER_DECORATIVE_BACKGROUND',
      path: 'home.promo-banner.decorative.background',
      lifecycle: 'active',
      description: 'Promo banner decorative background',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
  },
  CURATED_OFFERS: {
    CONTAINER: {
      id: 'UI_HOME_CURATED_OFFERS_CONTAINER',
      path: 'home.curated-offers.layout.container',
      lifecycle: 'active',
      description: 'Curated offers section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    HEADER: {
      id: 'UI_HOME_CURATED_OFFERS_HEADER',
      path: 'home.curated-offers.layout.header',
      lifecycle: 'active',
      description: 'Curated offers section header',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_GRID: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_GRID',
      path: 'home.curated-offers.layout.product-grid',
      lifecycle: 'active',
      description: 'Curated offers product grid',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_CARD: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_CARD',
      path: 'home.curated-offers.layout.product-card',
      lifecycle: 'active',
      description: 'Curated offers product card',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_IMAGE_CONTAINER: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE_CONTAINER',
      path: 'home.curated-offers.layout.product-image-container',
      lifecycle: 'active',
      description: 'Curated offers product image container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_INFO: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_INFO',
      path: 'home.curated-offers.layout.product-info',
      lifecycle: 'active',
      description: 'Curated offers product info section',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRICE_ROW: {
      id: 'UI_HOME_CURATED_OFFERS_PRICE_ROW',
      path: 'home.curated-offers.layout.price-row',
      lifecycle: 'active',
      description: 'Curated offers price row',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SHOW_MORE_CONTAINER: {
      id: 'UI_HOME_CURATED_OFFERS_SHOW_MORE_CONTAINER',
      path: 'home.curated-offers.layout.show-more-container',
      lifecycle: 'active',
      description: 'Curated offers show more button container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SHOW_MORE: {
uuid: 'd1105943-783f-57d2-99bf-ff1984020cf8',
      id: 'UI_HOME_CURATED_OFFERS_MORE',
      path: 'home.curated-offers.actions.show-more-button',
      lifecycle: 'active',
      description: 'Show more curated offers button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    ADD_TO_CART: {
uuid: '1bbf218e-0417-5e51-9e53-8dcc82c2933f',
      id: 'UI_HOME_CURATED_OFFERS_ADD_TO_CART',
      path: 'home.curated-offers.actions.add-to-cart-button',
      lifecycle: 'active',
      description: 'Add item to cart button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    ADD_TO_FAVORITES: {
uuid: '0e3c1ff6-0a95-5e47-b502-fdf4b9740105',
      id: 'UI_HOME_CURATED_OFFERS_FAVORITE',
      path: 'home.curated-offers.actions.add-to-favorites-button',
      lifecycle: 'active',
      description: 'Add item to favorites button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PRODUCT_IMAGE: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE',
      path: 'home.curated-offers.display.product-image',
      lifecycle: 'active',
      description: 'Product image in curated offers',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    CATEGORY_LABEL: {
      id: 'UI_HOME_CURATED_OFFERS_CATEGORY_LABEL',
      path: 'home.curated-offers.display.category-label',
      lifecycle: 'active',
      description: 'Product category label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PRODUCT_TITLE: {
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_TITLE',
      path: 'home.curated-offers.display.product-title',
      lifecycle: 'active',
      description: 'Product title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PRICE_LABEL: {
      id: 'UI_HOME_CURATED_OFFERS_PRICE_LABEL',
      path: 'home.curated-offers.display.price-label',
      lifecycle: 'active',
      description: 'Product price label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SECTION_TITLE: {
uuid: '95c0c3f8-7d73-5d6f-8631-3a56c9d829ed',
      id: 'UI_HOME_CURATED_OFFERS_SECTION_TITLE',
      path: 'home.curated-offers.display.section-title',
      lifecycle: 'active',
      description: 'Curated offers section title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PROMO_TAG: {
uuid: '6c8e3d42-7222-5f9d-801c-3cd035255013',
      id: 'UI_HOME_CURATED_OFFERS_PROMO_TAG',
      path: 'home.curated-offers.display.promo-tag',
      lifecycle: 'active',
      description: 'Curated offers promo tag',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },
  HERO_SLIDER: {
    CONTAINER: {
      id: 'UI_HOME_HERO_SLIDER_CONTAINER',
      path: 'home.hero-slider.layout.container',
      lifecycle: 'active',
      description: 'Hero slider section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDER_TRACK: {
      id: 'UI_HOME_HERO_SLIDER_SLIDER_TRACK',
      path: 'home.hero-slider.layout.slider-track',
      lifecycle: 'active',
      description: 'Hero slider track container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE',
      path: 'home.hero-slider.layout.slide',
      lifecycle: 'active',
      description: 'Hero slider slide container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDE_CONTENT: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_CONTENT',
      path: 'home.hero-slider.layout.slide-content',
      lifecycle: 'active',
      description: 'Hero slider slide content overlay',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    INDICATORS: {
      id: 'UI_HOME_HERO_SLIDER_INDICATORS',
      path: 'home.hero-slider.layout.indicators',
      lifecycle: 'active',
      description: 'Hero slider dot indicators',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDE_IMAGE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_IMAGE',
      path: 'home.hero-slider.display.slide-image',
      lifecycle: 'active',
      description: 'Hero slider slide image',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SLIDE_TITLE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_TITLE',
      path: 'home.hero-slider.display.slide-title',
      lifecycle: 'active',
      description: 'Hero slider slide title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SLIDE_BADGE: {
      id: 'UI_HOME_HERO_SLIDER_SLIDE_BADGE',
      path: 'home.hero-slider.display.slide-badge',
      lifecycle: 'active',
      description: 'Hero slider slide badge',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },
  FEATURED_MARQUEE: {
SECTION: {
      id: 'UI_HOME_FEATURED_MARQUEE_SECTION',
      path: 'home.featured-marquee.layout.section',
      lifecycle: 'active',
      description: 'section',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
HEADER: {
      id: 'UI_HOME_FEATURED_MARQUEE_HEADER',
      path: 'home.featured-marquee.display.header',
      lifecycle: 'active',
      description: 'header',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  CATEGORIES_GRID: {
    SECTION: {
      id: 'UI_HOME_CATEGORIES_GRID_SECTION',
      path: 'home.categories-grid.layout.section',
      lifecycle: 'active',
      description: 'section',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,

    TOGGLE: {
uuid: '4d96c903-4026-5d64-b003-27114c48b5f2',
      id: 'UI_HOME_CATEGORIES_GRID_TOGGLE',
      path: 'home.categories-grid.actions.toggle-button',
      lifecycle: 'active',
      description: 'Toggle categories grid layout button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    TOGGLE_LABEL: {
      id: 'UI_HOME_CATEGORIES_GRID_TOGGLE_LABEL',
      path: 'home.categories-grid.display.toggle-label',
      lifecycle: 'active',
      description: 'Toggle categories grid button label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ITEM: {
      id: 'UI_HOME_CATEGORIES_GRID_ITEM',
      path: 'home.categories-grid.actions.category-button',
      lifecycle: 'active',
      description: 'Select category button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    CATEGORY_IMAGE: {
      id: 'UI_HOME_CATEGORIES_GRID_CATEGORY_IMAGE',
      path: 'home.categories-grid.display.category-image',
      lifecycle: 'active',
      description: 'Category image in grid',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    CATEGORY_NAME: {
      id: 'UI_HOME_CATEGORIES_GRID_CATEGORY_NAME',
      path: 'home.categories-grid.display.category-name',
      lifecycle: 'active',
      description: 'Category name label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SECTION_TITLE: {
uuid: 'b6226727-2816-5e66-9fe6-735128d31df8',
      id: 'UI_HOME_CATEGORIES_GRID_SECTION_TITLE',
      path: 'home.categories-grid.display.section-title',
      lifecycle: 'active',
      description: 'Categories section title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },

  SHELL: {
    HOME_L14: {
      id: 'UI_HOME_STRUCTURE_HOME_L14',
      path: 'home.dom.home.home-l14',
      lifecycle: 'active',
      description: 'Structural element at src/app/(app)/home/page.tsx:15',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CATEGORIES_GRID_SECTION_TITLE_WRAPPER_L29: {
      id: 'UI_HOME_STRUCTURE_CATEGORIES_GRID_SECTION_TITLE_WRAPPER_L29',
      path: 'home.dom.categories-grid.categories-grid-section-title-wrapper-l29',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/CategoriesGrid.tsx:29',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CATEGORIES_GRID_SECTION_TITLE_WRAPPER_L30: {
      id: 'UI_HOME_STRUCTURE_CATEGORIES_GRID_SECTION_TITLE_WRAPPER_L30',
      path: 'home.dom.categories-grid.categories-grid-section-title-wrapper-l30',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/CategoriesGrid.tsx:30',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NAMEKEY_WRAPPER_L44: {
      id: 'UI_HOME_STRUCTURE_NAMEKEY_WRAPPER_L44',
      path: 'home.dom.categories-grid.namekey-wrapper-l44',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/CategoriesGrid.tsx:44',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NAMEKEY_WRAPPER_L47: {
      id: 'UI_HOME_STRUCTURE_NAMEKEY_WRAPPER_L47',
      path: 'home.dom.categories-grid.namekey-wrapper-l47',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/CategoriesGrid.tsx:47',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CURATED_OFFERS_SECTION_TITLE_WRAPPER_L67: {
      id: 'UI_HOME_STRUCTURE_CURATED_OFFERS_SECTION_TITLE_WRAPPER_L67',
      path: 'home.dom.curated-offers.curated-offers-section-title-wrapper-l67',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/CuratedOffers.tsx:67',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_WRAPPER_L54: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_WRAPPER_L54',
      path: 'home.dom.featured-marquee.titlekey-wrapper-l54',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:54',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_WRAPPER_L55: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_WRAPPER_L55',
      path: 'home.dom.featured-marquee.titlekey-wrapper-l55',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:55',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_WRAPPER_L75: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_WRAPPER_L75',
      path: 'home.dom.featured-marquee.titlekey-wrapper-l75',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:75',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_WRAPPER_L79: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_WRAPPER_L79',
      path: 'home.dom.featured-marquee.titlekey-wrapper-l79',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:79',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_CONTAINER_L81: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_CONTAINER_L81',
      path: 'home.dom.featured-marquee.titlekey-container-l81',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:81',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_CONTAINER_L85: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_CONTAINER_L85',
      path: 'home.dom.featured-marquee.titlekey-container-l85',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:85',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_CONTAINER_L86: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_CONTAINER_L86',
      path: 'home.dom.featured-marquee.titlekey-container-l86',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:86',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TITLEKEY_CONTAINER_L89: {
      id: 'UI_HOME_STRUCTURE_TITLEKEY_CONTAINER_L89',
      path: 'home.dom.featured-marquee.titlekey-container-l89',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/FeaturedMarquee.tsx:89',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    BADGEKEY_CONTAINER_L68: {
      id: 'UI_HOME_STRUCTURE_BADGEKEY_CONTAINER_L68',
      path: 'home.dom.hero-slider.badgekey-container-l68',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/HeroSlider.tsx:68',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_WRAPPER_L22: {
      id: 'UI_HOME_STRUCTURE_KEY_WRAPPER_L22',
      path: 'home.dom.trending-ribbon.key-wrapper-l22',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/TrendingRibbon.tsx:22',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_WRAPPER_L23: {
      id: 'UI_HOME_STRUCTURE_KEY_WRAPPER_L23',
      path: 'home.dom.trending-ribbon.key-wrapper-l23',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/TrendingRibbon.tsx:23',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_SPAN_L25: {
      id: 'UI_HOME_STRUCTURE_KEY_SPAN_L25',
      path: 'home.dom.trending-ribbon.key-span-l25',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/TrendingRibbon.tsx:25',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_WRAPPER_L30: {
      id: 'UI_HOME_STRUCTURE_KEY_WRAPPER_L30',
      path: 'home.dom.trending-ribbon.key-wrapper-l30',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/TrendingRibbon.tsx:30',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_CONTAINER_L32: {
      id: 'UI_HOME_STRUCTURE_KEY_CONTAINER_L32',
      path: 'home.dom.trending-ribbon.key-container-l32',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/TrendingRibbon.tsx:32',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_SPAN_L33: {
      id: 'UI_HOME_STRUCTURE_KEY_SPAN_L33',
      path: 'home.dom.trending-ribbon.key-span-l33',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/TrendingRibbon.tsx:33',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    KEY_SPAN_L36: {
      id: 'UI_HOME_STRUCTURE_KEY_SPAN_L36',
      path: 'home.dom.trending-ribbon.key-span-l36',
      lifecycle: 'active',
      description: 'Structural element at src/components/home/TrendingRibbon.tsx:36',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LANGUAGE_SWITCHER_ENGLISH_BUTTON_WRAPPER_L15: {
      id: 'UI_HOME_STRUCTURE_LANGUAGE_SWITCHER_ENGLISH_BUTTON_WRAPPER_L15',
      path: 'home.dom.language-switcher.language-switcher-english-button-wrapper-l15',
      lifecycle: 'active',
      description: 'Structural element at src/components/shared/LanguageSwitcher.tsx:15',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },} as const;

// ============================================================================
// SPLASH PAGE IDENTIFIERS
// ============================================================================
