/** Auto-split from registry.ts */
export const HOME = {
  LANGUAGE_SWITCHER: {
    ENGLISH_BUTTON: {
uuid: '38a914ca-716f-55bd-b177-54f00e0b2f1b',
      id: 'UI_HOME_LANG_ENGLISH',
      path: 'home.language-switcher.buttons.english-button',
      lifecycle: 'active',
      description: 'English language switcher button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    ARABIC_BUTTON: {
uuid: '8d25ea72-53a4-59a7-870e-8c741ca321e9',
      id: 'UI_HOME_LANG_ARABIC',
      path: 'home.language-switcher.buttons.arabic-button',
      lifecycle: 'active',
      description: 'Arabic language switcher button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },
  PROMO_BANNER: {
    CONTAINER: {
uuid: '107a634b-839d-5cbc-9702-72b14753f3a2',
      id: 'UI_HOME_PROMO_BANNER_CONTAINER',
      path: 'home.promo-banner.layout.container',
      lifecycle: 'active',
      description: 'Promo banner section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    CONTENT_WRAPPER: {
uuid: '7a56ab4d-31c4-5a72-a955-d97ff8a0a71c',
      id: 'UI_HOME_PROMO_BANNER_CONTENT_WRAPPER',
      path: 'home.promo-banner.layout.content-wrapper',
      lifecycle: 'active',
      description: 'Promo banner content wrapper',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    ACTION_BUTTON: {
uuid: '0540ae86-babc-564b-a885-2620eb5d04ed',
      id: 'UI_HOME_PROMO_BANNER_ACTION',
      path: 'home.promo-banner.actions.banner-button',
      lifecycle: 'active',
      description: 'Promo banner call-to-action button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    TITLE: {
uuid: 'c537d012-980e-5205-8dc7-dfd4b4118a3f',
      id: 'UI_HOME_PROMO_BANNER_TITLE',
      path: 'home.promo-banner.display.title',
      lifecycle: 'active',
      description: 'Promo banner main heading',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    DESCRIPTION: {
uuid: '9dd0782e-d811-5ddd-885c-9364f6283a1b',
      id: 'UI_HOME_PROMO_BANNER_DESCRIPTION',
      path: 'home.promo-banner.display.description',
      lifecycle: 'active',
      description: 'Promo banner description text',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    LOGO: {
uuid: 'afb9f7fb-5e44-520e-8985-bc551f347208',
      id: 'UI_HOME_PROMO_BANNER_LOGO',
      path: 'home.promo-banner.display.logo',
      lifecycle: 'active',
      description: 'Promo banner logo image',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    DECORATIVE_BACKGROUND: {
uuid: '1a84444b-f465-576c-9ea4-3bbd33dd877e',
      id: 'UI_HOME_PROMO_BANNER_DECORATIVE_BACKGROUND',
      path: 'home.promo-banner.decorative.background',
      lifecycle: 'active',
      description: 'Promo banner decorative background',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
  },
  CURATED_OFFERS: {
    CONTAINER: {
uuid: '485db1a9-bbdf-5192-9d5d-57df2f586640',
      id: 'UI_HOME_CURATED_OFFERS_CONTAINER',
      path: 'home.curated-offers.layout.container',
      lifecycle: 'active',
      description: 'Curated offers section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    HEADER: {
uuid: '032ab0e3-27e1-594e-a5c1-b2ed1e2dfc48',
      id: 'UI_HOME_CURATED_OFFERS_HEADER',
      path: 'home.curated-offers.layout.header',
      lifecycle: 'active',
      description: 'Curated offers section header',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_GRID: {
uuid: '58d14d2a-fb74-50af-844d-62f80b8ffa3d',
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_GRID',
      path: 'home.curated-offers.layout.product-grid',
      lifecycle: 'active',
      description: 'Curated offers product grid',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_CARD: {
uuid: '5cc8c348-8b2f-535d-8e19-a6b6d1f75323',
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_CARD',
      path: 'home.curated-offers.layout.product-card',
      lifecycle: 'active',
      description: 'Curated offers product card',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_IMAGE_CONTAINER: {
uuid: 'f36e272f-44e1-5fa0-9343-94bdb05a0e46',
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE_CONTAINER',
      path: 'home.curated-offers.layout.product-image-container',
      lifecycle: 'active',
      description: 'Curated offers product image container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRODUCT_INFO: {
uuid: '6cc3be8a-7e2a-5d6f-a876-a4e403417639',
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_INFO',
      path: 'home.curated-offers.layout.product-info',
      lifecycle: 'active',
      description: 'Curated offers product info section',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    PRICE_ROW: {
uuid: 'c2f6b2a8-0a1c-5263-9981-19b29325be35',
      id: 'UI_HOME_CURATED_OFFERS_PRICE_ROW',
      path: 'home.curated-offers.layout.price-row',
      lifecycle: 'active',
      description: 'Curated offers price row',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SHOW_MORE_CONTAINER: {
uuid: 'e67b3c09-b619-588a-8f79-fcdba724f124',
      id: 'UI_HOME_CURATED_OFFERS_SHOW_MORE_CONTAINER',
      path: 'home.curated-offers.layout.show-more-container',
      lifecycle: 'active',
      description: 'Curated offers show more button container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SHOW_MORE: {
uuid: 'd1105943-783f-57d2-99bf-ff1984020cf8',
      id: 'UI_HOME_CURATED_OFFERS_MORE',
      path: 'home.curated-offers.actions.show-more-button',
      lifecycle: 'active',
      description: 'Show more curated offers button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    ADD_TO_CART: {
uuid: '1bbf218e-0417-5e51-9e53-8dcc82c2933f',
      id: 'UI_HOME_CURATED_OFFERS_ADD_TO_CART',
      path: 'home.curated-offers.actions.add-to-cart-button',
      lifecycle: 'active',
      description: 'Add item to cart button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    ADD_TO_FAVORITES: {
uuid: '0e3c1ff6-0a95-5e47-b502-fdf4b9740105',
      id: 'UI_HOME_CURATED_OFFERS_FAVORITE',
      path: 'home.curated-offers.actions.add-to-favorites-button',
      lifecycle: 'active',
      description: 'Add item to favorites button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PRODUCT_IMAGE: {
uuid: 'e905f1d7-551a-5b30-8d73-a705c3e1b696',
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE',
      path: 'home.curated-offers.display.product-image',
      lifecycle: 'active',
      description: 'Product image in curated offers',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    CATEGORY_LABEL: {
uuid: 'b87fa2cf-77b1-5e9a-a2dd-92f52e8678b8',
      id: 'UI_HOME_CURATED_OFFERS_CATEGORY_LABEL',
      path: 'home.curated-offers.display.category-label',
      lifecycle: 'active',
      description: 'Product category label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PRODUCT_TITLE: {
uuid: 'f180a614-775a-5f4b-8b10-727ea582c0cd',
      id: 'UI_HOME_CURATED_OFFERS_PRODUCT_TITLE',
      path: 'home.curated-offers.display.product-title',
      lifecycle: 'active',
      description: 'Product title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PRICE_LABEL: {
uuid: '7528dada-9a54-5415-8b65-9dd44f13de5f',
      id: 'UI_HOME_CURATED_OFFERS_PRICE_LABEL',
      path: 'home.curated-offers.display.price-label',
      lifecycle: 'active',
      description: 'Product price label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SECTION_TITLE: {
uuid: '95c0c3f8-7d73-5d6f-8631-3a56c9d829ed',
      id: 'UI_HOME_CURATED_OFFERS_SECTION_TITLE',
      path: 'home.curated-offers.display.section-title',
      lifecycle: 'active',
      description: 'Curated offers section title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    PROMO_TAG: {
uuid: '6c8e3d42-7222-5f9d-801c-3cd035255013',
      id: 'UI_HOME_CURATED_OFFERS_PROMO_TAG',
      path: 'home.curated-offers.display.promo-tag',
      lifecycle: 'active',
      description: 'Curated offers promo tag',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },
  HERO_SLIDER: {
    CONTAINER: {
uuid: '35087503-4f0c-50d2-aa1b-e421dab95950',
      id: 'UI_HOME_HERO_SLIDER_CONTAINER',
      path: 'home.hero-slider.layout.container',
      lifecycle: 'active',
      description: 'Hero slider section container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDER_TRACK: {
uuid: '5113b031-ec30-5612-872c-bda7b47118d8',
      id: 'UI_HOME_HERO_SLIDER_SLIDER_TRACK',
      path: 'home.hero-slider.layout.slider-track',
      lifecycle: 'active',
      description: 'Hero slider track container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDE: {
uuid: 'bef0f761-bec9-50d8-9a93-967756b86a7e',
      id: 'UI_HOME_HERO_SLIDER_SLIDE',
      path: 'home.hero-slider.layout.slide',
      lifecycle: 'active',
      description: 'Hero slider slide container',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDE_CONTENT: {
uuid: '428dd9d3-9c8b-5e62-9d0f-4f1dc2374994',
      id: 'UI_HOME_HERO_SLIDER_SLIDE_CONTENT',
      path: 'home.hero-slider.layout.slide-content',
      lifecycle: 'active',
      description: 'Hero slider slide content overlay',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    INDICATORS: {
uuid: '29e2ed12-ca0e-5d35-b197-fbac5f598a7f',
      id: 'UI_HOME_HERO_SLIDER_INDICATORS',
      path: 'home.hero-slider.layout.indicators',
      lifecycle: 'active',
      description: 'Hero slider dot indicators',
      category: 'container',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    SLIDE_IMAGE: {
uuid: 'cb7f2aaf-8c20-5b1a-9a48-f44587bd0e28',
      id: 'UI_HOME_HERO_SLIDER_SLIDE_IMAGE',
      path: 'home.hero-slider.display.slide-image',
      lifecycle: 'active',
      description: 'Hero slider slide image',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SLIDE_TITLE: {
uuid: '16bcf24c-528d-58a9-876c-39beec170463',
      id: 'UI_HOME_HERO_SLIDER_SLIDE_TITLE',
      path: 'home.hero-slider.display.slide-title',
      lifecycle: 'active',
      description: 'Hero slider slide title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SLIDE_BADGE: {
uuid: 'da8a3951-b71d-5158-8501-6f43d4c815c2',
      id: 'UI_HOME_HERO_SLIDER_SLIDE_BADGE',
      path: 'home.hero-slider.display.slide-badge',
      lifecycle: 'active',
      description: 'Hero slider slide badge',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },
  CATEGORIES_GRID: {
    TOGGLE: {
uuid: '4d96c903-4026-5d64-b003-27114c48b5f2',
      id: 'UI_HOME_CATEGORIES_GRID_TOGGLE',
      path: 'home.categories-grid.actions.toggle-button',
      lifecycle: 'active',
      description: 'Toggle categories grid layout button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    ITEM: {
uuid: 'ddc65ba8-04b2-5a47-bc76-ddaa6685edb1',
      id: 'UI_HOME_CATEGORIES_GRID_ITEM',
      path: 'home.categories-grid.actions.category-button',
      lifecycle: 'active',
      description: 'Select category button',
      category: 'action',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    CATEGORY_IMAGE: {
uuid: 'a4172aa1-94fe-5262-bfc6-e39b098ec46c',
      id: 'UI_HOME_CATEGORIES_GRID_CATEGORY_IMAGE',
      path: 'home.categories-grid.display.category-image',
      lifecycle: 'active',
      description: 'Category image in grid',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    CATEGORY_NAME: {
uuid: '62a7ee4f-6607-519e-9970-39152b9de294',
      id: 'UI_HOME_CATEGORIES_GRID_CATEGORY_NAME',
      path: 'home.categories-grid.display.category-name',
      lifecycle: 'active',
      description: 'Category name label',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    SECTION_TITLE: {
uuid: 'b6226727-2816-5e66-9fe6-735128d31df8',
      id: 'UI_HOME_CATEGORIES_GRID_SECTION_TITLE',
      path: 'home.categories-grid.display.section-title',
      lifecycle: 'active',
      description: 'Categories section title',
      category: 'display',
      feature: 'home',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
  },
} as const;

// ============================================================================
// SPLASH PAGE IDENTIFIERS
// ============================================================================
