/** image-upload-form feature UI identities */
export const IMAGE_UPLOAD_FORM = {
  PAGE: {
        CONTAINER: {
uuid: '0f9ef543-6486-538a-9480-fca1962dd810',
          id: 'UI_IMAGE_UPLOAD_FORM_PAGE_CONTAINER',
          path: 'image-upload-form.page.layout.container',
          lifecycle: 'active',
          description: 'Page root container',
          category: 'container',
          feature: 'image-upload-form',
          version: '1.0.0',
          createdAt: '2026-06-20',
          updatedAt: '2026-06-20',
} as const,
        TITLE: {
uuid: 'a5e11cca-caba-5ea7-9897-e0447ca05f41',
          id: 'UI_IMAGE_UPLOAD_FORM_PAGE_TITLE',
          path: 'image-upload-form.page.display.title',
          lifecycle: 'active',
          description: 'Page title',
          category: 'display',
          feature: 'image-upload-form',
          version: '1.0.0',
          createdAt: '2026-06-20',
          updatedAt: '2026-06-20',
} as const,
        DESCRIPTION: {
uuid: 'e72b30a6-8870-52e3-b57b-9794149ed8a1',
          id: 'UI_IMAGE_UPLOAD_FORM_PAGE_DESCRIPTION',
          path: 'image-upload-form.page.display.description',
          lifecycle: 'active',
          description: 'Page description',
          category: 'display',
          feature: 'image-upload-form',
          version: '1.0.0',
          createdAt: '2026-06-20',
          updatedAt: '2026-06-20',
} as const,
        CREATE_BUTTON: {
uuid: '0b6cc731-753a-51b6-bf59-75c3efa5e2e0',
          id: 'UI_IMAGE_UPLOAD_FORM_ACTIONS_CREATE_BUTTON',
          path: 'image-upload-form.actions.create-button',
          lifecycle: 'active',
          description: 'Create action button',
          category: 'action',
          feature: 'image-upload-form',
          version: '1.0.0',
          createdAt: '2026-06-20',
          updatedAt: '2026-06-20',
} as const,
        SAVE_BUTTON: {
uuid: '89af3dca-6269-5911-83da-7e143fc8f0fb',
          id: 'UI_IMAGE_UPLOAD_FORM_ACTIONS_SAVE_BUTTON',
          path: 'image-upload-form.actions.save-button',
          lifecycle: 'active',
          description: 'Save action button',
          category: 'action',
          feature: 'image-upload-form',
          version: '1.0.0',
          createdAt: '2026-06-20',
          updatedAt: '2026-06-20',
} as const,
        ROW: {
uuid: 'fd2ef148-0438-5aeb-8e64-369ef9aacf29',
          id: 'UI_IMAGE_UPLOAD_FORM_ACTIONS_ROW',
          path: 'image-upload-form.actions.layout.row',
          lifecycle: 'active',
          description: 'Actions button row',
          category: 'container',
          feature: 'image-upload-form',
          version: '1.0.0',
          createdAt: '2026-06-20',
          updatedAt: '2026-06-20',
} as const,
  },
  FORM: {
    FIELD1_LABEL: {
uuid: 'c8ae5681-29d3-59ca-a31b-b63ba7359644',
id: 'UI_IMAGE_UPLOAD_FORM_FORM_FIELD1_LABEL',
      path: 'image-upload-form.form.display.field1-label',
      lifecycle: 'active',
      description: 'Field 1 label',
      category: 'display',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FIELD1_INPUT: {
uuid: '69140c6f-08f7-5e70-a6d0-e8d16648a212',
id: 'UI_IMAGE_UPLOAD_FORM_FORM_FIELD1_INPUT',
      path: 'image-upload-form.form.input.field1',
      lifecycle: 'active',
      description: 'Field 1 input',
      category: 'input',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FIELD2_LABEL: {
uuid: '30488744-1cf1-59db-8fb2-ea2a3f9b6581',
id: 'UI_IMAGE_UPLOAD_FORM_FORM_FIELD2_LABEL',
      path: 'image-upload-form.form.display.field2-label',
      lifecycle: 'active',
      description: 'Field 2 label',
      category: 'display',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FIELD2_INPUT: {
uuid: 'ef5b9312-0a88-5d71-a55e-30d0e0011b6f',
id: 'UI_IMAGE_UPLOAD_FORM_FORM_FIELD2_INPUT',
      path: 'image-upload-form.form.input.field2',
      lifecycle: 'active',
      description: 'Field 2 input',
      category: 'input',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FIELD3_LABEL: {
uuid: '6ad2cc2f-6c27-5410-8a6c-3dfd1bc5b4be',
id: 'UI_IMAGE_UPLOAD_FORM_FORM_FIELD3_LABEL',
      path: 'image-upload-form.form.display.field3-label',
      lifecycle: 'active',
      description: 'Field 3 label',
      category: 'display',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FIELD3_INPUT: {
uuid: 'b060a1b5-3958-5fde-90be-f27b3e115924',
id: 'UI_IMAGE_UPLOAD_FORM_FORM_FIELD3_INPUT',
      path: 'image-upload-form.form.input.field3',
      lifecycle: 'active',
      description: 'Field 3 input',
      category: 'input',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  GALLERY: {
    CONTAINER: {
uuid: '2e800f0e-147a-5961-8d35-017c7e6786af',
id: 'UI_IMAGE_UPLOAD_FORM_GALLERY_CONTAINER',
      path: 'image-upload-form.gallery.layout.container',
      lifecycle: 'active',
      description: 'Gallery container',
      category: 'container',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SELECT_BUTTON: {
uuid: 'b78f0520-c97a-544f-b83c-66123943f4e9',
id: 'UI_IMAGE_UPLOAD_FORM_GALLERY_SELECT_BUTTON',
      path: 'image-upload-form.gallery.actions.select-button',
      lifecycle: 'active',
      description: 'Select images button',
      category: 'action',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FILE_INPUT: {
uuid: 'ad2fa9da-bf8e-5857-944e-669494fe4a21',
id: 'UI_IMAGE_UPLOAD_FORM_GALLERY_FILE_INPUT',
      path: 'image-upload-form.gallery.input.file-input',
      lifecycle: 'active',
      description: 'Hidden file input',
      category: 'input',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PREVIEW_IMAGE: {
uuid: '58074a33-c71b-5648-a558-16214acf881e',
id: 'UI_IMAGE_UPLOAD_FORM_GALLERY_PREVIEW_IMAGE',
      path: 'image-upload-form.gallery.display.preview-image',
      lifecycle: 'active',
      description: 'Preview image',
      category: 'display',
      feature: 'image-upload-form',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
      repeatable: true,
} as const,
  },
} as const;
