export const MERCHANT = {
  MERCHANT_PROFILE: {
    HERO: {
      CONTAINER: {
uuid: '422c491a-06cd-55fd-b7f8-632046559e73',
        id: 'UI_MERCHANT_PROFILE_HERO_CONTAINER',
        path: 'merchant.hero.display.container',
        lifecycle: 'active',
        description: 'Merchant profile hero container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      BANNER: {
uuid: '1ff85999-dff4-576c-8c93-f967346eeb22',
        id: 'UI_MERCHANT_PROFILE_HERO_BANNER',
        path: 'merchant.hero.display.banner',
        lifecycle: 'active',
        description: 'Merchant banner image',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      AVATAR: {
uuid: 'a84223c6-bb25-54bf-a9d8-b5dcda6beec5',
        id: 'UI_MERCHANT_PROFILE_HERO_AVATAR',
        path: 'merchant.hero.display.avatar',
        lifecycle: 'active',
        description: 'Merchant avatar/logo',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      NAME: {
uuid: 'f1ee4e9c-95cb-540d-9a1d-c57efcff57b7',
        id: 'UI_MERCHANT_PROFILE_HERO_NAME',
        path: 'merchant.hero.display.name',
        lifecycle: 'active',
        description: 'Merchant name',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      VERIFIED_BADGE: {
uuid: 'fab7dea3-272d-593e-a2bc-825d9fccd318',
        id: 'UI_MERCHANT_PROFILE_HERO_VERIFIED',
        path: 'merchant.hero.display.verified-badge',
        lifecycle: 'active',
        description: 'Verified badge text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FOLLOWERS: {
uuid: '82115972-da26-52f1-be55-e9240307ea53',
        id: 'UI_MERCHANT_PROFILE_HERO_FOLLOWERS',
        path: 'merchant.hero.display.followers',
        lifecycle: 'active',
        description: 'Followers text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FOLLOWING: {
uuid: '7065e4de-7249-5d1d-bfca-2e804b3fd147',
        id: 'UI_MERCHANT_PROFILE_HERO_FOLLOWING',
        path: 'merchant.hero.display.following',
        lifecycle: 'active',
        description: 'Following text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      FOLLOW_BUTTON: {
uuid: 'b1d25722-365e-535b-a2bf-95a8479b6eb9',
        id: 'UI_MERCHANT_PROFILE_HERO_FOLLOW',
        path: 'merchant.hero.display.follow-button',
        lifecycle: 'active',
        description: 'Follow merchant button',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      MESSAGE_BUTTON: {
uuid: 'befd67fe-7d9a-56ad-8c05-37bc99e4297b',
        id: 'UI_MERCHANT_PROFILE_HERO_MESSAGE',
        path: 'merchant.hero.display.message-button',
        lifecycle: 'active',
        description: 'Message merchant button',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      JOINED: {
uuid: 'fde7cdfe-9849-5e2b-9975-34084b1569ad',
        id: 'UI_MERCHANT_PROFILE_HERO_JOINED',
        path: 'merchant.hero.display.joined',
        lifecycle: 'active',
        description: 'Joined date text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      BANNER_ALT_SUFFIX: {
uuid: 'e81a0d1f-3047-582c-a1d6-c1c5030f153a',
        id: 'UI_MERCHANT_PROFILE_HERO_BANNER_ALT_SUFFIX',
        path: 'merchant.hero.display.banner-alt-suffix',
        lifecycle: 'active',
        description: 'Merchant banner alt suffix',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STATUS_LABEL: {
uuid: 'beb9c238-baca-5d25-8c73-a2d6a356b093',
        id: 'UI_MERCHANT_PROFILE_HERO_STATUS_LABEL',
        path: 'merchant.hero.display.status-label',
        lifecycle: 'active',
        description: 'Merchant status aria label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    OVERVIEW: {
      CONTAINER: {
uuid: 'e3da8de1-2452-5a16-89c9-59eb98fb12d8',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_CONTAINER',
        path: 'merchant.overview.display.container',
        lifecycle: 'active',
        description: 'Merchant overview section container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      CARD: {
uuid: 'ec6e6c78-6cf9-5f6d-b3a2-59fa9e251f9f',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_CARD',
        path: 'merchant.overview.display.card',
        lifecycle: 'active',
        description: 'Merchant overview stat card',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      PRODUCTS: {
uuid: 'a1632076-fa5d-5633-8321-fd388fbaab8d',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_PRODUCTS',
        path: 'merchant.overview.display.products',
        lifecycle: 'active',
        description: 'Products label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ORDERS: {
uuid: 'b896b60b-323e-5c2a-b5a1-23bdec2e9eac',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_ORDERS',
        path: 'merchant.overview.display.orders',
        lifecycle: 'active',
        description: 'Orders label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      CUSTOMERS: {
uuid: 'fea3e7c3-bc00-5ba4-8080-c125f92c793e',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_CUSTOMERS',
        path: 'merchant.overview.display.customers',
        lifecycle: 'active',
        description: 'Customers label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      RATING: {
uuid: 'a4d28e2b-3f49-5772-a716-a081ac591810',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_RATING',
        path: 'merchant.overview.display.rating',
        lifecycle: 'active',
        description: 'Rating label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      REVENUE: {
uuid: '6d9362ea-4ac7-5399-a440-b39cb0dfbfbb',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_REVENUE',
        path: 'merchant.overview.display.revenue',
        lifecycle: 'active',
        description: 'Revenue label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      COMPLETION_RATE: {
uuid: '46672967-afe6-574c-881f-9d058b048dea',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_COMPLETION_RATE',
        path: 'merchant.overview.display.completion-rate',
        lifecycle: 'active',
        description: 'Completion rate label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      RESPONSE_RATE: {
uuid: '7615813c-509e-5477-a78c-cc26958fcbd9',
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_RESPONSE_RATE',
        path: 'merchant.overview.display.response-rate',
        lifecycle: 'active',
        description: 'Response rate label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    QUICK_ACTIONS: {
      CONTAINER: {
uuid: '484cb035-271f-50b4-9b41-d0fb0031006a',
        id: 'UI_MERCHANT_PROFILE_QUICK_ACTIONS_CONTAINER',
        path: 'merchant.quick-actions.display.container',
        lifecycle: 'active',
        description: 'Quick actions section container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      BUTTON: {
uuid: '40c6a83d-6410-5fa4-98f8-fff7872bf526',
        id: 'UI_MERCHANT_PROFILE_QUICK_ACTION_BUTTON',
        path: 'merchant.quick-actions.display.button',
        lifecycle: 'active',
        description: 'Quick action button',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: '02c846c0-a187-5abd-8c1e-a742ad229e07',
        id: 'UI_MERCHANT_PROFILE_QUICK_ACTIONS_TITLE',
        path: 'merchant.quick-actions.display.title',
        lifecycle: 'active',
        description: 'Quick actions section title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    PERFORMANCE: {
      CONTAINER: {
uuid: 'd32c35bc-19f7-5a21-b6c1-67c663510c4b',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_CONTAINER',
        path: 'merchant.performance.display.container',
        lifecycle: 'active',
        description: 'Performance dashboard container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: 'e1f58b05-00f3-55c4-8f19-8d0bf705e912',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_TITLE',
        path: 'merchant.performance.display.title',
        lifecycle: 'active',
        description: 'Performance dashboard title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      REVENUE_TODAY: {
uuid: '043e53a9-4312-5678-a8e6-b8b3483769f2',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_TODAY',
        path: 'merchant.performance.display.revenue-today',
        lifecycle: 'active',
        description: 'Revenue today label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      REVENUE_TODAY_SUBTITLE: {
uuid: 'e91d92f6-a469-5959-bbd3-3a1094d9e39b',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_TODAY_SUBTITLE',
        path: 'merchant.performance.display.revenue-today-subtitle',
        lifecycle: 'active',
        description: 'Revenue today subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      REVENUE_MONTH: {
uuid: '9fc5c9d6-216f-597b-8d21-fc94d21cd1d1',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_MONTH',
        path: 'merchant.performance.display.revenue-month',
        lifecycle: 'active',
        description: 'Revenue this month label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      REVENUE_MONTH_SUBTITLE: {
uuid: 'a155b477-17da-5158-a8ad-efdd24efcc9e',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_MONTH_SUBTITLE',
        path: 'merchant.performance.display.revenue-month-subtitle',
        lifecycle: 'active',
        description: 'Revenue this month subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ORDERS_TODAY: {
uuid: '2962ad3e-847f-5c2d-b2fa-8a086329bf27',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_TODAY',
        path: 'merchant.performance.display.orders-today',
        lifecycle: 'active',
        description: 'Orders today label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ORDERS_TODAY_SUBTITLE: {
uuid: '02c23edf-35dc-5d02-a33b-57e969cbf32c',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_TODAY_SUBTITLE',
        path: 'merchant.performance.display.orders-today-subtitle',
        lifecycle: 'active',
        description: 'Orders today subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ORDERS_MONTH: {
uuid: 'ea185185-38d2-5d62-abcd-f92baf5cf2d0',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_MONTH',
        path: 'merchant.performance.display.orders-month',
        lifecycle: 'active',
        description: 'Orders this month label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ORDERS_MONTH_SUBTITLE: {
uuid: '91f4193a-85d2-5e4b-8399-388815207e71',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_MONTH_SUBTITLE',
        path: 'merchant.performance.display.orders-month-subtitle',
        lifecycle: 'active',
        description: 'Orders this month subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      CONVERSION_RATE: {
uuid: '14679420-b33b-551d-844d-1b8e5148534b',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_CONVERSION_RATE',
        path: 'merchant.performance.display.conversion-rate',
        lifecycle: 'active',
        description: 'Conversion rate label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      CONVERSION_RATE_SUBTITLE: {
uuid: 'bfbfa581-ede0-5672-81f4-4a2feac288e8',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_CONVERSION_RATE_SUBTITLE',
        path: 'merchant.performance.display.conversion-rate-subtitle',
        lifecycle: 'active',
        description: 'Conversion rate subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      AVG_ORDER_VALUE: {
uuid: 'fadc8ba2-ea29-5f0f-bf27-a3605b705c3d',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_AVG_ORDER_VALUE',
        path: 'merchant.performance.display.avg-order-value',
        lifecycle: 'active',
        description: 'Average order value label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      AVG_ORDER_VALUE_SUBTITLE: {
uuid: '02b6a98b-1277-5194-91fb-59c14336f152',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_AVG_ORDER_VALUE_SUBTITLE',
        path: 'merchant.performance.display.avg-order-value-subtitle',
        lifecycle: 'active',
        description: 'Average order value subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      BEST_SELLING_CATEGORY: {
uuid: '79735e61-f01f-57ac-867a-95bb06fa286e',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_BEST_SELLING_CATEGORY',
        path: 'merchant.performance.display.best-selling-category',
        lifecycle: 'active',
        description: 'Best selling category label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      BEST_SELLING_CATEGORY_SUBTITLE: {
uuid: '22c6692e-ba18-5c95-ab9a-1c98ef4676cf',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_BEST_SELLING_CATEGORY_SUBTITLE',
        path: 'merchant.performance.display.best-selling-category-subtitle',
        lifecycle: 'active',
        description: 'Best selling category subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      INVENTORY_HEALTH: {
uuid: 'ecd34eba-e64e-542d-8043-548c881ab557',
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_INVENTORY_HEALTH',
        path: 'merchant.performance.display.inventory-health',
        lifecycle: 'active',
        description: 'Inventory health label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    COLLECTIONS: {
      CONTAINER: {
uuid: '6504d413-c393-5ae2-a6a1-26156cb71fc4',
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_CONTAINER',
        path: 'merchant.collections.display.container',
        lifecycle: 'active',
        description: 'Featured collections container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      CARD: {
uuid: '0fad23f2-b5f5-57f1-a6ac-a9841dae2a23',
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_CARD',
        path: 'merchant.collections.display.card',
        lifecycle: 'active',
        description: 'Collection card',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: '1e0fb61a-e35b-5c7f-8f87-4020d65735cd',
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_TITLE',
        path: 'merchant.collections.display.title',
        lifecycle: 'active',
        description: 'Featured collections title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      VIEW_ALL: {
uuid: '3659295d-a4a1-5892-8779-60ab2bc0ec00',
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_VIEW_ALL',
        path: 'merchant.collections.display.view-all',
        lifecycle: 'active',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ITEMS: {
uuid: '9db97800-dbca-5899-83ba-db52c831194b',
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_ITEMS',
        path: 'merchant.collections.display.items',
        lifecycle: 'active',
        description: 'Items count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    BEST_SELLERS: {
      CONTAINER: {
uuid: '2755b4c7-c603-5554-9250-b5cd353d057a',
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_CONTAINER',
        path: 'merchant.best-sellers.display.container',
        lifecycle: 'active',
        description: 'Best sellers container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      CARD: {
uuid: '28364e9e-c6c6-56b3-987f-decc3d8b3cb9',
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_CARD',
        path: 'merchant.best-sellers.display.card',
        lifecycle: 'active',
        description: 'Product card',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: 'f4ac98f6-e472-5edd-b902-45d824b7a3d7',
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_TITLE',
        path: 'merchant.best-sellers.display.title',
        lifecycle: 'active',
        description: 'Best selling products title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      VIEW_ALL: {
uuid: '24c1ba11-36e7-57d0-9648-66b37e6e0eda',
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_VIEW_ALL',
        path: 'merchant.best-sellers.display.view-all',
        lifecycle: 'active',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      PERCENT_OFF: {
uuid: '16d830e7-e9d4-5870-a076-b7bd34142716',
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_PERCENT_OFF',
        path: 'merchant.best-sellers.display.percent-off',
        lifecycle: 'active',
        description: 'Percent off badge text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SOLD: {
uuid: '45b4e13a-3005-5553-ac52-53f8682a8a99',
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_SOLD',
        path: 'merchant.best-sellers.display.sold',
        lifecycle: 'active',
        description: 'Sold count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    RECENT_ORDERS: {
      CONTAINER: {
uuid: 'c2a8784b-89d2-52b6-92ce-952db8097a18',
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_CONTAINER',
        path: 'merchant.recent-orders.display.container',
        lifecycle: 'active',
        description: 'Recent orders container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: 'bc7e9512-d0ac-5f7b-b0ae-55b8ef12b429',
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_TITLE',
        path: 'merchant.recent-orders.display.title',
        lifecycle: 'active',
        description: 'Recent orders title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      VIEW_ALL: {
uuid: 'f571b605-6898-59d6-b85c-ce5364a67204',
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_VIEW_ALL',
        path: 'merchant.recent-orders.display.view-all',
        lifecycle: 'active',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ITEM: {
uuid: '1996d2db-8560-591c-a834-a9bd5d0c3066',
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_ITEM',
        path: 'merchant.recent-orders.display.item',
        lifecycle: 'active',
        description: 'Item count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ITEMS: {
uuid: 'd06d6c18-462a-575d-b8e7-81aaaf2fe36f',
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_ITEMS',
        path: 'merchant.recent-orders.display.items',
        lifecycle: 'active',
        description: 'Items count text (plural)',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    REVIEWS: {
      CONTAINER: {
uuid: '61f6fdeb-063f-5b0a-a9fe-3a6d18695cac',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_CONTAINER',
        path: 'merchant.reviews.display.container',
        lifecycle: 'active',
        description: 'Customer reviews container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: '2abb3cb2-62ad-5e27-bff4-6af8425a2875',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_TITLE',
        path: 'merchant.reviews.display.title',
        lifecycle: 'active',
        description: 'Customer reviews title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      VIEW_ALL: {
uuid: 'a8f82d65-31ab-562a-9479-ae93965c8118',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_VIEW_ALL',
        path: 'merchant.reviews.display.view-all',
        lifecycle: 'active',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      BASED_ON: {
uuid: '79312799-c35d-5e22-abc0-53e73dee2e18',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_BASED_ON',
        path: 'merchant.reviews.display.based-on',
        lifecycle: 'active',
        description: 'Based on reviews text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      REVIEWS: {
uuid: 'a6e04331-9cff-528c-91ca-b6bf84dd9582',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_REVIEWS',
        path: 'merchant.reviews.display.reviews',
        lifecycle: 'active',
        description: 'Reviews count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STAR: {
uuid: '2060df0c-9a26-58b3-b59f-d70ee304b76d',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_STAR',
        path: 'merchant.reviews.display.star',
        lifecycle: 'active',
        description: 'Star text (singular)',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STARS: {
uuid: '577fa28d-8a2b-58a0-87a0-07679e6c769a',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_STARS',
        path: 'merchant.reviews.display.stars',
        lifecycle: 'active',
        description: 'Stars text (plural)',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      PURCHASED: {
uuid: '24beb6a1-2cc6-5ffc-9c29-64f3d064f3d6',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_PURCHASED',
        path: 'merchant.reviews.display.purchased',
        lifecycle: 'active',
        description: 'Purchased text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      HELPFUL: {
uuid: '2384467a-d161-5df7-8fd9-0d545e8ab9b1',
        id: 'UI_MERCHANT_PROFILE_REVIEWS_HELPFUL',
        path: 'merchant.reviews.display.helpful',
        lifecycle: 'active',
        description: 'Helpful text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    STORE_INFO: {
      CONTAINER: {
uuid: '39dc65b0-2aee-5973-9e10-ece21c1aca7d',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_CONTAINER',
        path: 'merchant.store-info.display.container',
        lifecycle: 'active',
        description: 'Store information container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: '42922561-3bd5-53fa-8582-7e7fb3938348',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_TITLE',
        path: 'merchant.store-info.display.title',
        lifecycle: 'active',
        description: 'Store information title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ABOUT: {
uuid: '1edc6b66-179b-5cb1-b060-426412fcf707',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_ABOUT',
        path: 'merchant.store-info.display.about',
        lifecycle: 'active',
        description: 'About section label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SHOW_LESS: {
uuid: '3bbce5a4-b766-5e07-832c-9e826e1393fd',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_SHOW_LESS',
        path: 'merchant.store-info.display.show-less',
        lifecycle: 'active',
        description: 'Show less button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SHOW_MORE: {
uuid: 'e667d674-bfd3-547f-a881-307aa8230fed',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_SHOW_MORE',
        path: 'merchant.store-info.display.show-more',
        lifecycle: 'active',
        description: 'Show more button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      CATEGORIES: {
uuid: '3c493475-38a6-59a0-9128-724b4003fb0e',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_CATEGORIES',
        path: 'merchant.store-info.display.categories',
        lifecycle: 'active',
        description: 'Categories label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SHIPPING_COVERAGE: {
uuid: '4ee1e6de-fa1f-56f5-9067-27d8020afa07',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_SHIPPING_COVERAGE',
        path: 'merchant.store-info.display.shipping-coverage',
        lifecycle: 'active',
        description: 'Shipping coverage label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      MORE: {
uuid: 'f5896da8-c344-53a5-9133-2ea24fd21a4f',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_MORE',
        path: 'merchant.store-info.display.more',
        lifecycle: 'active',
        description: 'More countries text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      RETURN_POLICY: {
uuid: 'f11c8562-7035-5459-b9c4-0e10923158af',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_RETURN_POLICY',
        path: 'merchant.store-info.display.return-policy',
        lifecycle: 'active',
        description: 'Return policy label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      STORE_SPECIALTIES: {
uuid: '680b7e0d-4c9f-58b6-bca8-60ff243d5058',
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_STORE_SPECIALTIES',
        path: 'merchant.store-info.display.store-specialties',
        lifecycle: 'active',
        description: 'Store specialties label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
    TRUST: {
      CONTAINER: {
uuid: '15afd448-9f66-5579-9e66-1afaf61d330b',
        id: 'UI_MERCHANT_PROFILE_TRUST_CONTAINER',
        path: 'merchant.trust.display.container',
        lifecycle: 'active',
        description: 'Trust & credibility container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
} as const,
      TITLE: {
uuid: 'ff46f319-f98c-5ddc-9992-6157750584d2',
        id: 'UI_MERCHANT_PROFILE_TRUST_TITLE',
        path: 'merchant.trust.display.title',
        lifecycle: 'active',
        description: 'Trust & credibility title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      ACHIEVEMENTS: {
uuid: 'faa679a1-839d-5d86-a1d0-3ecb32b55400',
        id: 'UI_MERCHANT_PROFILE_TRUST_ACHIEVEMENTS',
        path: 'merchant.trust.display.achievements',
        lifecycle: 'active',
        description: 'Achievements label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      SELLER_BADGES: {
uuid: 'ea3f5deb-6ebf-5b6a-ba20-a5c9e1fbb338',
        id: 'UI_MERCHANT_PROFILE_TRUST_SELLER_BADGES',
        path: 'merchant.trust.display.seller-badges',
        lifecycle: 'active',
        description: 'Seller badges label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
      NO_BADGES_EARNED: {
uuid: 'dd149a3b-adb4-5654-b9b8-a899bb855c82',
        id: 'UI_MERCHANT_PROFILE_TRUST_NO_BADGES_EARNED',
        path: 'merchant.trust.display.no-badges-earned',
        lifecycle: 'active',
        description: 'No badges earned text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
} as const,
    },
  },
  COMMON: {
    VIEW_ALL: {
uuid: '6ec6bbb3-7085-52aa-b755-553d21b2255c',
      id: 'UI_MERCHANT_COMMON_VIEW_ALL',
      path: 'merchant.common.view-all',
      lifecycle: 'active',
      description: 'View all button text',
      category: 'action',
      feature: 'merchant',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
} as const;
