export const MERCHANT = {
  MERCHANT_PROFILE: {
    HERO: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_HERO_CONTAINER',
        path: 'merchant.hero.display.container',
        description: 'Merchant profile hero container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      BANNER: {
        id: 'UI_MERCHANT_PROFILE_HERO_BANNER',
        path: 'merchant.hero.display.banner',
        description: 'Merchant banner image',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      AVATAR: {
        id: 'UI_MERCHANT_PROFILE_HERO_AVATAR',
        path: 'merchant.hero.display.avatar',
        description: 'Merchant avatar/logo',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      NAME: {
        id: 'UI_MERCHANT_PROFILE_HERO_NAME',
        path: 'merchant.hero.display.name',
        description: 'Merchant name',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      VERIFIED_BADGE: {
        id: 'UI_MERCHANT_PROFILE_HERO_VERIFIED',
        path: 'merchant.hero.display.verified-badge',
        description: 'Verified badge text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      FOLLOWERS: {
        id: 'UI_MERCHANT_PROFILE_HERO_FOLLOWERS',
        path: 'merchant.hero.display.followers',
        description: 'Followers text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      FOLLOWING: {
        id: 'UI_MERCHANT_PROFILE_HERO_FOLLOWING',
        path: 'merchant.hero.display.following',
        description: 'Following text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      FOLLOW_BUTTON: {
        id: 'UI_MERCHANT_PROFILE_HERO_FOLLOW',
        path: 'merchant.hero.display.follow-button',
        description: 'Follow merchant button',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      MESSAGE_BUTTON: {
        id: 'UI_MERCHANT_PROFILE_HERO_MESSAGE',
        path: 'merchant.hero.display.message-button',
        description: 'Message merchant button',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      JOINED: {
        id: 'UI_MERCHANT_PROFILE_HERO_JOINED',
        path: 'merchant.hero.display.joined',
        description: 'Joined date text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      BANNER_ALT_SUFFIX: {
        id: 'UI_MERCHANT_PROFILE_HERO_BANNER_ALT_SUFFIX',
        path: 'merchant.hero.display.banner-alt-suffix',
        description: 'Merchant banner alt suffix',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      STATUS_LABEL: {
        id: 'UI_MERCHANT_PROFILE_HERO_STATUS_LABEL',
        path: 'merchant.hero.display.status-label',
        description: 'Merchant status aria label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    OVERVIEW: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_CONTAINER',
        path: 'merchant.overview.display.container',
        description: 'Merchant overview section container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      CARD: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_CARD',
        path: 'merchant.overview.display.card',
        description: 'Merchant overview stat card',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      PRODUCTS: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_PRODUCTS',
        path: 'merchant.overview.display.products',
        description: 'Products label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ORDERS: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_ORDERS',
        path: 'merchant.overview.display.orders',
        description: 'Orders label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      CUSTOMERS: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_CUSTOMERS',
        path: 'merchant.overview.display.customers',
        description: 'Customers label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      RATING: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_RATING',
        path: 'merchant.overview.display.rating',
        description: 'Rating label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      REVENUE: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_REVENUE',
        path: 'merchant.overview.display.revenue',
        description: 'Revenue label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      COMPLETION_RATE: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_COMPLETION_RATE',
        path: 'merchant.overview.display.completion-rate',
        description: 'Completion rate label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      RESPONSE_RATE: {
        id: 'UI_MERCHANT_PROFILE_OVERVIEW_RESPONSE_RATE',
        path: 'merchant.overview.display.response-rate',
        description: 'Response rate label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    QUICK_ACTIONS: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_QUICK_ACTIONS_CONTAINER',
        path: 'merchant.quick-actions.display.container',
        description: 'Quick actions section container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      BUTTON: {
        id: 'UI_MERCHANT_PROFILE_QUICK_ACTION_BUTTON',
        path: 'merchant.quick-actions.display.button',
        description: 'Quick action button',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_QUICK_ACTIONS_TITLE',
        path: 'merchant.quick-actions.display.title',
        description: 'Quick actions section title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    PERFORMANCE: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_CONTAINER',
        path: 'merchant.performance.display.container',
        description: 'Performance dashboard container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_TITLE',
        path: 'merchant.performance.display.title',
        description: 'Performance dashboard title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      REVENUE_TODAY: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_TODAY',
        path: 'merchant.performance.display.revenue-today',
        description: 'Revenue today label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      REVENUE_TODAY_SUBTITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_TODAY_SUBTITLE',
        path: 'merchant.performance.display.revenue-today-subtitle',
        description: 'Revenue today subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      REVENUE_MONTH: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_MONTH',
        path: 'merchant.performance.display.revenue-month',
        description: 'Revenue this month label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      REVENUE_MONTH_SUBTITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_REVENUE_MONTH_SUBTITLE',
        path: 'merchant.performance.display.revenue-month-subtitle',
        description: 'Revenue this month subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ORDERS_TODAY: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_TODAY',
        path: 'merchant.performance.display.orders-today',
        description: 'Orders today label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ORDERS_TODAY_SUBTITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_TODAY_SUBTITLE',
        path: 'merchant.performance.display.orders-today-subtitle',
        description: 'Orders today subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ORDERS_MONTH: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_MONTH',
        path: 'merchant.performance.display.orders-month',
        description: 'Orders this month label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ORDERS_MONTH_SUBTITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_ORDERS_MONTH_SUBTITLE',
        path: 'merchant.performance.display.orders-month-subtitle',
        description: 'Orders this month subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      CONVERSION_RATE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_CONVERSION_RATE',
        path: 'merchant.performance.display.conversion-rate',
        description: 'Conversion rate label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      CONVERSION_RATE_SUBTITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_CONVERSION_RATE_SUBTITLE',
        path: 'merchant.performance.display.conversion-rate-subtitle',
        description: 'Conversion rate subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      AVG_ORDER_VALUE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_AVG_ORDER_VALUE',
        path: 'merchant.performance.display.avg-order-value',
        description: 'Average order value label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      AVG_ORDER_VALUE_SUBTITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_AVG_ORDER_VALUE_SUBTITLE',
        path: 'merchant.performance.display.avg-order-value-subtitle',
        description: 'Average order value subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      BEST_SELLING_CATEGORY: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_BEST_SELLING_CATEGORY',
        path: 'merchant.performance.display.best-selling-category',
        description: 'Best selling category label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      BEST_SELLING_CATEGORY_SUBTITLE: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_BEST_SELLING_CATEGORY_SUBTITLE',
        path: 'merchant.performance.display.best-selling-category-subtitle',
        description: 'Best selling category subtitle',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      INVENTORY_HEALTH: {
        id: 'UI_MERCHANT_PROFILE_PERFORMANCE_INVENTORY_HEALTH',
        path: 'merchant.performance.display.inventory-health',
        description: 'Inventory health label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    COLLECTIONS: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_CONTAINER',
        path: 'merchant.collections.display.container',
        description: 'Featured collections container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      CARD: {
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_CARD',
        path: 'merchant.collections.display.card',
        description: 'Collection card',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_TITLE',
        path: 'merchant.collections.display.title',
        description: 'Featured collections title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      VIEW_ALL: {
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_VIEW_ALL',
        path: 'merchant.collections.display.view-all',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ITEMS: {
        id: 'UI_MERCHANT_PROFILE_COLLECTIONS_ITEMS',
        path: 'merchant.collections.display.items',
        description: 'Items count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    BEST_SELLERS: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_CONTAINER',
        path: 'merchant.best-sellers.display.container',
        description: 'Best sellers container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      CARD: {
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_CARD',
        path: 'merchant.best-sellers.display.card',
        description: 'Product card',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_TITLE',
        path: 'merchant.best-sellers.display.title',
        description: 'Best selling products title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      VIEW_ALL: {
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_VIEW_ALL',
        path: 'merchant.best-sellers.display.view-all',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      PERCENT_OFF: {
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_PERCENT_OFF',
        path: 'merchant.best-sellers.display.percent-off',
        description: 'Percent off badge text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      SOLD: {
        id: 'UI_MERCHANT_PROFILE_BEST_SELLERS_SOLD',
        path: 'merchant.best-sellers.display.sold',
        description: 'Sold count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    RECENT_ORDERS: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_CONTAINER',
        path: 'merchant.recent-orders.display.container',
        description: 'Recent orders container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_TITLE',
        path: 'merchant.recent-orders.display.title',
        description: 'Recent orders title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      VIEW_ALL: {
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_VIEW_ALL',
        path: 'merchant.recent-orders.display.view-all',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ITEM: {
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_ITEM',
        path: 'merchant.recent-orders.display.item',
        description: 'Item count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ITEMS: {
        id: 'UI_MERCHANT_PROFILE_RECENT_ORDERS_ITEMS',
        path: 'merchant.recent-orders.display.items',
        description: 'Items count text (plural)',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    REVIEWS: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_CONTAINER',
        path: 'merchant.reviews.display.container',
        description: 'Customer reviews container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_TITLE',
        path: 'merchant.reviews.display.title',
        description: 'Customer reviews title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      VIEW_ALL: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_VIEW_ALL',
        path: 'merchant.reviews.display.view-all',
        description: 'View all button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      BASED_ON: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_BASED_ON',
        path: 'merchant.reviews.display.based-on',
        description: 'Based on reviews text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      REVIEWS: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_REVIEWS',
        path: 'merchant.reviews.display.reviews',
        description: 'Reviews count text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      STAR: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_STAR',
        path: 'merchant.reviews.display.star',
        description: 'Star text (singular)',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      STARS: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_STARS',
        path: 'merchant.reviews.display.stars',
        description: 'Stars text (plural)',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      PURCHASED: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_PURCHASED',
        path: 'merchant.reviews.display.purchased',
        description: 'Purchased text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      HELPFUL: {
        id: 'UI_MERCHANT_PROFILE_REVIEWS_HELPFUL',
        path: 'merchant.reviews.display.helpful',
        description: 'Helpful text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    STORE_INFO: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_CONTAINER',
        path: 'merchant.store-info.display.container',
        description: 'Store information container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_TITLE',
        path: 'merchant.store-info.display.title',
        description: 'Store information title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ABOUT: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_ABOUT',
        path: 'merchant.store-info.display.about',
        description: 'About section label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      SHOW_LESS: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_SHOW_LESS',
        path: 'merchant.store-info.display.show-less',
        description: 'Show less button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      SHOW_MORE: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_SHOW_MORE',
        path: 'merchant.store-info.display.show-more',
        description: 'Show more button text',
        category: 'action',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      CATEGORIES: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_CATEGORIES',
        path: 'merchant.store-info.display.categories',
        description: 'Categories label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      SHIPPING_COVERAGE: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_SHIPPING_COVERAGE',
        path: 'merchant.store-info.display.shipping-coverage',
        description: 'Shipping coverage label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      MORE: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_MORE',
        path: 'merchant.store-info.display.more',
        description: 'More countries text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      RETURN_POLICY: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_RETURN_POLICY',
        path: 'merchant.store-info.display.return-policy',
        description: 'Return policy label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      STORE_SPECIALTIES: {
        id: 'UI_MERCHANT_PROFILE_STORE_INFO_STORE_SPECIALTIES',
        path: 'merchant.store-info.display.store-specialties',
        description: 'Store specialties label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
    TRUST: {
      CONTAINER: {
        id: 'UI_MERCHANT_PROFILE_TRUST_CONTAINER',
        path: 'merchant.trust.display.container',
        description: 'Trust & credibility container',
        category: 'container',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-19',
        updatedAt: '2026-06-19',
      } as const,
      TITLE: {
        id: 'UI_MERCHANT_PROFILE_TRUST_TITLE',
        path: 'merchant.trust.display.title',
        description: 'Trust & credibility title',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      ACHIEVEMENTS: {
        id: 'UI_MERCHANT_PROFILE_TRUST_ACHIEVEMENTS',
        path: 'merchant.trust.display.achievements',
        description: 'Achievements label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      SELLER_BADGES: {
        id: 'UI_MERCHANT_PROFILE_TRUST_SELLER_BADGES',
        path: 'merchant.trust.display.seller-badges',
        description: 'Seller badges label',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
      NO_BADGES_EARNED: {
        id: 'UI_MERCHANT_PROFILE_TRUST_NO_BADGES_EARNED',
        path: 'merchant.trust.display.no-badges-earned',
        description: 'No badges earned text',
        category: 'display',
        feature: 'merchant',
        version: '1.0.0',
        createdAt: '2026-06-20',
        updatedAt: '2026-06-20',
      } as const,
    },
  },
  COMMON: {
    VIEW_ALL: {
      id: 'UI_MERCHANT_COMMON_VIEW_ALL',
      path: 'merchant.common.view-all',
      description: 'View all button text',
      category: 'action',
      feature: 'merchant',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
} as const;
