export const ONBOARDING = {
  ONBOARDING_PAGE: {
    CONTAINER: {
uuid: 'd6b7547e-ac71-580f-b9f0-44bc889302ad',
      id: 'UI_ONBOARDING_CONTAINER',
      path: 'onboarding.onboarding-page.display.container',
      lifecycle: 'active',
      description: 'Onboarding page container',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    SIDEBAR: {
uuid: 'b38d19cd-0d3c-549c-a0d3-eeb3761c9cf2',
      id: 'UI_ONBOARDING_SIDEBAR',
      path: 'onboarding.onboarding-page.display.sidebar',
      lifecycle: 'active',
      description: 'Onboarding sidebar navigation',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    STEP_ITEM: {
uuid: '47613d21-3758-51b8-a749-261b06170c82',
      id: 'UI_ONBOARDING_STEP_ITEM',
      path: 'onboarding.onboarding-page.display.step-item',
      lifecycle: 'active',
      description: 'Onboarding step list item',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    FORM: {
uuid: 'e17cce01-cabe-529e-a01e-c5f3fd424348',
      id: 'UI_ONBOARDING_FORM',
      path: 'onboarding.onboarding-page.form.form',
      lifecycle: 'active',
      description: 'Onboarding form container',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    NEXT_BUTTON: {
uuid: '7b7da5ff-b5e5-512a-a70a-9b85146175a0',
      id: 'UI_ONBOARDING_NEXT_BUTTON',
      path: 'onboarding.onboarding-page.actions.next-button',
      lifecycle: 'active',
      description: 'Next step button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    PREV_BUTTON: {
uuid: '0f7d89fb-cbf5-551e-aded-98e5ee76c500',
      id: 'UI_ONBOARDING_PREV_BUTTON',
      path: 'onboarding.onboarding-page.actions.prev-button',
      lifecycle: 'active',
      description: 'Previous step button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
    COMPLETION: {
uuid: '2b0bda3d-576e-5586-af34-2e33cfe6659c',
      id: 'UI_ONBOARDING_COMPLETION',
      path: 'onboarding.onboarding-page.display.completion',
      lifecycle: 'active',
      description: 'Onboarding completion screen',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
} as const,
  },
  WELCOME: {
    TITLE: {
uuid: '72b8d12c-c34b-5865-a2cc-6b7641bfe2e7',
      id: 'UI_ONBOARDING_WELCOME_TITLE',
      path: 'onboarding.welcome.display.title',
      lifecycle: 'active',
      description: 'Welcome step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: '3b90fdfc-ebfb-5dbd-a89d-b0ea0ef66423',
      id: 'UI_ONBOARDING_WELCOME_DESCRIPTION',
      path: 'onboarding.welcome.display.description',
      lifecycle: 'active',
      description: 'Welcome step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    GET_STARTED_BUTTON: {
uuid: '1f909260-c21d-5311-b7e5-a23a7713e20b',
      id: 'UI_ONBOARDING_WELCOME_GET_STARTED',
      path: 'onboarding.welcome.actions.get-started',
      lifecycle: 'active',
      description: 'Get started button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  STORE_INFO: {
    TITLE: {
uuid: '3129985c-b767-5667-adc5-788206ac1ee5',
      id: 'UI_ONBOARDING_STORE_INFO_TITLE',
      path: 'onboarding.store-info.display.title',
      lifecycle: 'active',
      description: 'Store info step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'ffdfccec-a5c3-5ba3-8dd8-cddefe22e03d',
      id: 'UI_ONBOARDING_STORE_INFO_DESCRIPTION',
      path: 'onboarding.store-info.display.description',
      lifecycle: 'active',
      description: 'Store info step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_NAME_LABEL: {
uuid: '26754a17-e06f-5436-8c22-2d0d4888f304',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_NAME',
      path: 'onboarding.store-info.form.store-name',
      lifecycle: 'active',
      description: 'Store name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_NAME_PLACEHOLDER: {
uuid: '4599b93d-aa32-56b8-b74b-b52324cf660e',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_NAME_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-name-placeholder',
      lifecycle: 'active',
      description: 'Store name placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_URL_LABEL: {
uuid: '897d6b55-8220-5d2e-ab13-acdfe61792c0',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_URL',
      path: 'onboarding.store-info.form.store-url',
      lifecycle: 'active',
      description: 'Store URL label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_URL_PLACEHOLDER: {
uuid: '288e5c1b-4520-5a40-ac29-43f531e85fd2',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_URL_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-url-placeholder',
      lifecycle: 'active',
      description: 'Store URL placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_LABEL: {
uuid: '07617834-f66e-59a1-aa8f-f5e67cace15b',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_CATEGORY',
      path: 'onboarding.store-info.form.store-category',
      lifecycle: 'active',
      description: 'Store category label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_PLACEHOLDER: {
uuid: '1753ba5e-b58b-5d6f-b7bc-0388b606fae9',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_CATEGORY_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-category-placeholder',
      lifecycle: 'active',
      description: 'Store category placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_FASHION: {
uuid: '92ec859d-05ea-5e10-8122-ea1336334236',
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_FASHION',
      path: 'onboarding.store-info.form.category-fashion',
      lifecycle: 'active',
      description: 'Fashion & Apparel category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_ELECTRONICS: {
uuid: '04135952-69ae-56cf-b0a7-0f689cba1fdd',
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_ELECTRONICS',
      path: 'onboarding.store-info.form.category-electronics',
      lifecycle: 'active',
      description: 'Electronics category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_HOME: {
uuid: '3251ee2c-30d7-5d13-895e-22fafe548d01',
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_HOME',
      path: 'onboarding.store-info.form.category-home',
      lifecycle: 'active',
      description: 'Home & Garden category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_BEAUTY: {
uuid: '69ab0b07-3351-530c-80aa-b96d9b40dd0a',
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_BEAUTY',
      path: 'onboarding.store-info.form.category-beauty',
      lifecycle: 'active',
      description: 'Beauty & Personal Care category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_SPORTS: {
uuid: '0e845bec-7113-538f-9166-196e4f7b7fe9',
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_SPORTS',
      path: 'onboarding.store-info.form.category-sports',
      lifecycle: 'active',
      description: 'Sports & Outdoors category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_CATEGORY_OTHER: {
uuid: '9f7717b3-9d2b-5536-a798-9319f3fe4c4c',
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_OTHER',
      path: 'onboarding.store-info.form.category-other',
      lifecycle: 'active',
      description: 'Other category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_DESCRIPTION_LABEL: {
uuid: 'a0c29276-83b7-5639-8a60-85f01b6c4ccb',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_DESCRIPTION',
      path: 'onboarding.store-info.form.store-description',
      lifecycle: 'active',
      description: 'Store description label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_DESCRIPTION_PLACEHOLDER: {
uuid: '9712e5f8-fbbb-5dd7-bc07-0de210bc4739',
      id: 'UI_ONBOARDING_STORE_INFO_STORE_DESCRIPTION_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-description-placeholder',
      lifecycle: 'active',
      description: 'Store description placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  BUSINESS_DETAILS: {
    TITLE: {
uuid: 'f6c267dd-1bba-5926-b22f-a6a3f7fbf38c',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TITLE',
      path: 'onboarding.business-details.display.title',
      lifecycle: 'active',
      description: 'Business details step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: '1be51cf5-e82c-539a-b2a0-abe753a953dc',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_DESCRIPTION',
      path: 'onboarding.business-details.display.description',
      lifecycle: 'active',
      description: 'Business details step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    BUSINESS_NAME_LABEL: {
uuid: 'c2ebb2a3-7f45-5c3c-bf94-908da9a94f5e',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_NAME',
      path: 'onboarding.business-details.form.business-name',
      lifecycle: 'active',
      description: 'Business name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    BUSINESS_NAME_PLACEHOLDER: {
uuid: '58ec8401-febf-59b6-85b8-c0a3111d1250',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_NAME_PLACEHOLDER',
      path: 'onboarding.business-details.form.business-name-placeholder',
      lifecycle: 'active',
      description: 'Business name placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    BUSINESS_TYPE_LABEL: {
uuid: 'bb4ea648-0994-5207-9042-04ce27aaa5f5',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_TYPE',
      path: 'onboarding.business-details.form.business-type',
      lifecycle: 'active',
      description: 'Business type label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    BUSINESS_TYPE_PLACEHOLDER: {
uuid: '97d04d0a-bc13-5b8d-8ffb-30e02538a63b',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_TYPE_PLACEHOLDER',
      path: 'onboarding.business-details.form.business-type-placeholder',
      lifecycle: 'active',
      description: 'Business type placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TYPE_SOLE_PROPRIETORSHIP: {
uuid: 'a64f817a-be3e-512f-98e9-ebacd18f69c9',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_SOLE_PROPRIETORSHIP',
      path: 'onboarding.business-details.form.type-sole-proprietorship',
      lifecycle: 'active',
      description: 'Sole Proprietorship business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TYPE_LLC: {
uuid: '9a026393-878b-58f2-a79b-bb75353faa74',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_LLC',
      path: 'onboarding.business-details.form.type-llc',
      lifecycle: 'active',
      description: 'LLC business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TYPE_CORPORATION: {
uuid: 'e96da820-1809-5c49-ac36-d3e2a602f35b',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_CORPORATION',
      path: 'onboarding.business-details.form.type-corporation',
      lifecycle: 'active',
      description: 'Corporation business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TYPE_PARTNERSHIP: {
uuid: '915e8a66-d98e-5bb3-98a8-d8bcb7481919',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_PARTNERSHIP',
      path: 'onboarding.business-details.form.type-partnership',
      lifecycle: 'active',
      description: 'Partnership business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TYPE_OTHER: {
uuid: '9e259cd0-4962-5e35-9114-5b0ee3fb6f9b',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_OTHER',
      path: 'onboarding.business-details.form.type-other',
      lifecycle: 'active',
      description: 'Other business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_NUMBER_LABEL: {
uuid: 'fd83ca5c-e2e0-5687-96a9-fb42db0af1a5',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_REGISTRATION_NUMBER',
      path: 'onboarding.business-details.form.registration-number',
      lifecycle: 'active',
      description: 'Registration number label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REGISTRATION_NUMBER_PLACEHOLDER: {
uuid: '438d9656-8b98-580d-b3c4-65fc4c9e440b',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_REGISTRATION_NUMBER_PLACEHOLDER',
      path: 'onboarding.business-details.form.registration-number-placeholder',
      lifecycle: 'active',
      description: 'Registration number placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    YEAR_FOUNDED_LABEL: {
uuid: '9f75fa76-ff4f-53df-9c44-e1644c7fa92d',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_YEAR_FOUNDED',
      path: 'onboarding.business-details.form.year-founded',
      lifecycle: 'active',
      description: 'Year founded label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    YEAR_FOUNDED_PLACEHOLDER: {
uuid: 'b4e9cdf8-3ec2-5af5-ac6f-956e4e063843',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_YEAR_FOUNDED_PLACEHOLDER',
      path: 'onboarding.business-details.form.year-founded-placeholder',
      lifecycle: 'active',
      description: 'Year founded placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    EMPLOYEE_COUNT_LABEL: {
uuid: '88824435-2233-51fc-834a-d8fb79114d7a',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_EMPLOYEE_COUNT',
      path: 'onboarding.business-details.form.employee-count',
      lifecycle: 'active',
      description: 'Employee count label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    EMPLOYEE_COUNT_PLACEHOLDER: {
uuid: '74eb617b-2910-5d76-9a85-f8098280a2e4',
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_EMPLOYEE_COUNT_PLACEHOLDER',
      path: 'onboarding.business-details.form.employee-count-placeholder',
      lifecycle: 'active',
      description: 'Employee count placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  IDENTITY_VERIFICATION: {
    TITLE: {
uuid: '46b41724-bd53-5189-b5e3-44c26253fadf',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_TITLE',
      path: 'onboarding.identity-verification.display.title',
      lifecycle: 'active',
      description: 'Identity verification step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: '898aa574-8d2b-5269-97b1-f31e09a21e3b',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_DESCRIPTION',
      path: 'onboarding.identity-verification.display.description',
      lifecycle: 'active',
      description: 'Identity verification step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FIRST_NAME_LABEL: {
uuid: 'f8964d76-d57c-55c1-a5f2-bfac37b58cff',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_FIRST_NAME',
      path: 'onboarding.identity-verification.form.first-name',
      lifecycle: 'active',
      description: 'First name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LAST_NAME_LABEL: {
uuid: 'cdbd8bb0-aab4-5d59-a469-772a93946eab',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_LAST_NAME',
      path: 'onboarding.identity-verification.form.last-name',
      lifecycle: 'active',
      description: 'Last name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DATE_OF_BIRTH_LABEL: {
uuid: '23e994b8-f2a2-597d-9b31-d286a1f51b2b',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_DATE_OF_BIRTH',
      path: 'onboarding.identity-verification.form.date-of-birth',
      lifecycle: 'active',
      description: 'Date of birth label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    EMAIL_LABEL: {
uuid: '655df5ee-dbb3-5147-84a1-600c547035e5',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_EMAIL',
      path: 'onboarding.identity-verification.form.email',
      lifecycle: 'active',
      description: 'Email label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PHONE_LABEL: {
uuid: 'a56ec842-1bfa-512f-bb66-4db08a5850f5',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_PHONE',
      path: 'onboarding.identity-verification.form.phone',
      lifecycle: 'active',
      description: 'Phone label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ID_TYPE_LABEL: {
uuid: 'ea08d878-3a33-5905-bc0f-a36228cf1667',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE',
      path: 'onboarding.identity-verification.form.id-type',
      lifecycle: 'active',
      description: 'ID type label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ID_TYPE_PLACEHOLDER: {
uuid: '88166d5a-2e23-536b-8303-cd9cfd000f6d',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_PLACEHOLDER',
      path: 'onboarding.identity-verification.form.id-type-placeholder',
      lifecycle: 'active',
      description: 'ID type placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ID_TYPE_PASSPORT: {
uuid: '27d04003-1cab-5048-9bdc-89e59431f6e2',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_PASSPORT',
      path: 'onboarding.identity-verification.form.id-type-passport',
      lifecycle: 'active',
      description: 'Passport ID type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ID_TYPE_DRIVER_LICENSE: {
uuid: 'ea152d03-a94d-57dc-9351-be094e11ddda',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_DRIVER_LICENSE',
      path: 'onboarding.identity-verification.form.id-type-driver-license',
      lifecycle: 'active',
      description: "Driver's License ID type",
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ID_TYPE_NATIONAL_ID: {
uuid: '2cd408e5-e9d9-5f40-a95d-3e0b02be5e9e',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_NATIONAL_ID',
      path: 'onboarding.identity-verification.form.id-type-national-id',
      lifecycle: 'active',
      description: 'National ID type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ID_NUMBER_LABEL: {
uuid: 'b1431a81-3ff5-5248-af6b-167f6242d9de',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_NUMBER',
      path: 'onboarding.identity-verification.form.id-number',
      lifecycle: 'active',
      description: 'ID number label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    UPLOAD_ID_LABEL: {
uuid: '99758225-0e2e-599c-b9e5-7a83cfc3a312',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_UPLOAD_ID',
      path: 'onboarding.identity-verification.form.upload-id',
      lifecycle: 'active',
      description: 'Upload ID label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    UPLOAD_ID_SUBTITLE: {
uuid: '4564ae1a-1ce5-5dc5-b9fb-da60915ef57b',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_UPLOAD_ID_SUBTITLE',
      path: 'onboarding.identity-verification.form.upload-id-subtitle',
      lifecycle: 'active',
      description: 'Upload ID subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CHOOSE_FILE_BUTTON: {
uuid: '6cfb0492-8ea3-5c4b-afc0-3458b8eab139',
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_CHOOSE_FILE',
      path: 'onboarding.identity-verification.actions.choose-file',
      lifecycle: 'active',
      description: 'Choose file button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  PRODUCTS: {
    TITLE: {
uuid: '32ccb4aa-2bf1-5075-950d-da5c2cfc7eff',
      id: 'UI_ONBOARDING_PRODUCTS_TITLE',
      path: 'onboarding.products.display.title',
      lifecycle: 'active',
      description: 'Products step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'a06bc006-ed94-53cd-8e91-feec325512db',
      id: 'UI_ONBOARDING_PRODUCTS_DESCRIPTION',
      path: 'onboarding.products.display.description',
      lifecycle: 'active',
      description: 'Products step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DIGITAL_PRODUCTS_LABEL: {
uuid: 'e8d2f469-1261-592c-b6af-96c7ff42e82a',
      id: 'UI_ONBOARDING_PRODUCTS_DIGITAL_PRODUCTS',
      path: 'onboarding.products.form.digital-products',
      lifecycle: 'active',
      description: 'Digital products label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DIGITAL_PRODUCTS_SUBTITLE: {
uuid: 'e51bfeb6-b087-5915-b636-888c506e7533',
      id: 'UI_ONBOARDING_PRODUCTS_DIGITAL_PRODUCTS_SUBTITLE',
      path: 'onboarding.products.form.digital-products-subtitle',
      lifecycle: 'active',
      description: 'Digital products subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PHYSICAL_PRODUCTS_LABEL: {
uuid: '396c7966-f3b1-5331-8f14-f5dc6fb2dccf',
      id: 'UI_ONBOARDING_PRODUCTS_PHYSICAL_PRODUCTS',
      path: 'onboarding.products.form.physical-products',
      lifecycle: 'active',
      description: 'Physical products label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PHYSICAL_PRODUCTS_SUBTITLE: {
uuid: 'bcbe7a87-aea2-5bbe-b975-f8057c0cb154',
      id: 'UI_ONBOARDING_PRODUCTS_PHYSICAL_PRODUCTS_SUBTITLE',
      path: 'onboarding.products.form.physical-products-subtitle',
      lifecycle: 'active',
      description: 'Physical products subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PRODUCT_CATALOG_LABEL: {
uuid: '19f1c42b-f289-5328-9b93-44b12de3d496',
      id: 'UI_ONBOARDING_PRODUCTS_PRODUCT_CATALOG',
      path: 'onboarding.products.form.product-catalog',
      lifecycle: 'active',
      description: 'Product catalog label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ADD_PRODUCTS_LATER_BUTTON: {
uuid: '45f0124d-6d01-5d00-8d8a-6dd795dc0fea',
      id: 'UI_ONBOARDING_PRODUCTS_ADD_PRODUCTS_LATER',
      path: 'onboarding.products.actions.add-products-later',
      lifecycle: 'active',
      description: 'Add products later button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  SHIPPING: {
    TITLE: {
uuid: '6d2e6ed0-585b-58c7-be66-d57e550b97c5',
      id: 'UI_ONBOARDING_SHIPPING_TITLE',
      path: 'onboarding.shipping.display.title',
      lifecycle: 'active',
      description: 'Shipping step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: '02f562b8-7824-5203-8a2b-27d24c1b449d',
      id: 'UI_ONBOARDING_SHIPPING_DESCRIPTION',
      path: 'onboarding.shipping.display.description',
      lifecycle: 'active',
      description: 'Shipping step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    COUNTRY_LABEL: {
uuid: '15be52d4-3982-528f-ae23-7ed2975fd50d',
      id: 'UI_ONBOARDING_SHIPPING_COUNTRY',
      path: 'onboarding.shipping.form.country',
      lifecycle: 'active',
      description: 'Country label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    COUNTRY_PLACEHOLDER: {
uuid: 'cadc60fe-faa5-5d85-acf5-0c2cb798dd23',
      id: 'UI_ONBOARDING_SHIPPING_COUNTRY_PLACEHOLDER',
      path: 'onboarding.shipping.form.country-placeholder',
      lifecycle: 'active',
      description: 'Country placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CITY_LABEL: {
uuid: 'd725be01-ab31-5be0-899f-d0e7fe185cde',
      id: 'UI_ONBOARDING_SHIPPING_CITY',
      path: 'onboarding.shipping.form.city',
      lifecycle: 'active',
      description: 'City label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CITY_PLACEHOLDER: {
uuid: 'c942e7cf-f404-5772-948b-c1edb246a7d0',
      id: 'UI_ONBOARDING_SHIPPING_CITY_PLACEHOLDER',
      path: 'onboarding.shipping.form.city-placeholder',
      lifecycle: 'active',
      description: 'City placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    POSTAL_CODE_LABEL: {
uuid: '11e5a253-8cd1-5248-a2af-eb75d94ed6b2',
      id: 'UI_ONBOARDING_SHIPPING_POSTAL_CODE',
      path: 'onboarding.shipping.form.postal-code',
      lifecycle: 'active',
      description: 'Postal code label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    POSTAL_CODE_PLACEHOLDER: {
uuid: 'eaca5411-ed13-590a-81a2-f3bb0788770c',
      id: 'UI_ONBOARDING_SHIPPING_POSTAL_CODE_PLACEHOLDER',
      path: 'onboarding.shipping.form.postal-code-placeholder',
      lifecycle: 'active',
      description: 'Postal code placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ADDRESS_LABEL: {
uuid: '2466fcae-a0a4-566d-a174-8a487c364e17',
      id: 'UI_ONBOARDING_SHIPPING_ADDRESS',
      path: 'onboarding.shipping.form.address',
      lifecycle: 'active',
      description: 'Address label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    ADDRESS_PLACEHOLDER: {
uuid: '2d69b1c0-b344-5c83-a8d0-f10a514b7d3d',
      id: 'UI_ONBOARDING_SHIPPING_ADDRESS_PLACEHOLDER',
      path: 'onboarding.shipping.form.address-placeholder',
      lifecycle: 'active',
      description: 'Address placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    OFFER_FREE_SHIPPING_LABEL: {
uuid: '33092ff6-1fa7-5381-8808-314021034a33',
      id: 'UI_ONBOARDING_SHIPPING_OFFER_FREE_SHIPPING',
      path: 'onboarding.shipping.form.offer-free-shipping',
      lifecycle: 'active',
      description: 'Offer free shipping label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  PAYMENTS: {
    TITLE: {
uuid: '58000435-804c-5966-87d2-ba8739e65ca0',
      id: 'UI_ONBOARDING_PAYMENTS_TITLE',
      path: 'onboarding.payments.display.title',
      lifecycle: 'active',
      description: 'Payments step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'd32f408d-6854-5fda-8fcb-c8c3599c4888',
      id: 'UI_ONBOARDING_PAYMENTS_DESCRIPTION',
      path: 'onboarding.payments.display.description',
      lifecycle: 'active',
      description: 'Payments step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PAYMENT_METHODS_LABEL: {
uuid: '90d2d1f8-3014-5e83-a62f-21528b692df5',
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHODS',
      path: 'onboarding.payments.form.payment-methods',
      lifecycle: 'active',
      description: 'Payment methods label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PAYMENT_METHOD_CREDIT_CARD: {
uuid: '787c89e8-b362-5a5d-856c-902afa95c8af',
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_CREDIT_CARD',
      path: 'onboarding.payments.form.payment-method-credit-card',
      lifecycle: 'active',
      description: 'Credit Card payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PAYMENT_METHOD_DEBIT_CARD: {
uuid: 'd5a88c01-891f-529e-ac75-7cbbe2c1f3e8',
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_DEBIT_CARD',
      path: 'onboarding.payments.form.payment-method-debit-card',
      lifecycle: 'active',
      description: 'Debit Card payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PAYMENT_METHOD_PAYPAL: {
uuid: '7165ef7b-3065-57a8-b387-e7b5ce78b95a',
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_PAYPAL',
      path: 'onboarding.payments.form.payment-method-paypal',
      lifecycle: 'active',
      description: 'PayPal payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PAYMENT_METHOD_BANK_TRANSFER: {
uuid: 'fc7cb50c-4d6f-5755-8096-0276211b1fcf',
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_BANK_TRANSFER',
      path: 'onboarding.payments.form.payment-method-bank-transfer',
      lifecycle: 'active',
      description: 'Bank Transfer payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CURRENCY_LABEL: {
uuid: 'a9a539f2-39cf-5b3b-9c30-2b044f301f2d',
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY',
      path: 'onboarding.payments.form.currency',
      lifecycle: 'active',
      description: 'Currency label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CURRENCY_USD: {
uuid: 'fb110471-01dd-5534-9c35-853bbf34064e',
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_USD',
      path: 'onboarding.payments.form.currency-usd',
      lifecycle: 'active',
      description: 'USD currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CURRENCY_EUR: {
uuid: 'd1eab2f1-21cf-5ff8-bc0a-a92b2eb70232',
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_EUR',
      path: 'onboarding.payments.form.currency-eur',
      lifecycle: 'active',
      description: 'EUR currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CURRENCY_GBP: {
uuid: 'f18dbed2-bb74-549b-81b3-b04091f2c259',
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_GBP',
      path: 'onboarding.payments.form.currency-gbp',
      lifecycle: 'active',
      description: 'GBP currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CURRENCY_CAD: {
uuid: '51e9b979-afc9-5510-855d-99b346522b6a',
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_CAD',
      path: 'onboarding.payments.form.currency-cad',
      lifecycle: 'active',
      description: 'CAD currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    CURRENCY_AUD: {
uuid: '49251b43-b9cb-57c6-bfc0-f9d1cd2b364c',
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_AUD',
      path: 'onboarding.payments.form.currency-aud',
      lifecycle: 'active',
      description: 'AUD currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  POLICIES: {
    TITLE: {
uuid: '762f16e4-1138-579f-9f8e-83c27fdf96dd',
      id: 'UI_ONBOARDING_POLICIES_TITLE',
      path: 'onboarding.policies.display.title',
      lifecycle: 'active',
      description: 'Policies step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'eb2a3834-c69d-5dfb-840b-3a1e3ca0d3f5',
      id: 'UI_ONBOARDING_POLICIES_DESCRIPTION',
      path: 'onboarding.policies.display.description',
      lifecycle: 'active',
      description: 'Policies step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    RETURN_POLICY_LABEL: {
uuid: 'cf35f363-403d-55b0-9521-aa21ab61b7f6',
      id: 'UI_ONBOARDING_POLICIES_RETURN_POLICY',
      path: 'onboarding.policies.form.return-policy',
      lifecycle: 'active',
      description: 'Return policy label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    RETURN_POLICY_PLACEHOLDER: {
uuid: '2362c7c1-5a14-53a2-ac06-95ef41f11378',
      id: 'UI_ONBOARDING_POLICIES_RETURN_POLICY_PLACEHOLDER',
      path: 'onboarding.policies.form.return-policy-placeholder',
      lifecycle: 'active',
      description: 'Return policy placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REFUND_POLICY_LABEL: {
uuid: '4f28d3ef-3f00-52d8-81dd-5455cebdaa8e',
      id: 'UI_ONBOARDING_POLICIES_REFUND_POLICY',
      path: 'onboarding.policies.form.refund-policy',
      lifecycle: 'active',
      description: 'Refund policy label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    REFUND_POLICY_PLACEHOLDER: {
uuid: '0c9f31e5-9bb0-5aba-94d9-f51b63d7b1a0',
      id: 'UI_ONBOARDING_POLICIES_REFUND_POLICY_PLACEHOLDER',
      path: 'onboarding.policies.form.refund-policy-placeholder',
      lifecycle: 'active',
      description: 'Refund policy placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PRIVACY_POLICY_LABEL: {
uuid: '884c2151-074e-5c8c-8ceb-242b8fb4e27e',
      id: 'UI_ONBOARDING_POLICIES_PRIVACY_POLICY',
      path: 'onboarding.policies.form.privacy-policy',
      lifecycle: 'active',
      description: 'Privacy policy label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PRIVACY_POLICY_PLACEHOLDER: {
uuid: '6829767f-498c-5ba6-94b9-5599fd4017f0',
      id: 'UI_ONBOARDING_POLICIES_PRIVACY_POLICY_PLACEHOLDER',
      path: 'onboarding.policies.form.privacy-policy-placeholder',
      lifecycle: 'active',
      description: 'Privacy policy placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TERMS_OF_SERVICE_LABEL: {
uuid: '208c242f-730a-548a-8538-5a99bff40474',
      id: 'UI_ONBOARDING_POLICIES_TERMS_OF_SERVICE',
      path: 'onboarding.policies.form.terms-of-service',
      lifecycle: 'active',
      description: 'Terms of service label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TERMS_OF_SERVICE_PLACEHOLDER: {
uuid: 'aa401425-913d-57d4-9094-c2b7ac1f0b9e',
      id: 'UI_ONBOARDING_POLICIES_TERMS_OF_SERVICE_PLACEHOLDER',
      path: 'onboarding.policies.form.terms-of-service-placeholder',
      lifecycle: 'active',
      description: 'Terms of service placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  BRANDING: {
    TITLE: {
uuid: 'e1df822d-5de4-5d5a-8230-c3638318c148',
      id: 'UI_ONBOARDING_BRANDING_TITLE',
      path: 'onboarding.branding.display.title',
      lifecycle: 'active',
      description: 'Branding step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'ad7d66c5-567f-54b6-8bff-1fa793c9c970',
      id: 'UI_ONBOARDING_BRANDING_DESCRIPTION',
      path: 'onboarding.branding.display.description',
      lifecycle: 'active',
      description: 'Branding step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_TAGLINE_LABEL: {
uuid: 'b685eed7-a918-500c-8047-322dcc85087a',
      id: 'UI_ONBOARDING_BRANDING_STORE_TAGLINE',
      path: 'onboarding.branding.form.store-tagline',
      lifecycle: 'active',
      description: 'Store tagline label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    STORE_TAGLINE_PLACEHOLDER: {
uuid: '1d2d07fd-9ac5-5726-af27-714361776de4',
      id: 'UI_ONBOARDING_BRANDING_STORE_TAGLINE_PLACEHOLDER',
      path: 'onboarding.branding.form.store-tagline-placeholder',
      lifecycle: 'active',
      description: 'Store tagline placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGO_LABEL: {
uuid: '00ca19f6-9e89-5903-98dd-66d4df119b51',
      id: 'UI_ONBOARDING_BRANDING_LOGO',
      path: 'onboarding.branding.form.logo',
      lifecycle: 'active',
      description: 'Logo label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    LOGO_SUBTITLE: {
uuid: '8855efd7-583a-5de0-b584-6a1d346b111e',
      id: 'UI_ONBOARDING_BRANDING_LOGO_SUBTITLE',
      path: 'onboarding.branding.form.logo-subtitle',
      lifecycle: 'active',
      description: 'Logo subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    UPLOAD_BUTTON: {
uuid: '142b2148-2c16-5efd-840a-b14676aad003',
      id: 'UI_ONBOARDING_BRANDING_UPLOAD',
      path: 'onboarding.branding.actions.upload',
      lifecycle: 'active',
      description: 'Upload button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PRIMARY_COLOR_LABEL: {
uuid: '65950dd1-f90d-5fce-a57e-2e0b5b91dae0',
      id: 'UI_ONBOARDING_BRANDING_PRIMARY_COLOR',
      path: 'onboarding.branding.form.primary-color',
      lifecycle: 'active',
      description: 'Primary color label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PRIMARY_COLOR_SUBTITLE: {
uuid: '2d10c09e-f691-546f-8a8a-c2a8106e0841',
      id: 'UI_ONBOARDING_BRANDING_PRIMARY_COLOR_SUBTITLE',
      path: 'onboarding.branding.form.primary-color-subtitle',
      lifecycle: 'active',
      description: 'Primary color subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  PREFERENCES: {
    TITLE: {
uuid: '10301ad6-8429-5b7f-bd86-6044620871ed',
      id: 'UI_ONBOARDING_PREFERENCES_TITLE',
      path: 'onboarding.preferences.display.title',
      lifecycle: 'active',
      description: 'Preferences step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'afb09eca-3732-5b5b-bef6-17948aab1c85',
      id: 'UI_ONBOARDING_PREFERENCES_DESCRIPTION',
      path: 'onboarding.preferences.display.description',
      lifecycle: 'active',
      description: 'Preferences step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TIMEZONE_LABEL: {
uuid: '3f134193-e62f-5fa8-b84f-f9c98de95bce',
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE',
      path: 'onboarding.preferences.form.timezone',
      lifecycle: 'active',
      description: 'Timezone label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NOTIFICATIONS_LABEL: {
uuid: 'e6dbca44-3828-5201-bf3b-2ad6e82747db',
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATIONS',
      path: 'onboarding.preferences.form.notifications',
      lifecycle: 'active',
      description: 'Notifications label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NOTIFICATION_ORDER: {
uuid: '7cb64318-d3a2-55c7-81fc-1412d3820e61',
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_ORDER',
      path: 'onboarding.preferences.form.notification-order',
      lifecycle: 'active',
      description: 'Order notifications',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NOTIFICATION_MARKETING: {
uuid: '58d86aa0-71a2-539f-86c6-d51e3dcac6fd',
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_MARKETING',
      path: 'onboarding.preferences.form.notification-marketing',
      lifecycle: 'active',
      description: 'Marketing emails',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NOTIFICATION_SYSTEM: {
uuid: '7cd02fa1-0b3a-560c-a92e-a2234ef39d6e',
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_SYSTEM',
      path: 'onboarding.preferences.form.notification-system',
      lifecycle: 'active',
      description: 'System updates',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NOTIFICATION_WEEKLY_REPORT: {
uuid: '77e1c3be-e5ca-5f0d-a42d-e53c82563d2b',
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_WEEKLY_REPORT',
      path: 'onboarding.preferences.form.notification-weekly-report',
      lifecycle: 'active',
      description: 'Weekly performance report',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TIMEZONE_ET: {
uuid: 'b98567a5-7732-55ec-8661-76e3c61293d2',
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_ET',
      path: 'onboarding.preferences.form.timezone-et',
      lifecycle: 'active',
      description: 'Eastern Time (ET)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TIMEZONE_CT: {
uuid: 'b5946be3-7b41-56c2-8a52-72a58204b13c',
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_CT',
      path: 'onboarding.preferences.form.timezone-ct',
      lifecycle: 'active',
      description: 'Central Time (CT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TIMEZONE_MT: {
uuid: '8998a3cd-4745-5214-9675-17cb962762fa',
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_MT',
      path: 'onboarding.preferences.form.timezone-mt',
      lifecycle: 'active',
      description: 'Mountain Time (MT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TIMEZONE_PT: {
uuid: '83b470d8-4d16-5d51-887b-bd86d432fd87',
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_PT',
      path: 'onboarding.preferences.form.timezone-pt',
      lifecycle: 'active',
      description: 'Pacific Time (PT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TIMEZONE_GMT: {
uuid: 'e4a32f78-e78f-59cf-a525-dd467d741945',
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_GMT',
      path: 'onboarding.preferences.form.timezone-gmt',
      lifecycle: 'active',
      description: 'London (GMT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TIMEZONE_CET: {
uuid: '897c399c-dc67-5ee3-b2ef-60a2db3e1a91',
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_CET',
      path: 'onboarding.preferences.form.timezone-cet',
      lifecycle: 'active',
      description: 'Paris (CET)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  TAX_INFO: {
    TITLE: {
uuid: 'f40e4a2c-ee02-5ef3-83b0-be0edc778945',
      id: 'UI_ONBOARDING_TAX_INFO_TITLE',
      path: 'onboarding.tax-info.display.title',
      lifecycle: 'active',
      description: 'Tax info step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'ac72aefc-a125-5777-8289-c462599baa1d',
      id: 'UI_ONBOARDING_TAX_INFO_DESCRIPTION',
      path: 'onboarding.tax-info.display.description',
      lifecycle: 'active',
      description: 'Tax info step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TAX_ID_LABEL: {
uuid: '4369ee71-2e52-524c-b51b-37439a95e39e',
      id: 'UI_ONBOARDING_TAX_INFO_TAX_ID',
      path: 'onboarding.tax-info.form.tax-id',
      lifecycle: 'active',
      description: 'Tax ID/VAT Number label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    TAX_ID_PLACEHOLDER: {
uuid: '4eaaeb1f-b3e8-5c66-acec-caa1599bef90',
      id: 'UI_ONBOARDING_TAX_INFO_TAX_ID_PLACEHOLDER',
      path: 'onboarding.tax-info.form.tax-id-placeholder',
      lifecycle: 'active',
      description: 'Tax ID placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  MARKETING: {
    TITLE: {
uuid: '604717cc-1629-5759-b399-ab82e4d2d31f',
      id: 'UI_ONBOARDING_MARKETING_TITLE',
      path: 'onboarding.marketing.display.title',
      lifecycle: 'active',
      description: 'Marketing step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'e57bc81c-0232-5079-a573-68dea687cd7b',
      id: 'UI_ONBOARDING_MARKETING_DESCRIPTION',
      path: 'onboarding.marketing.display.description',
      lifecycle: 'active',
      description: 'Marketing step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    EMAIL_MARKETING_LABEL: {
uuid: '0a1a52d9-a82a-5b48-be18-f7430de74522',
      id: 'UI_ONBOARDING_MARKETING_EMAIL_MARKETING',
      path: 'onboarding.marketing.form.email-marketing',
      lifecycle: 'active',
      description: 'Email marketing label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    EMAIL_MARKETING_SUBTITLE: {
uuid: 'e8c63c66-4a75-5229-8767-da20cd04be0b',
      id: 'UI_ONBOARDING_MARKETING_EMAIL_MARKETING_SUBTITLE',
      path: 'onboarding.marketing.form.email-marketing-subtitle',
      lifecycle: 'active',
      description: 'Email marketing subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SOCIAL_SHARING_LABEL: {
uuid: 'caaeb4f2-cd02-5509-81cb-0af4789089db',
      id: 'UI_ONBOARDING_MARKETING_SOCIAL_SHARING',
      path: 'onboarding.marketing.form.social-sharing',
      lifecycle: 'active',
      description: 'Social sharing label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    SOCIAL_SHARING_SUBTITLE: {
uuid: 'fc56149b-9ec7-5796-8a31-337de8b71478',
      id: 'UI_ONBOARDING_MARKETING_SOCIAL_SHARING_SUBTITLE',
      path: 'onboarding.marketing.form.social-sharing-subtitle',
      lifecycle: 'active',
      description: 'Social sharing subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PRODUCT_REVIEWS_LABEL: {
uuid: '821e92bb-2a4c-5a22-a8ef-626903899510',
      id: 'UI_ONBOARDING_MARKETING_PRODUCT_REVIEWS',
      path: 'onboarding.marketing.form.product-reviews',
      lifecycle: 'active',
      description: 'Product reviews label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    PRODUCT_REVIEWS_SUBTITLE: {
uuid: 'ae034398-6540-5d0b-8298-68b66e6de7b1',
      id: 'UI_ONBOARDING_MARKETING_PRODUCT_REVIEWS_SUBTITLE',
      path: 'onboarding.marketing.form.product-reviews-subtitle',
      lifecycle: 'active',
      description: 'Product reviews subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  COMPLETION: {
    TITLE: {
uuid: '10c544d0-9831-54db-beec-04d261f54f75',
      id: 'UI_ONBOARDING_COMPLETION_TITLE',
      path: 'onboarding.completion.display.title',
      lifecycle: 'active',
      description: 'Completion step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    DESCRIPTION: {
uuid: 'b72588b8-4cd7-5dbf-85b8-4aee7f829acd',
      id: 'UI_ONBOARDING_COMPLETION_DESCRIPTION',
      path: 'onboarding.completion.display.description',
      lifecycle: 'active',
      description: 'Completion step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    GO_TO_DASHBOARD_BUTTON: {
uuid: '97fc3063-cc4a-5d74-8ddc-c8b11dacbee2',
      id: 'UI_ONBOARDING_COMPLETION_GO_TO_DASHBOARD',
      path: 'onboarding.completion.actions.go-to-dashboard',
      lifecycle: 'active',
      description: 'Go to dashboard button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
  COMMON: {
    PREVIOUS_BUTTON: {
uuid: 'e0096b9a-4952-560f-80c2-6f00158fd2a5',
      id: 'UI_ONBOARDING_COMMON_PREVIOUS',
      path: 'onboarding.common.actions.previous',
      lifecycle: 'active',
      description: 'Previous button text',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    NEXT_BUTTON: {
uuid: 'a5db3656-1b5c-5617-9277-a8c07a360e51',
      id: 'UI_ONBOARDING_COMMON_NEXT',
      path: 'onboarding.common.actions.next',
      lifecycle: 'active',
      description: 'Next button text',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
    FINISH_BUTTON: {
uuid: '31a0a970-51b0-5c05-84d1-09ca4da68e4f',
      id: 'UI_ONBOARDING_COMMON_FINISH',
      path: 'onboarding.common.actions.finish',
      lifecycle: 'active',
      description: 'Finish button text',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
} as const,
  },
} as const;
