export const ONBOARDING = {
  ONBOARDING_PAGE: {
    CONTAINER: {
      id: 'UI_ONBOARDING_CONTAINER',
      path: 'onboarding.onboarding-page.display.container',
      description: 'Onboarding page container',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    SIDEBAR: {
      id: 'UI_ONBOARDING_SIDEBAR',
      path: 'onboarding.onboarding-page.display.sidebar',
      description: 'Onboarding sidebar navigation',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    STEP_ITEM: {
      id: 'UI_ONBOARDING_STEP_ITEM',
      path: 'onboarding.onboarding-page.display.step-item',
      description: 'Onboarding step list item',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    FORM: {
      id: 'UI_ONBOARDING_FORM',
      path: 'onboarding.onboarding-page.form.form',
      description: 'Onboarding form container',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    NEXT_BUTTON: {
      id: 'UI_ONBOARDING_NEXT_BUTTON',
      path: 'onboarding.onboarding-page.actions.next-button',
      description: 'Next step button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PREV_BUTTON: {
      id: 'UI_ONBOARDING_PREV_BUTTON',
      path: 'onboarding.onboarding-page.actions.prev-button',
      description: 'Previous step button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    COMPLETION: {
      id: 'UI_ONBOARDING_COMPLETION',
      path: 'onboarding.onboarding-page.display.completion',
      description: 'Onboarding completion screen',
      category: 'container',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
  },
  WELCOME: {
    TITLE: {
      id: 'UI_ONBOARDING_WELCOME_TITLE',
      path: 'onboarding.welcome.display.title',
      description: 'Welcome step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_WELCOME_DESCRIPTION',
      path: 'onboarding.welcome.display.description',
      description: 'Welcome step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    GET_STARTED_BUTTON: {
      id: 'UI_ONBOARDING_WELCOME_GET_STARTED',
      path: 'onboarding.welcome.actions.get-started',
      description: 'Get started button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  STORE_INFO: {
    TITLE: {
      id: 'UI_ONBOARDING_STORE_INFO_TITLE',
      path: 'onboarding.store-info.display.title',
      description: 'Store info step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_STORE_INFO_DESCRIPTION',
      path: 'onboarding.store-info.display.description',
      description: 'Store info step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_NAME_LABEL: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_NAME',
      path: 'onboarding.store-info.form.store-name',
      description: 'Store name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_NAME_PLACEHOLDER: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_NAME_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-name-placeholder',
      description: 'Store name placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_URL_LABEL: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_URL',
      path: 'onboarding.store-info.form.store-url',
      description: 'Store URL label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_URL_PLACEHOLDER: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_URL_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-url-placeholder',
      description: 'Store URL placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_LABEL: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_CATEGORY',
      path: 'onboarding.store-info.form.store-category',
      description: 'Store category label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_PLACEHOLDER: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_CATEGORY_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-category-placeholder',
      description: 'Store category placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_FASHION: {
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_FASHION',
      path: 'onboarding.store-info.form.category-fashion',
      description: 'Fashion & Apparel category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_ELECTRONICS: {
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_ELECTRONICS',
      path: 'onboarding.store-info.form.category-electronics',
      description: 'Electronics category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_HOME: {
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_HOME',
      path: 'onboarding.store-info.form.category-home',
      description: 'Home & Garden category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_BEAUTY: {
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_BEAUTY',
      path: 'onboarding.store-info.form.category-beauty',
      description: 'Beauty & Personal Care category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_SPORTS: {
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_SPORTS',
      path: 'onboarding.store-info.form.category-sports',
      description: 'Sports & Outdoors category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_CATEGORY_OTHER: {
      id: 'UI_ONBOARDING_STORE_INFO_CATEGORY_OTHER',
      path: 'onboarding.store-info.form.category-other',
      description: 'Other category',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_DESCRIPTION_LABEL: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_DESCRIPTION',
      path: 'onboarding.store-info.form.store-description',
      description: 'Store description label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_DESCRIPTION_PLACEHOLDER: {
      id: 'UI_ONBOARDING_STORE_INFO_STORE_DESCRIPTION_PLACEHOLDER',
      path: 'onboarding.store-info.form.store-description-placeholder',
      description: 'Store description placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  BUSINESS_DETAILS: {
    TITLE: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TITLE',
      path: 'onboarding.business-details.display.title',
      description: 'Business details step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_DESCRIPTION',
      path: 'onboarding.business-details.display.description',
      description: 'Business details step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    BUSINESS_NAME_LABEL: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_NAME',
      path: 'onboarding.business-details.form.business-name',
      description: 'Business name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    BUSINESS_NAME_PLACEHOLDER: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_NAME_PLACEHOLDER',
      path: 'onboarding.business-details.form.business-name-placeholder',
      description: 'Business name placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    BUSINESS_TYPE_LABEL: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_TYPE',
      path: 'onboarding.business-details.form.business-type',
      description: 'Business type label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    BUSINESS_TYPE_PLACEHOLDER: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_BUSINESS_TYPE_PLACEHOLDER',
      path: 'onboarding.business-details.form.business-type-placeholder',
      description: 'Business type placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TYPE_SOLE_PROPRIETORSHIP: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_SOLE_PROPRIETORSHIP',
      path: 'onboarding.business-details.form.type-sole-proprietorship',
      description: 'Sole Proprietorship business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TYPE_LLC: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_LLC',
      path: 'onboarding.business-details.form.type-llc',
      description: 'LLC business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TYPE_CORPORATION: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_CORPORATION',
      path: 'onboarding.business-details.form.type-corporation',
      description: 'Corporation business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TYPE_PARTNERSHIP: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_PARTNERSHIP',
      path: 'onboarding.business-details.form.type-partnership',
      description: 'Partnership business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TYPE_OTHER: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_TYPE_OTHER',
      path: 'onboarding.business-details.form.type-other',
      description: 'Other business type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    REGISTRATION_NUMBER_LABEL: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_REGISTRATION_NUMBER',
      path: 'onboarding.business-details.form.registration-number',
      description: 'Registration number label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    REGISTRATION_NUMBER_PLACEHOLDER: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_REGISTRATION_NUMBER_PLACEHOLDER',
      path: 'onboarding.business-details.form.registration-number-placeholder',
      description: 'Registration number placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    YEAR_FOUNDED_LABEL: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_YEAR_FOUNDED',
      path: 'onboarding.business-details.form.year-founded',
      description: 'Year founded label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    YEAR_FOUNDED_PLACEHOLDER: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_YEAR_FOUNDED_PLACEHOLDER',
      path: 'onboarding.business-details.form.year-founded-placeholder',
      description: 'Year founded placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    EMPLOYEE_COUNT_LABEL: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_EMPLOYEE_COUNT',
      path: 'onboarding.business-details.form.employee-count',
      description: 'Employee count label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    EMPLOYEE_COUNT_PLACEHOLDER: {
      id: 'UI_ONBOARDING_BUSINESS_DETAILS_EMPLOYEE_COUNT_PLACEHOLDER',
      path: 'onboarding.business-details.form.employee-count-placeholder',
      description: 'Employee count placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  IDENTITY_VERIFICATION: {
    TITLE: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_TITLE',
      path: 'onboarding.identity-verification.display.title',
      description: 'Identity verification step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_DESCRIPTION',
      path: 'onboarding.identity-verification.display.description',
      description: 'Identity verification step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    FIRST_NAME_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_FIRST_NAME',
      path: 'onboarding.identity-verification.form.first-name',
      description: 'First name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    LAST_NAME_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_LAST_NAME',
      path: 'onboarding.identity-verification.form.last-name',
      description: 'Last name label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DATE_OF_BIRTH_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_DATE_OF_BIRTH',
      path: 'onboarding.identity-verification.form.date-of-birth',
      description: 'Date of birth label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    EMAIL_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_EMAIL',
      path: 'onboarding.identity-verification.form.email',
      description: 'Email label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PHONE_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_PHONE',
      path: 'onboarding.identity-verification.form.phone',
      description: 'Phone label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ID_TYPE_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE',
      path: 'onboarding.identity-verification.form.id-type',
      description: 'ID type label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ID_TYPE_PLACEHOLDER: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_PLACEHOLDER',
      path: 'onboarding.identity-verification.form.id-type-placeholder',
      description: 'ID type placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ID_TYPE_PASSPORT: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_PASSPORT',
      path: 'onboarding.identity-verification.form.id-type-passport',
      description: 'Passport ID type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ID_TYPE_DRIVER_LICENSE: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_DRIVER_LICENSE',
      path: 'onboarding.identity-verification.form.id-type-driver-license',
      description: 'Driver\'s License ID type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ID_TYPE_NATIONAL_ID: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_TYPE_NATIONAL_ID',
      path: 'onboarding.identity-verification.form.id-type-national-id',
      description: 'National ID type',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ID_NUMBER_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_ID_NUMBER',
      path: 'onboarding.identity-verification.form.id-number',
      description: 'ID number label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    UPLOAD_ID_LABEL: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_UPLOAD_ID',
      path: 'onboarding.identity-verification.form.upload-id',
      description: 'Upload ID label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    UPLOAD_ID_SUBTITLE: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_UPLOAD_ID_SUBTITLE',
      path: 'onboarding.identity-verification.form.upload-id-subtitle',
      description: 'Upload ID subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CHOOSE_FILE_BUTTON: {
      id: 'UI_ONBOARDING_IDENTITY_VERIFICATION_CHOOSE_FILE',
      path: 'onboarding.identity-verification.actions.choose-file',
      description: 'Choose file button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  PRODUCTS: {
    TITLE: {
      id: 'UI_ONBOARDING_PRODUCTS_TITLE',
      path: 'onboarding.products.display.title',
      description: 'Products step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_PRODUCTS_DESCRIPTION',
      path: 'onboarding.products.display.description',
      description: 'Products step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DIGITAL_PRODUCTS_LABEL: {
      id: 'UI_ONBOARDING_PRODUCTS_DIGITAL_PRODUCTS',
      path: 'onboarding.products.form.digital-products',
      description: 'Digital products label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DIGITAL_PRODUCTS_SUBTITLE: {
      id: 'UI_ONBOARDING_PRODUCTS_DIGITAL_PRODUCTS_SUBTITLE',
      path: 'onboarding.products.form.digital-products-subtitle',
      description: 'Digital products subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PHYSICAL_PRODUCTS_LABEL: {
      id: 'UI_ONBOARDING_PRODUCTS_PHYSICAL_PRODUCTS',
      path: 'onboarding.products.form.physical-products',
      description: 'Physical products label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PHYSICAL_PRODUCTS_SUBTITLE: {
      id: 'UI_ONBOARDING_PRODUCTS_PHYSICAL_PRODUCTS_SUBTITLE',
      path: 'onboarding.products.form.physical-products-subtitle',
      description: 'Physical products subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PRODUCT_CATALOG_LABEL: {
      id: 'UI_ONBOARDING_PRODUCTS_PRODUCT_CATALOG',
      path: 'onboarding.products.form.product-catalog',
      description: 'Product catalog label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ADD_PRODUCTS_LATER_BUTTON: {
      id: 'UI_ONBOARDING_PRODUCTS_ADD_PRODUCTS_LATER',
      path: 'onboarding.products.actions.add-products-later',
      description: 'Add products later button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  SHIPPING: {
    TITLE: {
      id: 'UI_ONBOARDING_SHIPPING_TITLE',
      path: 'onboarding.shipping.display.title',
      description: 'Shipping step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_SHIPPING_DESCRIPTION',
      path: 'onboarding.shipping.display.description',
      description: 'Shipping step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    COUNTRY_LABEL: {
      id: 'UI_ONBOARDING_SHIPPING_COUNTRY',
      path: 'onboarding.shipping.form.country',
      description: 'Country label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    COUNTRY_PLACEHOLDER: {
      id: 'UI_ONBOARDING_SHIPPING_COUNTRY_PLACEHOLDER',
      path: 'onboarding.shipping.form.country-placeholder',
      description: 'Country placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CITY_LABEL: {
      id: 'UI_ONBOARDING_SHIPPING_CITY',
      path: 'onboarding.shipping.form.city',
      description: 'City label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CITY_PLACEHOLDER: {
      id: 'UI_ONBOARDING_SHIPPING_CITY_PLACEHOLDER',
      path: 'onboarding.shipping.form.city-placeholder',
      description: 'City placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    POSTAL_CODE_LABEL: {
      id: 'UI_ONBOARDING_SHIPPING_POSTAL_CODE',
      path: 'onboarding.shipping.form.postal-code',
      description: 'Postal code label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    POSTAL_CODE_PLACEHOLDER: {
      id: 'UI_ONBOARDING_SHIPPING_POSTAL_CODE_PLACEHOLDER',
      path: 'onboarding.shipping.form.postal-code-placeholder',
      description: 'Postal code placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ADDRESS_LABEL: {
      id: 'UI_ONBOARDING_SHIPPING_ADDRESS',
      path: 'onboarding.shipping.form.address',
      description: 'Address label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    ADDRESS_PLACEHOLDER: {
      id: 'UI_ONBOARDING_SHIPPING_ADDRESS_PLACEHOLDER',
      path: 'onboarding.shipping.form.address-placeholder',
      description: 'Address placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    OFFER_FREE_SHIPPING_LABEL: {
      id: 'UI_ONBOARDING_SHIPPING_OFFER_FREE_SHIPPING',
      path: 'onboarding.shipping.form.offer-free-shipping',
      description: 'Offer free shipping label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  PAYMENTS: {
    TITLE: {
      id: 'UI_ONBOARDING_PAYMENTS_TITLE',
      path: 'onboarding.payments.display.title',
      description: 'Payments step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_PAYMENTS_DESCRIPTION',
      path: 'onboarding.payments.display.description',
      description: 'Payments step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PAYMENT_METHODS_LABEL: {
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHODS',
      path: 'onboarding.payments.form.payment-methods',
      description: 'Payment methods label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PAYMENT_METHOD_CREDIT_CARD: {
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_CREDIT_CARD',
      path: 'onboarding.payments.form.payment-method-credit-card',
      description: 'Credit Card payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PAYMENT_METHOD_DEBIT_CARD: {
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_DEBIT_CARD',
      path: 'onboarding.payments.form.payment-method-debit-card',
      description: 'Debit Card payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PAYMENT_METHOD_PAYPAL: {
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_PAYPAL',
      path: 'onboarding.payments.form.payment-method-paypal',
      description: 'PayPal payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PAYMENT_METHOD_BANK_TRANSFER: {
      id: 'UI_ONBOARDING_PAYMENTS_PAYMENT_METHOD_BANK_TRANSFER',
      path: 'onboarding.payments.form.payment-method-bank-transfer',
      description: 'Bank Transfer payment method',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CURRENCY_LABEL: {
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY',
      path: 'onboarding.payments.form.currency',
      description: 'Currency label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CURRENCY_USD: {
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_USD',
      path: 'onboarding.payments.form.currency-usd',
      description: 'USD currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CURRENCY_EUR: {
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_EUR',
      path: 'onboarding.payments.form.currency-eur',
      description: 'EUR currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CURRENCY_GBP: {
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_GBP',
      path: 'onboarding.payments.form.currency-gbp',
      description: 'GBP currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CURRENCY_CAD: {
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_CAD',
      path: 'onboarding.payments.form.currency-cad',
      description: 'CAD currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    CURRENCY_AUD: {
      id: 'UI_ONBOARDING_PAYMENTS_CURRENCY_AUD',
      path: 'onboarding.payments.form.currency-aud',
      description: 'AUD currency',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  POLICIES: {
    TITLE: {
      id: 'UI_ONBOARDING_POLICIES_TITLE',
      path: 'onboarding.policies.display.title',
      description: 'Policies step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_POLICIES_DESCRIPTION',
      path: 'onboarding.policies.display.description',
      description: 'Policies step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    RETURN_POLICY_LABEL: {
      id: 'UI_ONBOARDING_POLICIES_RETURN_POLICY',
      path: 'onboarding.policies.form.return-policy',
      description: 'Return policy label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    RETURN_POLICY_PLACEHOLDER: {
      id: 'UI_ONBOARDING_POLICIES_RETURN_POLICY_PLACEHOLDER',
      path: 'onboarding.policies.form.return-policy-placeholder',
      description: 'Return policy placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    REFUND_POLICY_LABEL: {
      id: 'UI_ONBOARDING_POLICIES_REFUND_POLICY',
      path: 'onboarding.policies.form.refund-policy',
      description: 'Refund policy label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    REFUND_POLICY_PLACEHOLDER: {
      id: 'UI_ONBOARDING_POLICIES_REFUND_POLICY_PLACEHOLDER',
      path: 'onboarding.policies.form.refund-policy-placeholder',
      description: 'Refund policy placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PRIVACY_POLICY_LABEL: {
      id: 'UI_ONBOARDING_POLICIES_PRIVACY_POLICY',
      path: 'onboarding.policies.form.privacy-policy',
      description: 'Privacy policy label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PRIVACY_POLICY_PLACEHOLDER: {
      id: 'UI_ONBOARDING_POLICIES_PRIVACY_POLICY_PLACEHOLDER',
      path: 'onboarding.policies.form.privacy-policy-placeholder',
      description: 'Privacy policy placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TERMS_OF_SERVICE_LABEL: {
      id: 'UI_ONBOARDING_POLICIES_TERMS_OF_SERVICE',
      path: 'onboarding.policies.form.terms-of-service',
      description: 'Terms of service label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TERMS_OF_SERVICE_PLACEHOLDER: {
      id: 'UI_ONBOARDING_POLICIES_TERMS_OF_SERVICE_PLACEHOLDER',
      path: 'onboarding.policies.form.terms-of-service-placeholder',
      description: 'Terms of service placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  BRANDING: {
    TITLE: {
      id: 'UI_ONBOARDING_BRANDING_TITLE',
      path: 'onboarding.branding.display.title',
      description: 'Branding step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_BRANDING_DESCRIPTION',
      path: 'onboarding.branding.display.description',
      description: 'Branding step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_TAGLINE_LABEL: {
      id: 'UI_ONBOARDING_BRANDING_STORE_TAGLINE',
      path: 'onboarding.branding.form.store-tagline',
      description: 'Store tagline label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    STORE_TAGLINE_PLACEHOLDER: {
      id: 'UI_ONBOARDING_BRANDING_STORE_TAGLINE_PLACEHOLDER',
      path: 'onboarding.branding.form.store-tagline-placeholder',
      description: 'Store tagline placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    LOGO_LABEL: {
      id: 'UI_ONBOARDING_BRANDING_LOGO',
      path: 'onboarding.branding.form.logo',
      description: 'Logo label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    LOGO_SUBTITLE: {
      id: 'UI_ONBOARDING_BRANDING_LOGO_SUBTITLE',
      path: 'onboarding.branding.form.logo-subtitle',
      description: 'Logo subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    UPLOAD_BUTTON: {
      id: 'UI_ONBOARDING_BRANDING_UPLOAD',
      path: 'onboarding.branding.actions.upload',
      description: 'Upload button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PRIMARY_COLOR_LABEL: {
      id: 'UI_ONBOARDING_BRANDING_PRIMARY_COLOR',
      path: 'onboarding.branding.form.primary-color',
      description: 'Primary color label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PRIMARY_COLOR_SUBTITLE: {
      id: 'UI_ONBOARDING_BRANDING_PRIMARY_COLOR_SUBTITLE',
      path: 'onboarding.branding.form.primary-color-subtitle',
      description: 'Primary color subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  PREFERENCES: {
    TITLE: {
      id: 'UI_ONBOARDING_PREFERENCES_TITLE',
      path: 'onboarding.preferences.display.title',
      description: 'Preferences step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_PREFERENCES_DESCRIPTION',
      path: 'onboarding.preferences.display.description',
      description: 'Preferences step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TIMEZONE_LABEL: {
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE',
      path: 'onboarding.preferences.form.timezone',
      description: 'Timezone label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    NOTIFICATIONS_LABEL: {
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATIONS',
      path: 'onboarding.preferences.form.notifications',
      description: 'Notifications label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    NOTIFICATION_ORDER: {
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_ORDER',
      path: 'onboarding.preferences.form.notification-order',
      description: 'Order notifications',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    NOTIFICATION_MARKETING: {
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_MARKETING',
      path: 'onboarding.preferences.form.notification-marketing',
      description: 'Marketing emails',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    NOTIFICATION_SYSTEM: {
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_SYSTEM',
      path: 'onboarding.preferences.form.notification-system',
      description: 'System updates',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    NOTIFICATION_WEEKLY_REPORT: {
      id: 'UI_ONBOARDING_PREFERENCES_NOTIFICATION_WEEKLY_REPORT',
      path: 'onboarding.preferences.form.notification-weekly-report',
      description: 'Weekly performance report',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TIMEZONE_ET: {
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_ET',
      path: 'onboarding.preferences.form.timezone-et',
      description: 'Eastern Time (ET)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TIMEZONE_CT: {
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_CT',
      path: 'onboarding.preferences.form.timezone-ct',
      description: 'Central Time (CT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TIMEZONE_MT: {
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_MT',
      path: 'onboarding.preferences.form.timezone-mt',
      description: 'Mountain Time (MT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TIMEZONE_PT: {
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_PT',
      path: 'onboarding.preferences.form.timezone-pt',
      description: 'Pacific Time (PT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TIMEZONE_GMT: {
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_GMT',
      path: 'onboarding.preferences.form.timezone-gmt',
      description: 'London (GMT)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TIMEZONE_CET: {
      id: 'UI_ONBOARDING_PREFERENCES_TIMEZONE_CET',
      path: 'onboarding.preferences.form.timezone-cet',
      description: 'Paris (CET)',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  TAX_INFO: {
    TITLE: {
      id: 'UI_ONBOARDING_TAX_INFO_TITLE',
      path: 'onboarding.tax-info.display.title',
      description: 'Tax info step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_TAX_INFO_DESCRIPTION',
      path: 'onboarding.tax-info.display.description',
      description: 'Tax info step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TAX_ID_LABEL: {
      id: 'UI_ONBOARDING_TAX_INFO_TAX_ID',
      path: 'onboarding.tax-info.form.tax-id',
      description: 'Tax ID/VAT Number label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    TAX_ID_PLACEHOLDER: {
      id: 'UI_ONBOARDING_TAX_INFO_TAX_ID_PLACEHOLDER',
      path: 'onboarding.tax-info.form.tax-id-placeholder',
      description: 'Tax ID placeholder',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  MARKETING: {
    TITLE: {
      id: 'UI_ONBOARDING_MARKETING_TITLE',
      path: 'onboarding.marketing.display.title',
      description: 'Marketing step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_MARKETING_DESCRIPTION',
      path: 'onboarding.marketing.display.description',
      description: 'Marketing step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    EMAIL_MARKETING_LABEL: {
      id: 'UI_ONBOARDING_MARKETING_EMAIL_MARKETING',
      path: 'onboarding.marketing.form.email-marketing',
      description: 'Email marketing label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    EMAIL_MARKETING_SUBTITLE: {
      id: 'UI_ONBOARDING_MARKETING_EMAIL_MARKETING_SUBTITLE',
      path: 'onboarding.marketing.form.email-marketing-subtitle',
      description: 'Email marketing subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    SOCIAL_SHARING_LABEL: {
      id: 'UI_ONBOARDING_MARKETING_SOCIAL_SHARING',
      path: 'onboarding.marketing.form.social-sharing',
      description: 'Social sharing label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    SOCIAL_SHARING_SUBTITLE: {
      id: 'UI_ONBOARDING_MARKETING_SOCIAL_SHARING_SUBTITLE',
      path: 'onboarding.marketing.form.social-sharing-subtitle',
      description: 'Social sharing subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PRODUCT_REVIEWS_LABEL: {
      id: 'UI_ONBOARDING_MARKETING_PRODUCT_REVIEWS',
      path: 'onboarding.marketing.form.product-reviews',
      description: 'Product reviews label',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    PRODUCT_REVIEWS_SUBTITLE: {
      id: 'UI_ONBOARDING_MARKETING_PRODUCT_REVIEWS_SUBTITLE',
      path: 'onboarding.marketing.form.product-reviews-subtitle',
      description: 'Product reviews subtitle',
      category: 'input',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  COMPLETION: {
    TITLE: {
      id: 'UI_ONBOARDING_COMPLETION_TITLE',
      path: 'onboarding.completion.display.title',
      description: 'Completion step title',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    DESCRIPTION: {
      id: 'UI_ONBOARDING_COMPLETION_DESCRIPTION',
      path: 'onboarding.completion.display.description',
      description: 'Completion step description',
      category: 'display',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    GO_TO_DASHBOARD_BUTTON: {
      id: 'UI_ONBOARDING_COMPLETION_GO_TO_DASHBOARD',
      path: 'onboarding.completion.actions.go-to-dashboard',
      description: 'Go to dashboard button',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
  COMMON: {
    PREVIOUS_BUTTON: {
      id: 'UI_ONBOARDING_COMMON_PREVIOUS',
      path: 'onboarding.common.actions.previous',
      description: 'Previous button text',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    NEXT_BUTTON: {
      id: 'UI_ONBOARDING_COMMON_NEXT',
      path: 'onboarding.common.actions.next',
      description: 'Next button text',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
    FINISH_BUTTON: {
      id: 'UI_ONBOARDING_COMMON_FINISH',
      path: 'onboarding.common.actions.finish',
      description: 'Finish button text',
      category: 'action',
      feature: 'onboarding',
      version: '1.0.0',
      createdAt: '2026-06-20',
      updatedAt: '2026-06-20',
    } as const,
  },
} as const;
