/** Settings page UI identities */
export const SETTINGS = {
  PAGE: {
    TITLE: {
      id: 'UI_SETTINGS_PAGE_TITLE',
      path: 'settings.page.title',
      description: 'Settings page title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DESCRIPTION: {
      id: 'UI_SETTINGS_PAGE_DESCRIPTION',
      path: 'settings.page.description',
      description: 'Settings page description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  LANGUAGE: {
    TITLE: {
      id: 'UI_SETTINGS_LANGUAGE_TITLE',
      path: 'settings.language.title',
      description: 'Language section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DESCRIPTION: {
      id: 'UI_SETTINGS_LANGUAGE_DESCRIPTION',
      path: 'settings.language.description',
      description: 'Language section description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  DIRECTION: {
    TITLE: {
      id: 'UI_SETTINGS_DIRECTION_TITLE',
      path: 'settings.direction.title',
      description: 'Direction section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DESCRIPTION: {
      id: 'UI_SETTINGS_DIRECTION_DESCRIPTION',
      path: 'settings.direction.description',
      description: 'Direction section description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    RTL: {
      id: 'UI_SETTINGS_DIRECTION_RTL',
      path: 'settings.direction.rtl',
      description: 'RTL direction label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    LTR: {
      id: 'UI_SETTINGS_DIRECTION_LTR',
      path: 'settings.direction.ltr',
      description: 'LTR direction label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  THEME: {
    TITLE: {
      id: 'UI_SETTINGS_THEME_TITLE',
      path: 'settings.theme.title',
      description: 'Theme section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DESCRIPTION: {
      id: 'UI_SETTINGS_THEME_DESCRIPTION',
      path: 'settings.theme.description',
      description: 'Theme section description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  DISPLAY: {
    TITLE: {
      id: 'UI_SETTINGS_DISPLAY_TITLE',
      path: 'settings.display.title',
      description: 'Display section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    FONT_SIZE: {
      id: 'UI_SETTINGS_DISPLAY_FONT_SIZE',
      path: 'settings.display.font-size',
      description: 'Font size slider label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DENSITY: {
      id: 'UI_SETTINGS_DISPLAY_DENSITY',
      path: 'settings.display.density',
      description: 'Density selector label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  ACCESSIBILITY: {
    TITLE: {
      id: 'UI_SETTINGS_ACCESSIBILITY_TITLE',
      path: 'settings.accessibility.title',
      description: 'Accessibility section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    HIGH_CONTRAST: {
      id: 'UI_SETTINGS_ACCESSIBILITY_HIGH_CONTRAST',
      path: 'settings.accessibility.high-contrast',
      description: 'High contrast toggle label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    REDUCED_MOTION: {
      id: 'UI_SETTINGS_ACCESSIBILITY_REDUCED_MOTION',
      path: 'settings.accessibility.reduced-motion',
      description: 'Reduced motion toggle label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  FEATURES: {
    TITLE: {
      id: 'UI_SETTINGS_FEATURES_TITLE',
      path: 'settings.features.title',
      description: 'Features section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DARK_MODE: {
      id: 'UI_SETTINGS_FEATURES_DARK_MODE',
      path: 'settings.features.dark-mode',
      description: 'Dark mode feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    MULTI_LANGUAGE: {
      id: 'UI_SETTINGS_FEATURES_MULTI_LANGUAGE',
      path: 'settings.features.multi-language',
      description: 'Multi language feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ADVANCED_SEARCH: {
      id: 'UI_SETTINGS_FEATURES_ADVANCED_SEARCH',
      path: 'settings.features.advanced-search',
      description: 'Advanced search feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    EXPORT_DATA: {
      id: 'UI_SETTINGS_FEATURES_EXPORT_DATA',
      path: 'settings.features.export-data',
      description: 'Export data feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    IMPORT_DATA: {
      id: 'UI_SETTINGS_FEATURES_IMPORT_DATA',
      path: 'settings.features.import-data',
      description: 'Import data feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    EXPERIMENTAL_UI: {
      id: 'UI_SETTINGS_FEATURES_EXPERIMENTAL_UI',
      path: 'settings.features.experimental-ui',
      description: 'Experimental UI feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    BETA_FEATURES: {
      id: 'UI_SETTINGS_FEATURES_BETA_FEATURES',
      path: 'settings.features.beta-features',
      description: 'Beta features toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SOCIAL_SHARING: {
      id: 'UI_SETTINGS_FEATURES_SOCIAL_SHARING',
      path: 'settings.features.social-sharing',
      description: 'Social sharing feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    OFFLINE_MODE: {
      id: 'UI_SETTINGS_FEATURES_OFFLINE_MODE',
      path: 'settings.features.offline-mode',
      description: 'Offline mode feature toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  MAINTENANCE: {
    TITLE: {
      id: 'UI_SETTINGS_MAINTENANCE_TITLE',
      path: 'settings.maintenance.title',
      description: 'Maintenance section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ENABLED: {
      id: 'UI_SETTINGS_MAINTENANCE_ENABLED',
      path: 'settings.maintenance.enabled',
      description: 'Maintenance mode toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    BYPASSED: {
      id: 'UI_SETTINGS_MAINTENANCE_BYPASSED',
      path: 'settings.maintenance.bypassed',
      description: 'Maintenance bypass toggle',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  OPTIONS: {
    ENGLISH: {
      id: 'UI_SETTINGS_OPTIONS_ENGLISH',
      path: 'settings.options.english',
      description: 'English language option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ARABIC: {
      id: 'UI_SETTINGS_OPTIONS_ARABIC',
      path: 'settings.options.arabic',
      description: 'Arabic language option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    LIGHT: {
      id: 'UI_SETTINGS_OPTIONS_LIGHT',
      path: 'settings.options.light',
      description: 'Light theme option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DARK: {
      id: 'UI_SETTINGS_OPTIONS_DARK',
      path: 'settings.options.dark',
      description: 'Dark theme option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SYSTEM: {
      id: 'UI_SETTINGS_OPTIONS_SYSTEM',
      path: 'settings.options.system',
      description: 'System theme option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DENSITY_COMPACT: {
      id: 'UI_SETTINGS_OPTIONS_DENSITY_COMPACT',
      path: 'settings.options.density-compact',
      description: 'Compact density option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DENSITY_COMFORTABLE: {
      id: 'UI_SETTINGS_OPTIONS_DENSITY_COMFORTABLE',
      path: 'settings.options.density-comfortable',
      description: 'Comfortable density option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DENSITY_SPACIOUS: {
      id: 'UI_SETTINGS_OPTIONS_DENSITY_SPACIOUS',
      path: 'settings.options.density-spacious',
      description: 'Spacious density option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  ACTIONS: {
    RESET: {
      id: 'UI_SETTINGS_ACTION_RESET',
      path: 'settings.actions.reset',
      description: 'Reset preferences button',
      category: 'action',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
} as const;
