/** Settings page UI identities */
export const SETTINGS = {
  TITLE: {
    id: 'UI_SETTINGS_TITLE',
    path: 'settings.page.title',
    description: 'Settings page title',
    category: 'display',
    feature: 'settings',
    version: '1.0.0',
    createdAt: '2026-06-18',
    updatedAt: '2026-06-18',
  } as const,
  DESCRIPTION: {
    id: 'UI_SETTINGS_DESCRIPTION',
    path: 'settings.page.description',
    description: 'Settings page description',
    category: 'display',
    feature: 'settings',
    version: '1.0.0',
    createdAt: '2026-06-18',
    updatedAt: '2026-06-18',
  } as const,
  APP_SETTINGS: {
    TITLE: {
      id: 'UI_SETTINGS_APP_SETTINGS_TITLE',
      path: 'settings.appSettings.title',
      description: 'Application settings section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    ACTIVE: {
      id: 'UI_SETTINGS_APP_SETTINGS_ACTIVE',
      path: 'settings.appSettings.status.active',
      description: 'System status active label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    STATUS_TITLE: {
      id: 'UI_SETTINGS_APP_SETTINGS_STATUS_TITLE',
      path: 'settings.appSettings.status.title',
      description: 'System status title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    STATUS_DESCRIPTION: {
      id: 'UI_SETTINGS_APP_SETTINGS_STATUS_DESCRIPTION',
      path: 'settings.appSettings.status.description',
      description: 'System status description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    MAINTENANCE_TITLE: {
      id: 'UI_SETTINGS_APP_SETTINGS_MAINTENANCE_TITLE',
      path: 'settings.appSettings.maintenance.title',
      description: 'Maintenance mode title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    MAINTENANCE_DESCRIPTION: {
      id: 'UI_SETTINGS_APP_SETTINGS_MAINTENANCE_DESCRIPTION',
      path: 'settings.appSettings.maintenance.description',
      description: 'Maintenance mode description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    FEATURE_FLAGS_TITLE: {
      id: 'UI_SETTINGS_APP_SETTINGS_FEATURE_FLAGS_TITLE',
      path: 'settings.appSettings.featureFlags.title',
      description: 'Feature flags section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    AI: {
      id: 'UI_SETTINGS_APP_SETTINGS_AI',
      path: 'settings.appSettings.featureFlags.ai',
      description: 'AI feature flag label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    ANALYTICS: {
      id: 'UI_SETTINGS_APP_SETTINGS_ANALYTICS',
      path: 'settings.appSettings.featureFlags.analytics',
      description: 'Analytics feature flag label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    PDF: {
      id: 'UI_SETTINGS_APP_SETTINGS_PDF',
      path: 'settings.appSettings.featureFlags.pdf',
      description: 'PDF export feature flag label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
  LANGUAGE_REGION: {
    TITLE: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_TITLE',
      path: 'settings.languageRegion.title',
      description: 'Language & region section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    LANGUAGE_TITLE: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_LANGUAGE_TITLE',
      path: 'settings.languageRegion.language.title',
      description: 'Language selection title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    LANGUAGE_DESCRIPTION: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_LANGUAGE_DESCRIPTION',
      path: 'settings.languageRegion.language.description',
      description: 'Language selection description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    DIRECTION_PREVIEW: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_DIRECTION_PREVIEW',
      path: 'settings.languageRegion.direction.preview',
      description: 'Direction preview label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    TIMEZONE: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_TIMEZONE',
      path: 'settings.languageRegion.timezone.label',
      description: 'Timezone label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    CAIRO: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_CAIRO',
      path: 'settings.languageRegion.timezone.cairo',
      description: 'Cairo timezone option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    MECCA: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_MECCA',
      path: 'settings.languageRegion.timezone.mecca',
      description: 'Mecca timezone option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    DUBAI: {
      id: 'UI_SETTINGS_LANGUAGE_REGION_DUBAI',
      path: 'settings.languageRegion.timezone.dubai',
      description: 'Dubai timezone option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
  APPEARANCE: {
    TITLE: {
      id: 'UI_SETTINGS_APPEARANCE_TITLE',
      path: 'settings.appearance.title',
      description: 'Appearance section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    THEME_TITLE: {
      id: 'UI_SETTINGS_APPEARANCE_THEME_TITLE',
      path: 'settings.appearance.theme.title',
      description: 'Theme section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    LIGHT: {
      id: 'UI_SETTINGS_APPEARANCE_LIGHT',
      path: 'settings.appearance.theme.light',
      description: 'Light theme option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    DARK: {
      id: 'UI_SETTINGS_APPEARANCE_DARK',
      path: 'settings.appearance.theme.dark',
      description: 'Dark theme option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    SYSTEM: {
      id: 'UI_SETTINGS_APPEARANCE_SYSTEM',
      path: 'settings.appearance.theme.system',
      description: 'System theme option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    FONT_SIZE_TITLE: {
      id: 'UI_SETTINGS_APPEARANCE_FONT_SIZE_TITLE',
      path: 'settings.appearance.fontSize.title',
      description: 'Font size section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    DENSITY_TITLE: {
      id: 'UI_SETTINGS_APPEARANCE_DENSITY_TITLE',
      path: 'settings.appearance.density.title',
      description: 'Density section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    COMPACT: {
      id: 'UI_SETTINGS_APPEARANCE_COMPACT',
      path: 'settings.appearance.density.compact',
      description: 'Compact density option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    COMFORTABLE: {
      id: 'UI_SETTINGS_APPEARANCE_COMFORTABLE',
      path: 'settings.appearance.density.comfortable',
      description: 'Comfortable density option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    SPACIOUS: {
      id: 'UI_SETTINGS_APPEARANCE_SPACIOUS',
      path: 'settings.appearance.density.spacious',
      description: 'Spacious density option',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    PREVIEW_TITLE: {
      id: 'UI_SETTINGS_APPEARANCE_PREVIEW_TITLE',
      path: 'settings.appearance.preview.title',
      description: 'Preview section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    BUTTON: {
      id: 'UI_SETTINGS_APPEARANCE_BUTTON',
      path: 'settings.appearance.preview.button',
      description: 'Preview button label',
      category: 'action',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
  ACCESSIBILITY: {
    TITLE: {
      id: 'UI_SETTINGS_ACCESSIBILITY_TITLE',
      path: 'settings.accessibility.title',
      description: 'Accessibility section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    HIGH_CONTRAST_TITLE: {
      id: 'UI_SETTINGS_ACCESSIBILITY_HIGH_CONTRAST_TITLE',
      path: 'settings.accessibility.highContrast.title',
      description: 'High contrast toggle title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    HIGH_CONTRAST_DESCRIPTION: {
      id: 'UI_SETTINGS_ACCESSIBILITY_HIGH_CONTRAST_DESCRIPTION',
      path: 'settings.accessibility.highContrast.description',
      description: 'High contrast toggle description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    REDUCED_MOTION_TITLE: {
      id: 'UI_SETTINGS_ACCESSIBILITY_REDUCED_MOTION_TITLE',
      path: 'settings.accessibility.reducedMotion.title',
      description: 'Reduced motion toggle title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    REDUCED_MOTION_DESCRIPTION: {
      id: 'UI_SETTINGS_ACCESSIBILITY_REDUCED_MOTION_DESCRIPTION',
      path: 'settings.accessibility.reducedMotion.description',
      description: 'Reduced motion toggle description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
  DEVELOPER_TOOLS: {
    TITLE: {
      id: 'UI_SETTINGS_DEVELOPER_TOOLS_TITLE',
      path: 'settings.developerTools.title',
      description: 'Developer tools section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    SSOT_GUARD_TITLE: {
      id: 'UI_SETTINGS_DEVELOPER_TOOLS_SSOT_GUARD_TITLE',
      path: 'settings.developerTools.ssotGuard.title',
      description: 'SSOT Guard toggle title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    SSOT_GUARD_DESCRIPTION: {
      id: 'UI_SETTINGS_DEVELOPER_TOOLS_SSOT_GUARD_DESCRIPTION',
      path: 'settings.developerTools.ssotGuard.description',
      description: 'SSOT Guard toggle description',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    DIAGNOSTICS: {
      id: 'UI_SETTINGS_DEVELOPER_TOOLS_DIAGNOSTICS',
      path: 'settings.developerTools.diagnostics.label',
      description: 'Diagnostics label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    START_TEST: {
      id: 'UI_SETTINGS_DEVELOPER_TOOLS_START_TEST',
      path: 'settings.developerTools.startTest.button',
      description: 'Start test button label',
      category: 'action',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
  STORAGE: {
    TITLE: {
      id: 'UI_SETTINGS_STORAGE_TITLE',
      path: 'settings.storage.title',
      description: 'Storage section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    LOCAL_STORAGE: {
      id: 'UI_SETTINGS_STORAGE_LOCAL_STORAGE',
      path: 'settings.storage.localStorage.label',
      description: 'Local storage label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    USAGE: {
      id: 'UI_SETTINGS_STORAGE_USAGE',
      path: 'settings.storage.usage.label',
      description: 'Storage usage label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    COOKIES: {
      id: 'UI_SETTINGS_STORAGE_COOKIES',
      path: 'settings.storage.cookies.label',
      description: 'Cookies label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    CLEAR_ALL: {
      id: 'UI_SETTINGS_STORAGE_CLEAR_ALL',
      path: 'settings.storage.clearAll.button',
      description: 'Clear all button label',
      category: 'action',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
  SUMMARY: {
    TITLE: {
      id: 'UI_SETTINGS_SUMMARY_TITLE',
      path: 'settings.summary.title',
      description: 'Summary section title',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    LANGUAGE: {
      id: 'UI_SETTINGS_SUMMARY_LANGUAGE',
      path: 'settings.summary.language.label',
      description: 'Active language label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    THEME: {
      id: 'UI_SETTINGS_SUMMARY_THEME',
      path: 'settings.summary.theme.label',
      description: 'Interface theme label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    DENSITY: {
      id: 'UI_SETTINGS_SUMMARY_DENSITY',
      path: 'settings.summary.density.label',
      description: 'Data density label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    TIMEZONE: {
      id: 'UI_SETTINGS_SUMMARY_TIMEZONE',
      path: 'settings.summary.timezone.label',
      description: 'Timezone label',
      category: 'display',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
  ACTIONS: {
    SAVE: {
      id: 'UI_SETTINGS_ACTIONS_SAVE',
      path: 'settings.actions.save.button',
      description: 'Save changes button label',
      category: 'action',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    RESET_PREFERENCES: {
      id: 'UI_SETTINGS_ACTIONS_RESET_PREFERENCES',
      path: 'settings.actions.resetPreferences.button',
      description: 'Reset preferences button label',
      category: 'action',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
    RESTORE_DEFAULTS: {
      id: 'UI_SETTINGS_ACTIONS_RESTORE_DEFAULTS',
      path: 'settings.actions.restoreDefaults.button',
      description: 'Restore defaults button label',
      category: 'action',
      feature: 'settings',
      version: '1.0.0',
      createdAt: '2026-06-18',
      updatedAt: '2026-06-18',
    } as const,
  },
} as const;
