/** Auto-split from registry.ts */
export const SHARED_LAYOUT = {
  HEADER: {
    CONTAINER: {
      id: 'UI_SHARED_HEADER_CONTAINER',
      path: 'shared-layout.header.layout.container',
      description: 'Header main container',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    INNER_WRAPPER: {
      id: 'UI_SHARED_HEADER_INNER_WRAPPER',
      path: 'shared-layout.header.layout.inner-wrapper',
      description: 'Header inner wrapper',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    BRAND_SECTION: {
      id: 'UI_SHARED_HEADER_BRAND_SECTION',
      path: 'shared-layout.header.layout.brand-section',
      description: 'Header brand section',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ACTIONS_SECTION: {
      id: 'UI_SHARED_HEADER_ACTIONS_SECTION',
      path: 'shared-layout.header.layout.actions-section',
      description: 'Header actions section',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    MENU: {
      MENU_BUTTON: {
        id: 'UI_SHARED_HEADER_MENU',
        path: 'shared-layout.header.menu.menu-button',
        description: 'Toggle mobile menu button',
        category: 'action',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
    },
    BRAND: {
      BRAND_LINK: {
        id: 'UI_SHARED_HEADER_BRAND_LINK',
        path: 'shared-layout.header.brand.brand-link',
        description: 'Brand logo home link',
        category: 'navigation',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
    },
    ACTIONS: {
      SEARCH_BUTTON: {
        id: 'UI_SHARED_HEADER_SEARCH_BUTTON',
        path: 'shared-layout.header.actions.search-button',
        description: 'Trigger search button',
        category: 'action',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
      CART_BUTTON: {
        id: 'UI_SHARED_HEADER_CART_BUTTON',
        path: 'shared-layout.header.actions.cart-button',
        description: 'Header shopping cart button',
        category: 'action',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
      SEARCH_INPUT: {
        id: 'UI_SHARED_HEADER_SEARCH_INPUT',
        path: 'shared-layout.header.actions.search-input',
        description: 'Desktop header search input field',
        category: 'input',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
    },
  },
  BOTTOM_NAV: {
    CONTAINER: {
      id: 'UI_SHARED_BOTTOM_NAV_CONTAINER',
      path: 'shared-layout.bottom-nav.layout.container',
      description: 'Bottom navigation bar container',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ITEMS: {
      HOME_LINK: {
        id: 'UI_SHARED_BOTTOM_NAV_HOME',
        path: 'shared-layout.bottom-nav.items.home-link',
        description: 'Bottom navigation home link',
        category: 'navigation',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
      NOTIFICATIONS_LINK: {
        id: 'UI_SHARED_BOTTOM_NAV_NOTIFICATIONS',
        path: 'shared-layout.bottom-nav.items.notifications-link',
        description: 'Bottom navigation notifications link',
        category: 'navigation',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
      FAVORITES_LINK: {
        id: 'UI_SHARED_BOTTOM_NAV_FAVORITES',
        path: 'shared-layout.bottom-nav.items.favorites-link',
        description: 'Bottom navigation favorites link',
        category: 'navigation',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
      ORDERS_LINK: {
        id: 'UI_SHARED_BOTTOM_NAV_ORDERS',
        path: 'shared-layout.bottom-nav.items.orders-link',
        description: 'Bottom navigation orders link',
        category: 'navigation',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
      PROFILE_LINK: {
        id: 'UI_SHARED_BOTTOM_NAV_PROFILE',
        path: 'shared-layout.bottom-nav.items.profile-link',
        description: 'Bottom navigation profile link',
        category: 'navigation',
        feature: 'shared-layout',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
    },
  },
  SIDEBAR: {
    CONTAINER: {
      id: 'UI_SHARED_SIDEBAR_CONTAINER',
      path: 'shared-layout.sidebar.layout.container',
      description: 'Sidebar main container',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    OVERLAY: {
      id: 'UI_SHARED_SIDEBAR_OVERLAY',
      path: 'shared-layout.sidebar.layout.overlay',
      description: 'Sidebar backdrop overlay',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    SIDEBAR_PANEL: {
      id: 'UI_SHARED_SIDEBAR_PANEL',
      path: 'shared-layout.sidebar.layout.panel',
      description: 'Sidebar panel',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    HEADER: {
      id: 'UI_SHARED_SIDEBAR_HEADER',
      path: 'shared-layout.sidebar.layout.header',
      description: 'Sidebar header',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CONTENT: {
      id: 'UI_SHARED_SIDEBAR_CONTENT',
      path: 'shared-layout.sidebar.layout.content',
      description: 'Sidebar content area',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ACTIONS_SECTION: {
      id: 'UI_SHARED_SIDEBAR_ACTIONS_SECTION',
      path: 'shared-layout.sidebar.layout.actions-section',
      description: 'Sidebar actions section',
      category: 'container',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CLOSE_BUTTON: {
      id: 'UI_SHARED_SIDEBAR_CLOSE',
      path: 'shared-layout.sidebar.actions.close-button',
      description: 'Close sidebar button',
      category: 'action',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-16',
      updatedAt: '2026-06-16',
    } as const,
    LOGIN_BUTTON: {
      id: 'UI_SHARED_SIDEBAR_LOGIN',
      path: 'shared-layout.sidebar.actions.login-button',
      description: 'Login button in sidebar',
      category: 'action',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-16',
      updatedAt: '2026-06-16',
    } as const,
    LANGUAGE_TOGGLE: {
      id: 'UI_SHARED_SIDEBAR_LANGUAGE',
      path: 'shared-layout.sidebar.actions.language-toggle',
      description: 'Language switcher button',
      category: 'action',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-16',
      updatedAt: '2026-06-16',
    } as const,
    THEME_TOGGLE: {
      id: 'UI_SHARED_SIDEBAR_THEME',
      path: 'shared-layout.sidebar.actions.theme-toggle',
      description: 'Dark/light mode toggle',
      category: 'action',
      feature: 'shared-layout',
      version: '1.0.0',
      createdAt: '2026-06-16',
      updatedAt: '2026-06-16',
    } as const,
  },
} as const;

// ============================================================================
// AUTH PAGE IDENTIFIERS
// ============================================================================