export const SIGNUP = {
  REGISTER: {
    LOGO: {
      id: 'UI_SIGNUP_REGISTER_LOGO',
      path: 'signup.register.display.logo',
      description: 'Register page logo',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    HEADING: {
      id: 'UI_SIGNUP_REGISTER_HEADING',
      path: 'signup.register.display.heading',
      description: 'Register page main heading',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    SUBHEADING: {
      id: 'UI_SIGNUP_REGISTER_SUBHEADING',
      path: 'signup.register.display.subheading',
      description: 'Register page subheading',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PHONE_INPUT: {
      id: 'UI_SIGNUP_REGISTER_PHONE_INPUT',
      path: 'signup.register.form.phone-input',
      description: 'Register page phone number input',
      category: 'input' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PHONE_COUNTRY_CODE: {
      id: 'UI_SIGNUP_REGISTER_PHONE_CODE',
      path: 'signup.register.form.phone-country-code',
      description: 'Egypt country code +20',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    VERIFY_PHONE_BUTTON: {
      id: 'UI_SIGNUP_REGISTER_VERIFY_PHONE',
      path: 'signup.register.form.verify-phone-button',
      description: 'Verify phone number button',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PHONE_VERIFIED_BADGE: {
      id: 'UI_SIGNUP_REGISTER_PHONE_VERIFIED',
      path: 'signup.register.form.phone-verified-badge',
      description: 'Phone verified success badge',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    CHANGE_PHONE_BUTTON: {
      id: 'UI_SIGNUP_REGISTER_CHANGE_PHONE',
      path: 'signup.register.form.change-phone-button',
      description: 'Change phone number button',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    OTP_INPUT: {
      id: 'UI_SIGNUP_REGISTER_OTP_INPUT',
      path: 'signup.register.form.otp-input',
      description: 'OTP verification code input',
      category: 'input' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    RESEND_OTP_BUTTON: {
      id: 'UI_SIGNUP_REGISTER_RESEND_OTP',
      path: 'signup.register.form.resend-otp-button',
      description: 'Resend OTP button',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    OTP_COUNTDOWN: {
      id: 'UI_SIGNUP_REGISTER_OTP_COUNTDOWN',
      path: 'signup.register.form.otp-countdown',
      description: 'OTP resend countdown timer',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PASSWORD_INPUT: {
      id: 'UI_SIGNUP_REGISTER_PASSWORD_INPUT',
      path: 'signup.register.form.password-input',
      description: 'Register page password input',
      category: 'input' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    TOGGLE_PASSWORD_VISIBILITY: {
      id: 'UI_SIGNUP_REGISTER_TOGGLE_PASSWORD',
      path: 'signup.register.form.toggle-password-visibility',
      description: 'Toggle password visibility button',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PASSWORD_STRENGTH_LABEL: {
      id: 'UI_SIGNUP_REGISTER_PASSWORD_STRENGTH',
      path: 'signup.register.form.password-strength-label',
      description: 'Password strength indicator label',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PASSWORD_STRENGTH_WEAK: {
      id: 'UI_SIGNUP_REGISTER_STRENGTH_WEAK',
      path: 'signup.register.form.strength-weak',
      description: 'Weak password strength text',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PASSWORD_STRENGTH_MEDIUM: {
      id: 'UI_SIGNUP_REGISTER_STRENGTH_MEDIUM',
      path: 'signup.register.form.strength-medium',
      description: 'Medium password strength text',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PASSWORD_STRENGTH_STRONG: {
      id: 'UI_SIGNUP_REGISTER_STRENGTH_STRONG',
      path: 'signup.register.form.strength-strong',
      description: 'Strong password strength text',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    CONFIRM_PASSWORD_INPUT: {
      id: 'UI_SIGNUP_REGISTER_CONFIRM_PASSWORD',
      path: 'signup.register.form.confirm-password-input',
      description: 'Confirm password input',
      category: 'input' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    TOGGLE_CONFIRM_PASSWORD_VISIBILITY: {
      id: 'UI_SIGNUP_REGISTER_TOGGLE_CONFIRM_PASSWORD',
      path: 'signup.register.form.toggle-confirm-password-visibility',
      description: 'Toggle confirm password visibility button',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    PASSWORD_MATCH_ERROR: {
      id: 'UI_SIGNUP_REGISTER_PASSWORD_MISMATCH',
      path: 'signup.register.form.password-mismatch-error',
      description: 'Password mismatch error message',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    SUBMIT_BUTTON: {
      id: 'UI_SIGNUP_REGISTER_SUBMIT',
      path: 'signup.register.form.submit-button',
      description: 'Register form submit button',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    LOGIN_LINK: {
      id: 'UI_SIGNUP_REGISTER_LOGIN_LINK',
      path: 'signup.register.actions.login-link',
      description: 'Login page link',
      category: 'navigation' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    ENGLISH_LANGUAGE_LINK: {
      id: 'UI_SIGNUP_REGISTER_ENGLISH_LANG',
      path: 'signup.register.footer.english-language-link',
      description: 'English language switcher link',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    DARK_MODE_TOGGLE: {
      id: 'UI_SIGNUP_REGISTER_DARK_MODE',
      path: 'signup.register.footer.dark-mode-toggle',
      description: 'Dark mode toggle button',
      category: 'action' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
    COPYRIGHT: {
      id: 'UI_SIGNUP_REGISTER_COPYRIGHT',
      path: 'signup.register.footer.copyright',
      description: 'Register page copyright notice',
      category: 'display' as const,
      feature: 'signup',
      version: '1.0.0',
      createdAt: '2026-06-19',
      updatedAt: '2026-06-19',
    } as const,
  },
} as const;
