/** Auto-split from registry.ts */
export const SPLASH = {
  LOGO: {
    IMAGE: {
      id: 'UI_SPLASH_LOGO_IMAGE',
      path: 'splash.logo.display.logo-image',
      description: 'Splash screen logo image',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    HEADING: {
      id: 'UI_SPLASH_LOGO_HEADING',
      path: 'splash.logo.display.heading',
      description: 'Splash screen main heading',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
    } as const,
    TAGLINE: {
      id: 'UI_SPLASH_LOGO_TAGLINE',
      path: 'splash.logo.display.tagline',
      description: 'Splash screen tagline below heading',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
  },
  MAINTENANCE: {
    CONTAINER: {
      id: 'UI_SPLASH_MAINTENANCE_CONTAINER',
      path: 'splash.maintenance.layout.container',
      description: 'Maintenance screen container',
      category: 'container',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    CARD: {
      id: 'UI_SPLASH_MAINTENANCE_CARD',
      path: 'splash.maintenance.layout.card',
      description: 'Maintenance card',
      category: 'container',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    ICON_CONTAINER: {
      id: 'UI_SPLASH_MAINTENANCE_ICON_CONTAINER',
      path: 'splash.maintenance.layout.icon-container',
      description: 'Maintenance icon container',
      category: 'container',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    TITLE: {
      id: 'UI_SPLASH_MAINTENANCE_TITLE',
      path: 'splash.maintenance.display.title',
      description: 'Maintenance screen title',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    DEFAULT_MESSAGE: {
      id: 'UI_SPLASH_MAINTENANCE_DEFAULT_MESSAGE',
      path: 'splash.maintenance.display.default-message',
      description: 'Maintenance default message',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    INVALID_CODE: {
      id: 'UI_SPLASH_MAINTENANCE_INVALID_CODE',
      path: 'splash.maintenance.display.invalid-code',
      description: 'Invalid maintenance access code error',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
    } as const,
    FORM: {
      PIN_INPUT: {
        id: 'UI_SPLASH_MAINT_PIN',
        path: 'splash.maintenance.form.pin-input',
        description: 'Developer bypass PIN input',
        category: 'input',
        feature: 'splash',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
      SUBMIT_BUTTON: {
        id: 'UI_SPLASH_MAINT_SUBMIT',
        path: 'splash.maintenance.form.submit-button',
        description: 'Bypass maintenance mode button',
        category: 'action',
        feature: 'splash',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
      } as const,
    },
  },
} as const;

// ============================================================================
// ERROR BOUNDARY IDENTIFIERS
// ============================================================================