/** Auto-split from registry.ts */
export const SPLASH = {
  LOGO: {
    IMAGE: {
uuid: '15a4525c-1cd3-52eb-9495-7e6ae3aae621',
      id: 'UI_SPLASH_LOGO_IMAGE',
      path: 'splash.logo.display.logo-image',
      lifecycle: 'active',
      description: 'Splash screen logo image',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    HEADING: {
uuid: '53c5d423-bb93-5198-8dea-5cc597eeabea',
      id: 'UI_SPLASH_LOGO_HEADING',
      path: 'splash.logo.display.heading',
      lifecycle: 'active',
      description: 'Splash screen main heading',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-15',
      updatedAt: '2026-06-15',
} as const,
    TAGLINE: {
uuid: 'bd84eebf-a9bc-529c-a90a-14691780243e',
      id: 'UI_SPLASH_LOGO_TAGLINE',
      path: 'splash.logo.display.tagline',
      lifecycle: 'active',
      description: 'Splash screen tagline below heading',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
  },
  MAINTENANCE: {
    CONTAINER: {
uuid: 'a235a578-904e-54f5-9041-2cbeb7eff38b',
      id: 'UI_SPLASH_MAINTENANCE_CONTAINER',
      path: 'splash.maintenance.layout.container',
      lifecycle: 'active',
      description: 'Maintenance screen container',
      category: 'container',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    CARD: {
uuid: '14c91eff-9944-5b24-988f-b5e5d8b9ed5a',
      id: 'UI_SPLASH_MAINTENANCE_CARD',
      path: 'splash.maintenance.layout.card',
      lifecycle: 'active',
      description: 'Maintenance card',
      category: 'container',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    ICON_CONTAINER: {
uuid: 'fb260840-b067-55bb-bab9-64428f565add',
      id: 'UI_SPLASH_MAINTENANCE_ICON_CONTAINER',
      path: 'splash.maintenance.layout.icon-container',
      lifecycle: 'active',
      description: 'Maintenance icon container',
      category: 'container',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    TITLE: {
uuid: '1112ba89-0bbc-5780-b18c-de439b753d52',
      id: 'UI_SPLASH_MAINTENANCE_TITLE',
      path: 'splash.maintenance.display.title',
      lifecycle: 'active',
      description: 'Maintenance screen title',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    DEFAULT_MESSAGE: {
uuid: 'a2dc337a-d336-530b-bb13-20d832217539',
      id: 'UI_SPLASH_MAINTENANCE_DEFAULT_MESSAGE',
      path: 'splash.maintenance.display.default-message',
      lifecycle: 'active',
      description: 'Maintenance default message',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    INVALID_CODE: {
uuid: 'e59899fc-53e8-54c3-b61f-2a66fa2e656d',
      id: 'UI_SPLASH_MAINTENANCE_INVALID_CODE',
      path: 'splash.maintenance.display.invalid-code',
      lifecycle: 'active',
      description: 'Invalid maintenance access code error',
      category: 'display',
      feature: 'splash',
      version: '1.0.0',
      createdAt: '2026-06-17',
      updatedAt: '2026-06-17',
} as const,
    FORM: {
      PIN_INPUT: {
uuid: 'ff1c9368-f143-5fd5-a597-4872abab0707',
        id: 'UI_SPLASH_MAINT_PIN',
        path: 'splash.maintenance.form.pin-input',
        lifecycle: 'active',
        description: 'Developer bypass PIN input',
        category: 'input',
        feature: 'splash',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
} as const,
      SUBMIT_BUTTON: {
uuid: '65d3a501-473f-5a8e-83d2-166badfe1980',
        id: 'UI_SPLASH_MAINT_SUBMIT',
        path: 'splash.maintenance.form.submit-button',
        lifecycle: 'active',
        description: 'Bypass maintenance mode button',
        category: 'action',
        feature: 'splash',
        version: '1.0.0',
        createdAt: '2026-06-15',
        updatedAt: '2026-06-15',
} as const,
    },
  },
} as const;

// ============================================================================
// ERROR BOUNDARY IDENTIFIERS
// ============================================================================
