/**
 * HTML Components - Generated by Factory Pattern
 * 
 * All HTML elements as UI-identified components
 */

import { createUiComponent } from './component-factory';

// ============================================================================
// STRUCTURAL ELEMENTS
// ============================================================================

export const UiDiv = createUiComponent('div', 'UiDiv');
export const UiSpan = createUiComponent('span', 'UiSpan');
export const UiHeader = createUiComponent('header', 'UiHeader');
export const UiNav = createUiComponent('nav', 'UiNav');
export const UiMain = createUiComponent('main', 'UiMain');
export const UiSection = createUiComponent('section', 'UiSection');
export const UiArticle = createUiComponent('article', 'UiArticle');
export const UiAside = createUiComponent('aside', 'UiAside');
export const UiFooter = createUiComponent('footer', 'UiFooter');

// ============================================================================
// HEADINGS
// ============================================================================

export const UiH1 = createUiComponent('h1', 'UiH1');
export const UiH2 = createUiComponent('h2', 'UiH2');
export const UiH3 = createUiComponent('h3', 'UiH3');
export const UiH4 = createUiComponent('h4', 'UiH4');
export const UiH5 = createUiComponent('h5', 'UiH5');
export const UiH6 = createUiComponent('h6', 'UiH6');

// ============================================================================
// TEXT ELEMENTS
// ============================================================================

export const UiP = createUiComponent('p', 'UiP');
export const UiStrong = createUiComponent('strong', 'UiStrong');
export const UiEm = createUiComponent('em', 'UiEm');

// ============================================================================
// LINKS
// ============================================================================

export const UiA = createUiComponent('a', 'UiA');

// ============================================================================
// MEDIA ELEMENTS
// ============================================================================

export const UiImg = createUiComponent('img', 'UiImg');
export const UiPicture = createUiComponent('picture', 'UiPicture');
export const UiFigure = createUiComponent('figure', 'UiFigure');
export const UiFigcaption = createUiComponent('figcaption', 'UiFigcaption');
export const UiVideo = createUiComponent('video', 'UiVideo');
export const UiAudio = createUiComponent('audio', 'UiAudio');
export const UiIframe = createUiComponent('iframe', 'UiIframe');

// ============================================================================
// LIST ELEMENTS
// ============================================================================

export const UiUl = createUiComponent('ul', 'UiUl');
export const UiOl = createUiComponent('ol', 'UiOl');
export const UiLi = createUiComponent('li', 'UiLi');

// ============================================================================
// TABLE ELEMENTS
// ============================================================================

export const UiTable = createUiComponent('table', 'UiTable');
export const UiThead = createUiComponent('thead', 'UiThead');
export const UiTbody = createUiComponent('tbody', 'UiTbody');
export const UiTr = createUiComponent('tr', 'UiTr');
export const UiTh = createUiComponent('th', 'UiTh');
export const UiTd = createUiComponent('td', 'UiTd');

// ============================================================================
// FORM ELEMENTS
// ============================================================================

export const UiForm = createUiComponent('form', 'UiForm');
export const UiInput = createUiComponent('input', 'UiInput');
export const UiTextarea = createUiComponent('textarea', 'UiTextarea');
export const UiSelect = createUiComponent('select', 'UiSelect');
export const UiOption = createUiComponent('option', 'UiOption');
export const UiButton = createUiComponent('button', 'UiButton');
export const UiLabel = createUiComponent('label', 'UiLabel');
export const UiFieldset = createUiComponent('fieldset', 'UiFieldset');
export const UiLegend = createUiComponent('legend', 'UiLegend');

// ============================================================================
// DIALOG ELEMENTS
// ============================================================================

export const UiDialog = createUiComponent('dialog', 'UiDialog');
export const UiDetails = createUiComponent('details', 'UiDetails');
export const UiSummary = createUiComponent('summary', 'UiSummary');

// ============================================================================
// GRAPHICS ELEMENTS
// ============================================================================

export const UiCanvas = createUiComponent('canvas', 'UiCanvas');
export const UiSvg = createUiComponent('svg', 'UiSvg');

// ============================================================================
// TEMPLATE ELEMENTS
// ============================================================================

export const UiTemplate = createUiComponent('template', 'UiTemplate');
export const UiSlot = createUiComponent('slot', 'UiSlot');

// ============================================================================
// SPACING ELEMENTS
// ============================================================================

export const UiBr = createUiComponent('br', 'UiBr');
export const UiHr = createUiComponent('hr', 'UiHr');

// ============================================================================
// CODE ELEMENTS
// ============================================================================

export const UiCode = createUiComponent('code', 'UiCode');
export const UiPre = createUiComponent('pre', 'UiPre');
