/**
 * Automatically generated by audit-unified-ui-i18n.ts.
 * Do not edit this file manually.
 */

export interface UiSourceLocation {
  id: string;
  path: string;
  sourceFile: string;
  sourceComponent: string;
  sourceLine: number;
  feature: string;
}

export const UI_SOURCE_INDEX: Record<string, UiSourceLocation> = {
  "UI_HOME_CATEGORIES_CONTAINER": {
    "id": "UI_HOME_CATEGORIES_CONTAINER",
    "path": "home.categories-grid.container.wrapper",
    "sourceFile": "/src/components/home/CategoriesGrid.tsx",
    "sourceComponent": "CategoriesGrid",
    "sourceLine": 65,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_TOGGLE": {
    "id": "UI_HOME_CATEGORIES_GRID_TOGGLE",
    "path": "home.categories-grid.actions.toggle-button",
    "sourceFile": "/src/components/home/CategoriesGrid.tsx",
    "sourceComponent": "CategoriesGrid",
    "sourceLine": 96,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_ITEM": {
    "id": "UI_HOME_CATEGORIES_GRID_ITEM",
    "path": "home.categories-grid.actions.category-button",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 11,
    "feature": "home"
  },
  "UI_HOME_CURATED_CONTAINER": {
    "id": "UI_HOME_CURATED_CONTAINER",
    "path": "home.curated-offers.container.wrapper",
    "sourceFile": "/src/components/home/CuratedOffers.tsx",
    "sourceComponent": "CuratedOffers",
    "sourceLine": 57,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_MORE": {
    "id": "UI_HOME_CURATED_OFFERS_MORE",
    "path": "home.curated-offers.actions.show-more-button",
    "sourceFile": "/src/components/home/CuratedOffers.tsx",
    "sourceComponent": "CuratedOffers",
    "sourceLine": 141,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_ADD_TO_CART": {
    "id": "UI_HOME_CURATED_OFFERS_ADD_TO_CART",
    "path": "home.curated-offers.actions.add-to-cart-button",
    "sourceFile": "/src/components/home/CuratedOffers.tsx",
    "sourceComponent": "CuratedOffers",
    "sourceLine": 99,
    "feature": "home"
  },
  "UI_HOME_FEATURED_MARQUEE_CONTAINER": {
    "id": "UI_HOME_FEATURED_MARQUEE_CONTAINER",
    "path": "home.featured-marquee.container.wrapper",
    "sourceFile": "/src/components/home/FeaturedMarquee.tsx",
    "sourceComponent": "FeaturedMarquee",
    "sourceLine": 48,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_CONTAINER": {
    "id": "UI_HOME_HERO_SLIDER_CONTAINER",
    "path": "home.hero-slider.container.wrapper",
    "sourceFile": "/src/components/home/HeroSlider.tsx",
    "sourceComponent": "HeroSlider",
    "sourceLine": 44,
    "feature": "home"
  },
  "UI_HOME_PROMO_CONTAINER": {
    "id": "UI_HOME_PROMO_CONTAINER",
    "path": "home.promo-banner.container.wrapper",
    "sourceFile": "/src/components/home/PromoBanner.tsx",
    "sourceComponent": "PromoBanner",
    "sourceLine": 14,
    "feature": "home"
  },
  "UI_HOME_PROMO_TITLE": {
    "id": "UI_HOME_PROMO_TITLE",
    "path": "home.promo-banner.display.title",
    "sourceFile": "/src/components/home/PromoBanner.tsx",
    "sourceComponent": "PromoBanner",
    "sourceLine": 23,
    "feature": "home"
  },
  "UI_HOME_PROMO_TEXT": {
    "id": "UI_HOME_PROMO_TEXT",
    "path": "home.promo-banner.display.text",
    "sourceFile": "/src/components/home/PromoBanner.tsx",
    "sourceComponent": "PromoBanner",
    "sourceLine": 33,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_ACTION": {
    "id": "UI_HOME_PROMO_BANNER_ACTION",
    "path": "home.promo-banner.actions.banner-button",
    "sourceFile": "/src/components/home/PromoBanner.tsx",
    "sourceComponent": "PromoBanner",
    "sourceLine": 41,
    "feature": "home"
  },
  "UI_HOME_TRENDING_RIBBON_CONTAINER": {
    "id": "UI_HOME_TRENDING_RIBBON_CONTAINER",
    "path": "home.trending-ribbon.container.wrapper",
    "sourceFile": "/src/components/home/TrendingRibbon.tsx",
    "sourceComponent": "TrendingRibbon",
    "sourceLine": 25,
    "feature": "home"
  },
  "UI_SHARED_HEADER_CONTAINER": {
    "id": "UI_SHARED_HEADER_CONTAINER",
    "path": "shared-layout.header.container.wrapper",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 14,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_MENU": {
    "id": "UI_SHARED_HEADER_MENU",
    "path": "shared-layout.header.menu.menu-button",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 32,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_BRAND_LINK": {
    "id": "UI_SHARED_HEADER_BRAND_LINK",
    "path": "shared-layout.header.brand.brand-link",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 43,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_BUTTON": {
    "id": "UI_SHARED_HEADER_SEARCH_BUTTON",
    "path": "shared-layout.header.actions.search-button",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 74,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_CART_BUTTON": {
    "id": "UI_SHARED_HEADER_CART_BUTTON",
    "path": "shared-layout.header.actions.cart-button",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 87,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_INPUT": {
    "id": "UI_SHARED_HEADER_SEARCH_INPUT",
    "path": "shared-layout.header.actions.search-input",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 65,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_CONTAINER": {
    "id": "UI_SHARED_BOTTOM_NAV_CONTAINER",
    "path": "shared-layout.bottom-nav.container.wrapper",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 26,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_HOME": {
    "id": "UI_SHARED_BOTTOM_NAV_HOME",
    "path": "shared-layout.bottom-nav.items.home-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 12,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS": {
    "id": "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS",
    "path": "shared-layout.bottom-nav.items.notifications-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 13,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_FAVORITES": {
    "id": "UI_SHARED_BOTTOM_NAV_FAVORITES",
    "path": "shared-layout.bottom-nav.items.favorites-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 14,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_ORDERS": {
    "id": "UI_SHARED_BOTTOM_NAV_ORDERS",
    "path": "shared-layout.bottom-nav.items.orders-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 15,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_PROFILE": {
    "id": "UI_SHARED_BOTTOM_NAV_PROFILE",
    "path": "shared-layout.bottom-nav.items.profile-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 16,
    "feature": "shared-layout"
  },
  "UI_ERROR_BOUNDARY_CONTAINER": {
    "id": "UI_ERROR_BOUNDARY_CONTAINER",
    "path": "error-boundary.main.container.wrapper",
    "sourceFile": "/src/components/shared/error-boundary.tsx",
    "sourceComponent": "error-boundary",
    "sourceLine": 54,
    "feature": "error-boundary"
  },
  "UI_ERROR_BOUNDARY_TITLE": {
    "id": "UI_ERROR_BOUNDARY_TITLE",
    "path": "error-boundary.main.display.title",
    "sourceFile": "/src/components/shared/error-boundary.tsx",
    "sourceComponent": "error-boundary",
    "sourceLine": 61,
    "feature": "error-boundary"
  },
  "UI_ERROR_BOUNDARY_TEXT": {
    "id": "UI_ERROR_BOUNDARY_TEXT",
    "path": "error-boundary.main.display.text",
    "sourceFile": "/src/components/shared/error-boundary.tsx",
    "sourceComponent": "error-boundary",
    "sourceLine": 69,
    "feature": "error-boundary"
  },
  "UI_ERROR_BOUNDARY_RELOAD": {
    "id": "UI_ERROR_BOUNDARY_RELOAD",
    "path": "error-boundary.main.actions.reload-button",
    "sourceFile": "/src/components/shared/error-boundary.tsx",
    "sourceComponent": "error-boundary",
    "sourceLine": 76,
    "feature": "error-boundary"
  },
  "UI_HOME_LANG_CONTAINER": {
    "id": "UI_HOME_LANG_CONTAINER",
    "path": "home.language-switcher.container.wrapper",
    "sourceFile": "/src/components/shared/LanguageSwitcher.tsx",
    "sourceComponent": "LanguageSwitcher",
    "sourceLine": 19,
    "feature": "home"
  },
  "UI_HOME_LANG_ENGLISH": {
    "id": "UI_HOME_LANG_ENGLISH",
    "path": "home.language-switcher.buttons.english-button",
    "sourceFile": "/src/components/shared/LanguageSwitcher.tsx",
    "sourceComponent": "LanguageSwitcher",
    "sourceLine": 25,
    "feature": "home"
  },
  "UI_HOME_LANG_ARABIC": {
    "id": "UI_HOME_LANG_ARABIC",
    "path": "home.language-switcher.buttons.arabic-button",
    "sourceFile": "/src/components/shared/LanguageSwitcher.tsx",
    "sourceComponent": "LanguageSwitcher",
    "sourceLine": 33,
    "feature": "home"
  },
  "UI_SPLASH_CONTAINER": {
    "id": "UI_SPLASH_CONTAINER",
    "path": "splash.main.container.wrapper",
    "sourceFile": "/src/components/splash/SplashScreen.tsx",
    "sourceComponent": "SplashScreen",
    "sourceLine": 73,
    "feature": "splash"
  },
  "UI_SPLASH_STATUS_TEXT": {
    "id": "UI_SPLASH_STATUS_TEXT",
    "path": "splash.main.display.status-text",
    "sourceFile": "/src/components/splash/ProgressIndicator.tsx",
    "sourceComponent": "ProgressIndicator",
    "sourceLine": 54,
    "feature": "splash"
  },
  "UI_SPLASH_PROGRESS_BAR": {
    "id": "UI_SPLASH_PROGRESS_BAR",
    "path": "splash.main.display.progress-bar",
    "sourceFile": "/src/components/splash/ProgressIndicator.tsx",
    "sourceComponent": "ProgressIndicator",
    "sourceLine": 66,
    "feature": "splash"
  },
  "UI_SPLASH_TITLE": {
    "id": "UI_SPLASH_TITLE",
    "path": "splash.main.display.title",
    "sourceFile": "/src/components/splash/SplashScreen.tsx",
    "sourceComponent": "SplashScreen",
    "sourceLine": 138,
    "feature": "splash"
  },
  "UI_SPLASH_SUBTITLE": {
    "id": "UI_SPLASH_SUBTITLE",
    "path": "splash.main.display.subtitle",
    "sourceFile": "/src/components/splash/SplashScreen.tsx",
    "sourceComponent": "SplashScreen",
    "sourceLine": 146,
    "feature": "splash"
  },
  "UI_SPLASH_MAINT_PIN": {
    "id": "UI_SPLASH_MAINT_PIN",
    "path": "splash.maintenance.form.pin-input",
    "sourceFile": "/src/components/splash/SplashScreen.tsx",
    "sourceComponent": "SplashScreen",
    "sourceLine": 90,
    "feature": "splash"
  },
  "UI_SPLASH_MAINT_SUBMIT": {
    "id": "UI_SPLASH_MAINT_SUBMIT",
    "path": "splash.maintenance.form.submit-button",
    "sourceFile": "/src/components/splash/SplashScreen.tsx",
    "sourceComponent": "SplashScreen",
    "sourceLine": 107,
    "feature": "splash"
  }
};
