/**
 * Automatically generated by audit-unified-ui-i18n.ts.
 * Do not edit this file manually.
 */

export interface UiSourceLocation {
  id: string;
  path: string;
  sourceFile: string;
  sourceComponent: string;
  sourceLine: number;
  feature: string;
}

export const UI_SOURCE_INDEX: Record<string, UiSourceLocation> = {
  "UI_HOME_CATEGORIES_GRID_TOGGLE": {
    "id": "UI_HOME_CATEGORIES_GRID_TOGGLE",
    "path": "home.categories-grid.actions.toggle-button",
    "sourceFile": "/src/components/home/CategoriesGrid.tsx",
    "sourceComponent": "CategoriesGrid",
    "sourceLine": 90,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_ITEM": {
    "id": "UI_HOME_CATEGORIES_GRID_ITEM",
    "path": "home.categories-grid.actions.category-button",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 11,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_MORE": {
    "id": "UI_HOME_CURATED_OFFERS_MORE",
    "path": "home.curated-offers.actions.show-more-button",
    "sourceFile": "/src/components/home/CuratedOffers.tsx",
    "sourceComponent": "CuratedOffers",
    "sourceLine": 135,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_ADD_TO_CART": {
    "id": "UI_HOME_CURATED_OFFERS_ADD_TO_CART",
    "path": "home.curated-offers.actions.add-to-cart-button",
    "sourceFile": "/src/components/home/CuratedOffers.tsx",
    "sourceComponent": "CuratedOffers",
    "sourceLine": 118,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_FAVORITE": {
    "id": "UI_HOME_CURATED_OFFERS_FAVORITE",
    "path": "home.curated-offers.actions.add-to-favorites-button",
    "sourceFile": "/src/components/home/CuratedOffers.tsx",
    "sourceComponent": "CuratedOffers",
    "sourceLine": 93,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_ACTION": {
    "id": "UI_HOME_PROMO_BANNER_ACTION",
    "path": "home.promo-banner.actions.banner-button",
    "sourceFile": "/src/components/home/PromoBanner.tsx",
    "sourceComponent": "PromoBanner",
    "sourceLine": 29,
    "feature": "home"
  },
  "UI_SHARED_HEADER_MENU": {
    "id": "UI_SHARED_HEADER_MENU",
    "path": "shared-layout.header.menu.menu-button",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 29,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_BRAND_LINK": {
    "id": "UI_SHARED_HEADER_BRAND_LINK",
    "path": "shared-layout.header.brand.brand-link",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 40,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_BUTTON": {
    "id": "UI_SHARED_HEADER_SEARCH_BUTTON",
    "path": "shared-layout.header.actions.search-button",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 71,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_CART_BUTTON": {
    "id": "UI_SHARED_HEADER_CART_BUTTON",
    "path": "shared-layout.header.actions.cart-button",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 84,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_INPUT": {
    "id": "UI_SHARED_HEADER_SEARCH_INPUT",
    "path": "shared-layout.header.actions.search-input",
    "sourceFile": "/src/components/layouts/AppHeader.tsx",
    "sourceComponent": "AppHeader",
    "sourceLine": 62,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_HOME": {
    "id": "UI_SHARED_BOTTOM_NAV_HOME",
    "path": "shared-layout.bottom-nav.items.home-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 12,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS": {
    "id": "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS",
    "path": "shared-layout.bottom-nav.items.notifications-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 13,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_FAVORITES": {
    "id": "UI_SHARED_BOTTOM_NAV_FAVORITES",
    "path": "shared-layout.bottom-nav.items.favorites-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 14,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_ORDERS": {
    "id": "UI_SHARED_BOTTOM_NAV_ORDERS",
    "path": "shared-layout.bottom-nav.items.orders-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 15,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_PROFILE": {
    "id": "UI_SHARED_BOTTOM_NAV_PROFILE",
    "path": "shared-layout.bottom-nav.items.profile-link",
    "sourceFile": "/src/components/layouts/BottomNavBar.tsx",
    "sourceComponent": "BottomNavBar",
    "sourceLine": 16,
    "feature": "shared-layout"
  },
  "UI_ERROR_BOUNDARY_RELOAD": {
    "id": "UI_ERROR_BOUNDARY_RELOAD",
    "path": "error-boundary.main.actions.reload-button",
    "sourceFile": "/src/components/shared/error-boundary.tsx",
    "sourceComponent": "error-boundary",
    "sourceLine": 61,
    "feature": "error-boundary"
  },
  "UI_HOME_LANG_ENGLISH": {
    "id": "UI_HOME_LANG_ENGLISH",
    "path": "home.language-switcher.buttons.english-button",
    "sourceFile": "/src/components/shared/LanguageSwitcher.tsx",
    "sourceComponent": "LanguageSwitcher",
    "sourceLine": 20,
    "feature": "home"
  },
  "UI_HOME_LANG_ARABIC": {
    "id": "UI_HOME_LANG_ARABIC",
    "path": "home.language-switcher.buttons.arabic-button",
    "sourceFile": "/src/components/shared/LanguageSwitcher.tsx",
    "sourceComponent": "LanguageSwitcher",
    "sourceLine": 28,
    "feature": "home"
  },
  "UI_SPLASH_MAINT_PIN": {
    "id": "UI_SPLASH_MAINT_PIN",
    "path": "splash.maintenance.form.pin-input",
    "sourceFile": "/src/components/splash/SplashScreen.tsx",
    "sourceComponent": "SplashScreen",
    "sourceLine": 87,
    "feature": "splash"
  },
  "UI_SPLASH_MAINT_SUBMIT": {
    "id": "UI_SPLASH_MAINT_SUBMIT",
    "path": "splash.maintenance.form.submit-button",
    "sourceFile": "/src/components/splash/SplashScreen.tsx",
    "sourceComponent": "SplashScreen",
    "sourceLine": 104,
    "feature": "splash"
  }
};
