export type {
  DatabaseRefColumn,
  DatabaseRefDatabase,
  DatabaseRefFile,
  DatabaseRefTable,
  DatabaseEnabledState,
} from './ui-inspector/data/database-ref.types';

export {
  emptyDatabaseRefFile,
  normalizeDatabaseRefFile,
  findDatabase,
  findTable,
  findColumn,
  cloneDatabaseRefFile,
  uniqueEnName,
  getEntityDescription,
  validateEnName,
  addDatabase,
  renameDatabase,
  deleteDatabase,
  addTable,
  renameTable,
  deleteTable,
  addColumn,
  renameColumn,
  deleteColumn,
  applyDescriptionUpdate,
  remapElementFieldNames,
} from './ui-inspector/data/database-ref-utils';
