/**
 * Automatically generated by audit-unified-ui-i18n.ts.
 * Do not edit this file manually.
 */

export interface UiSourceLocation {
  id: string;
  path: string;
  sourceFile: string;
  sourceComponent: string;
  sourceLine: number;
  feature: string;
}

export const UI_SOURCE_INDEX: Record<string, UiSourceLocation> = {
  "UI_SPLASH_MAINTENANCE_CARD": {
    "id": "UI_SPLASH_MAINTENANCE_CARD",
    "path": "splash.maintenance.layout.card",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 46,
    "feature": "splash"
  },
  "UI_AUTH_SHARED_PAGE": {
    "id": "UI_AUTH_SHARED_PAGE",
    "path": "auth.shared.layout.page",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 280,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_FORM_CARD": {
    "id": "UI_AUTH_SHARED_FORM_CARD",
    "path": "auth.shared.layout.form-card",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 104,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_HERO": {
    "id": "UI_AUTH_SHARED_HERO",
    "path": "auth.shared.layout.hero",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 269,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_BRAND_ROW": {
    "id": "UI_AUTH_SHARED_BRAND_ROW",
    "path": "auth.shared.display.brand-row",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 24,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_BRAND_ICON": {
    "id": "UI_AUTH_SHARED_BRAND_ICON",
    "path": "auth.shared.display.brand-icon",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 34,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_HERO_QUOTE": {
    "id": "UI_AUTH_SHARED_HERO_QUOTE",
    "path": "auth.shared.display.hero-quote-block",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 44,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_HERO_HIGHLIGHTS": {
    "id": "UI_AUTH_SHARED_HERO_HIGHLIGHTS",
    "path": "auth.shared.display.hero-highlights",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 54,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_HERO_DECOR": {
    "id": "UI_AUTH_SHARED_HERO_DECOR",
    "path": "auth.shared.layout.hero-decor",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 64,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_HIGHLIGHT_SECURITY": {
    "id": "UI_AUTH_SHARED_HIGHLIGHT_SECURITY",
    "path": "auth.shared.display.highlight-security",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 74,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_HIGHLIGHT_PHONE": {
    "id": "UI_AUTH_SHARED_HIGHLIGHT_PHONE",
    "path": "auth.shared.display.highlight-phone",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 84,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_HIGHLIGHT_ENCRYPTED": {
    "id": "UI_AUTH_SHARED_HIGHLIGHT_ENCRYPTED",
    "path": "auth.shared.display.highlight-encrypted",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 94,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_HERO_QUOTE": {
    "id": "UI_AUTH_LOGIN_HERO_QUOTE",
    "path": "auth.login.display.hero-quote",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 44,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_HERO_FOOTER": {
    "id": "UI_AUTH_LOGIN_HERO_FOOTER",
    "path": "auth.login.display.hero-footer",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 176,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_BRAND_NAME": {
    "id": "UI_AUTH_REGISTRATION_BRAND_NAME",
    "path": "auth.registration.brand-name",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 308,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_HEADING": {
    "id": "UI_AUTH_REGISTRATION_HEADING",
    "path": "auth.registration.heading",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 320,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_DESCRIPTION": {
    "id": "UI_AUTH_REGISTRATION_DESCRIPTION",
    "path": "auth.registration.description",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 330,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_MOBILE_BRAND": {
    "id": "UI_AUTH_SHARED_MOBILE_BRAND",
    "path": "auth.shared.display.mobile-brand",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 114,
    "feature": "auth"
  },
  "UI_HOME_CATEGORIES_GRID_TOGGLE": {
    "id": "UI_HOME_CATEGORIES_GRID_TOGGLE",
    "path": "home.categories-grid.actions.toggle-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 246,
    "feature": "home"
  },
  "UI_AUTH_SHARED_PHONE_PLACEHOLDER": {
    "id": "UI_AUTH_SHARED_PHONE_PLACEHOLDER",
    "path": "auth.shared.phone-placeholder",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 124,
    "feature": "auth"
  },
  "UI_AUTH_SHARED_PASSWORD_PLACEHOLDER": {
    "id": "UI_AUTH_SHARED_PASSWORD_PLACEHOLDER",
    "path": "auth.shared.password-placeholder",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 134,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_HEADING": {
    "id": "UI_AUTH_LOGIN_HEADING",
    "path": "auth.login.display.heading",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 148,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SUBHEADING": {
    "id": "UI_AUTH_LOGIN_SUBHEADING",
    "path": "auth.login.display.subheading",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 156,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_PHONE_INPUT": {
    "id": "UI_AUTH_LOGIN_PHONE_INPUT",
    "path": "auth.login.form.phone-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 188,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_PASSWORD_INPUT": {
    "id": "UI_AUTH_LOGIN_PASSWORD_INPUT",
    "path": "auth.login.form.password-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 198,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_FORGOT_PASSWORD": {
    "id": "UI_AUTH_LOGIN_FORGOT_PASSWORD",
    "path": "auth.login.form.forgot-password-link",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 206,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_TOGGLE_PASSWORD": {
    "id": "UI_AUTH_LOGIN_TOGGLE_PASSWORD",
    "path": "auth.login.toggle-password-visibility",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 218,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SUBMIT": {
    "id": "UI_AUTH_LOGIN_SUBMIT",
    "path": "auth.login.form.submit-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 228,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SUBMITTING": {
    "id": "UI_AUTH_LOGIN_SUBMITTING",
    "path": "auth.login.submitting-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 238,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_GUEST": {
    "id": "UI_AUTH_LOGIN_GUEST",
    "path": "auth.login.actions.guest-login-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 246,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SIGNUP_LINK": {
    "id": "UI_AUTH_LOGIN_SIGNUP_LINK",
    "path": "auth.login.actions.signup-link",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 256,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SIGNUP_DIVIDER": {
    "id": "UI_AUTH_LOGIN_SIGNUP_DIVIDER",
    "path": "auth.login.display.signup-divider",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 266,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SUCCESS_HEADING": {
    "id": "UI_AUTH_LOGIN_SUCCESS_HEADING",
    "path": "auth.login.display.success-heading",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 278,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SUCCESS_DESCRIPTION": {
    "id": "UI_AUTH_LOGIN_SUCCESS_DESCRIPTION",
    "path": "auth.login.display.success-description",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 288,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SIGNIN_AGAIN": {
    "id": "UI_AUTH_LOGIN_SIGNIN_AGAIN",
    "path": "auth.login.actions.signin-again-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 296,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_PASSWORD_INPUT": {
    "id": "UI_AUTH_REGISTRATION_PASSWORD_INPUT",
    "path": "auth.registration.password-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 450,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_CONFIRM_PASSWORD": {
    "id": "UI_AUTH_REGISTRATION_CONFIRM_PASSWORD",
    "path": "auth.registration.confirm-password-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 458,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_TOGGLE_PASSWORD": {
    "id": "UI_AUTH_REGISTRATION_TOGGLE_PASSWORD",
    "path": "auth.registration.toggle-password-visibility",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 470,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_PASSWORD_STRENGTH": {
    "id": "UI_AUTH_REGISTRATION_PASSWORD_STRENGTH",
    "path": "auth.registration.password-strength-label",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 478,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_STRENGTH_WEAK": {
    "id": "UI_AUTH_REGISTRATION_STRENGTH_WEAK",
    "path": "auth.registration.strength-weak",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 488,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_STRENGTH_FAIR": {
    "id": "UI_AUTH_REGISTRATION_STRENGTH_FAIR",
    "path": "auth.registration.strength-fair",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 498,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_STRENGTH_GOOD": {
    "id": "UI_AUTH_REGISTRATION_STRENGTH_GOOD",
    "path": "auth.registration.strength-good",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 508,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_STRENGTH_STRONG": {
    "id": "UI_AUTH_REGISTRATION_STRENGTH_STRONG",
    "path": "auth.registration.strength-strong",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 518,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_REQ_MIN": {
    "id": "UI_AUTH_REGISTRATION_REQ_MIN",
    "path": "auth.registration.req-min-length",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 528,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_REQ_UPPER": {
    "id": "UI_AUTH_REGISTRATION_REQ_UPPER",
    "path": "auth.registration.req-uppercase",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 538,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_REQ_LOWER": {
    "id": "UI_AUTH_REGISTRATION_REQ_LOWER",
    "path": "auth.registration.req-lowercase",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 548,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_REQ_NUMBER": {
    "id": "UI_AUTH_REGISTRATION_REQ_NUMBER",
    "path": "auth.registration.req-number",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 558,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_REQ_SPECIAL": {
    "id": "UI_AUTH_REGISTRATION_REQ_SPECIAL",
    "path": "auth.registration.req-special",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 568,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_PHONE_INPUT": {
    "id": "UI_AUTH_REGISTRATION_PHONE_INPUT",
    "path": "auth.registration.phone-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 360,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_VERIFY_BUTTON": {
    "id": "UI_AUTH_REGISTRATION_VERIFY_BUTTON",
    "path": "auth.registration.verify-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 368,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_EDIT_BUTTON": {
    "id": "UI_AUTH_REGISTRATION_EDIT_BUTTON",
    "path": "auth.registration.edit-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 378,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_OTP_LABEL": {
    "id": "UI_AUTH_REGISTRATION_OTP_LABEL",
    "path": "auth.registration.otp-label",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 388,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_OTP_DESCRIPTION": {
    "id": "UI_AUTH_REGISTRATION_OTP_DESCRIPTION",
    "path": "auth.registration.otp-description",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 398,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_OTP_INPUT": {
    "id": "UI_AUTH_REGISTRATION_OTP_INPUT",
    "path": "auth.registration.otp-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 408,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_RESEND_BUTTON": {
    "id": "UI_AUTH_REGISTRATION_RESEND_BUTTON",
    "path": "auth.registration.resend-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 418,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_VERIFY_OTP": {
    "id": "UI_AUTH_REGISTRATION_VERIFY_OTP",
    "path": "auth.registration.verify-otp-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 428,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_PHONE_VERIFIED": {
    "id": "UI_AUTH_REGISTRATION_PHONE_VERIFIED",
    "path": "auth.registration.phone-verified-message",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 438,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_VERIFYING_OTP": {
    "id": "UI_AUTH_REGISTRATION_VERIFYING_OTP",
    "path": "auth.registration.verifying-otp-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 578,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_TITLE": {
    "id": "UI_AUTH_REGISTRATION_TITLE",
    "path": "auth.registration.title",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 340,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_CARD_DESCRIPTION": {
    "id": "UI_AUTH_REGISTRATION_CARD_DESCRIPTION",
    "path": "auth.registration.card-description",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 348,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_SUBMITTING": {
    "id": "UI_AUTH_REGISTRATION_SUBMITTING",
    "path": "auth.registration.submitting-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 590,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_PHONE_REQUIRED": {
    "id": "UI_AUTH_REGISTRATION_PHONE_REQUIRED",
    "path": "auth.registration.phone-required-notice",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 598,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_SUBMIT": {
    "id": "UI_AUTH_REGISTRATION_SUBMIT",
    "path": "auth.registration.submit-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 610,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_SIGNIN_LINK": {
    "id": "UI_AUTH_REGISTRATION_SIGNIN_LINK",
    "path": "auth.registration.signin-link",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 618,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_SIGNIN_PROMPT": {
    "id": "UI_AUTH_REGISTRATION_SIGNIN_PROMPT",
    "path": "auth.registration.signin-prompt",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 628,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_SUCCESS_HEADING": {
    "id": "UI_AUTH_REGISTRATION_SUCCESS_HEADING",
    "path": "auth.registration.success-heading",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 640,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_SUCCESS_DESCRIPTION": {
    "id": "UI_AUTH_REGISTRATION_SUCCESS_DESCRIPTION",
    "path": "auth.registration.success-description",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 650,
    "feature": "auth"
  },
  "UI_AUTH_REGISTRATION_CONTINUE": {
    "id": "UI_AUTH_REGISTRATION_CONTINUE",
    "path": "auth.registration.continue-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 658,
    "feature": "auth"
  },
  "UI_HOME_CATEGORIES_GRID_ITEM": {
    "id": "UI_HOME_CATEGORIES_GRID_ITEM",
    "path": "home.categories-grid.actions.category-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 112,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_CATEGORY_IMAGE": {
    "id": "UI_HOME_CATEGORIES_GRID_CATEGORY_IMAGE",
    "path": "home.categories-grid.display.category-image",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 372,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_CATEGORY_NAME": {
    "id": "UI_HOME_CATEGORIES_GRID_CATEGORY_NAME",
    "path": "home.categories-grid.display.category-name",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 382,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_SECTION_TITLE": {
    "id": "UI_HOME_CATEGORIES_GRID_SECTION_TITLE",
    "path": "home.categories-grid.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 394,
    "feature": "home"
  },
  "UI_SPLASH_LOGO_IMAGE": {
    "id": "UI_SPLASH_LOGO_IMAGE",
    "path": "splash.logo.display.logo-image",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 4,
    "feature": "splash"
  },
  "UI_HOME_CURATED_OFFERS_CONTAINER": {
    "id": "UI_HOME_CURATED_OFFERS_CONTAINER",
    "path": "home.curated-offers.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 100,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_HEADER": {
    "id": "UI_HOME_CURATED_OFFERS_HEADER",
    "path": "home.curated-offers.layout.header",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 110,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_GRID": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_GRID",
    "path": "home.curated-offers.layout.product-grid",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 118,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_CARD": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_CARD",
    "path": "home.curated-offers.layout.product-card",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 128,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE_CONTAINER": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE_CONTAINER",
    "path": "home.curated-offers.layout.product-image-container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 138,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_INFO": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_INFO",
    "path": "home.curated-offers.layout.product-info",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 148,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRICE_ROW": {
    "id": "UI_HOME_CURATED_OFFERS_PRICE_ROW",
    "path": "home.curated-offers.layout.price-row",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 158,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_SHOW_MORE_CONTAINER": {
    "id": "UI_HOME_CURATED_OFFERS_SHOW_MORE_CONTAINER",
    "path": "home.curated-offers.layout.show-more-container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 168,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_MORE": {
    "id": "UI_HOME_CURATED_OFFERS_MORE",
    "path": "home.curated-offers.actions.show-more-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 168,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_ADD_TO_CART": {
    "id": "UI_HOME_CURATED_OFFERS_ADD_TO_CART",
    "path": "home.curated-offers.actions.add-to-cart-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 188,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_FAVORITE": {
    "id": "UI_HOME_CURATED_OFFERS_FAVORITE",
    "path": "home.curated-offers.actions.add-to-favorites-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 198,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE",
    "path": "home.curated-offers.display.product-image",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 138,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_CATEGORY_LABEL": {
    "id": "UI_HOME_CURATED_OFFERS_CATEGORY_LABEL",
    "path": "home.curated-offers.display.category-label",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 218,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_TITLE": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_TITLE",
    "path": "home.curated-offers.display.product-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 228,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRICE_LABEL": {
    "id": "UI_HOME_CURATED_OFFERS_PRICE_LABEL",
    "path": "home.curated-offers.display.price-label",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 238,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_SECTION_TITLE": {
    "id": "UI_HOME_CURATED_OFFERS_SECTION_TITLE",
    "path": "home.curated-offers.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 250,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PROMO_TAG": {
    "id": "UI_HOME_CURATED_OFFERS_PROMO_TAG",
    "path": "home.curated-offers.display.promo-tag",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 258,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_CONTAINER": {
    "id": "UI_HOME_HERO_SLIDER_CONTAINER",
    "path": "home.hero-slider.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 272,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDER_TRACK": {
    "id": "UI_HOME_HERO_SLIDER_SLIDER_TRACK",
    "path": "home.hero-slider.layout.slider-track",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 280,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE",
    "path": "home.hero-slider.layout.slide",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 269,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_CONTENT": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_CONTENT",
    "path": "home.hero-slider.layout.slide-content",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 300,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_INDICATORS": {
    "id": "UI_HOME_HERO_SLIDER_INDICATORS",
    "path": "home.hero-slider.layout.indicators",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 310,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_IMAGE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_IMAGE",
    "path": "home.hero-slider.display.slide-image",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 320,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_TITLE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_TITLE",
    "path": "home.hero-slider.display.slide-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 330,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_BADGE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_BADGE",
    "path": "home.hero-slider.display.slide-badge",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 340,
    "feature": "home"
  },
  "UI_SHARED_SIDEBAR_CONTENT": {
    "id": "UI_SHARED_SIDEBAR_CONTENT",
    "path": "shared-layout.sidebar.layout.content",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 206,
    "feature": "shared-layout"
  },
  "UI_HOME_PROMO_BANNER_CONTAINER": {
    "id": "UI_HOME_PROMO_BANNER_CONTAINER",
    "path": "home.promo-banner.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 28,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_CONTENT_WRAPPER": {
    "id": "UI_HOME_PROMO_BANNER_CONTENT_WRAPPER",
    "path": "home.promo-banner.layout.content-wrapper",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 36,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_ACTION": {
    "id": "UI_HOME_PROMO_BANNER_ACTION",
    "path": "home.promo-banner.actions.banner-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 46,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_TITLE": {
    "id": "UI_HOME_PROMO_BANNER_TITLE",
    "path": "home.promo-banner.display.title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 58,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_DESCRIPTION": {
    "id": "UI_HOME_PROMO_BANNER_DESCRIPTION",
    "path": "home.promo-banner.display.description",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 68,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_LOGO": {
    "id": "UI_HOME_PROMO_BANNER_LOGO",
    "path": "home.promo-banner.display.logo",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 3,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_DECORATIVE_BACKGROUND": {
    "id": "UI_HOME_PROMO_BANNER_DECORATIVE_BACKGROUND",
    "path": "home.promo-banner.decorative.background",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 86,
    "feature": "home"
  },
  "UI_SHARED_HEADER_CONTAINER": {
    "id": "UI_SHARED_HEADER_CONTAINER",
    "path": "shared-layout.header.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 6,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_INNER_WRAPPER": {
    "id": "UI_SHARED_HEADER_INNER_WRAPPER",
    "path": "shared-layout.header.layout.inner-wrapper",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 14,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_BRAND_SECTION": {
    "id": "UI_SHARED_HEADER_BRAND_SECTION",
    "path": "shared-layout.header.layout.brand-section",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 24,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_ACTIONS_SECTION": {
    "id": "UI_SHARED_HEADER_ACTIONS_SECTION",
    "path": "shared-layout.header.layout.actions-section",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 36,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_MENU": {
    "id": "UI_SHARED_HEADER_MENU",
    "path": "shared-layout.header.menu.menu-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 45,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_BRAND_LINK": {
    "id": "UI_SHARED_HEADER_BRAND_LINK",
    "path": "shared-layout.header.brand.brand-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 57,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_BUTTON": {
    "id": "UI_SHARED_HEADER_SEARCH_BUTTON",
    "path": "shared-layout.header.actions.search-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 69,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_CART_BUTTON": {
    "id": "UI_SHARED_HEADER_CART_BUTTON",
    "path": "shared-layout.header.actions.cart-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 79,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_INPUT": {
    "id": "UI_SHARED_HEADER_SEARCH_INPUT",
    "path": "shared-layout.header.actions.search-input",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 89,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_CONTAINER": {
    "id": "UI_SHARED_SIDEBAR_CONTAINER",
    "path": "shared-layout.sidebar.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 168,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_OVERLAY": {
    "id": "UI_SHARED_SIDEBAR_OVERLAY",
    "path": "shared-layout.sidebar.layout.overlay",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 176,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_PANEL": {
    "id": "UI_SHARED_SIDEBAR_PANEL",
    "path": "shared-layout.sidebar.layout.panel",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 186,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_HEADER": {
    "id": "UI_SHARED_SIDEBAR_HEADER",
    "path": "shared-layout.sidebar.layout.header",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 198,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_ACTIONS_SECTION": {
    "id": "UI_SHARED_SIDEBAR_ACTIONS_SECTION",
    "path": "shared-layout.sidebar.layout.actions-section",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 218,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_CLOSE": {
    "id": "UI_SHARED_SIDEBAR_CLOSE",
    "path": "shared-layout.sidebar.actions.close-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 226,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_SETTINGS": {
    "id": "UI_SHARED_SIDEBAR_SETTINGS",
    "path": "shared-layout.sidebar.actions.settings-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 266,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_CONTAINER": {
    "id": "UI_SHARED_BOTTOM_NAV_CONTAINER",
    "path": "shared-layout.bottom-nav.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 104,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_HOME": {
    "id": "UI_SHARED_BOTTOM_NAV_HOME",
    "path": "shared-layout.bottom-nav.items.home-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 113,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS": {
    "id": "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS",
    "path": "shared-layout.bottom-nav.items.notifications-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 123,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_FAVORITES": {
    "id": "UI_SHARED_BOTTOM_NAV_FAVORITES",
    "path": "shared-layout.bottom-nav.items.favorites-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 133,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_ORDERS": {
    "id": "UI_SHARED_BOTTOM_NAV_ORDERS",
    "path": "shared-layout.bottom-nav.items.orders-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 143,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_PROFILE": {
    "id": "UI_SHARED_BOTTOM_NAV_PROFILE",
    "path": "shared-layout.bottom-nav.items.profile-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 153,
    "feature": "shared-layout"
  },
  "UI_ERROR_BOUNDARY_TITLE": {
    "id": "UI_ERROR_BOUNDARY_TITLE",
    "path": "error-boundary.main.display.title",
    "sourceFile": "/src/platform/ui/registry/features/error-boundary.ts",
    "sourceComponent": "ERROR_BOUNDARY",
    "sourceLine": 5,
    "feature": "error-boundary"
  },
  "UI_ERROR_BOUNDARY_DEFAULT_MESSAGE": {
    "id": "UI_ERROR_BOUNDARY_DEFAULT_MESSAGE",
    "path": "error-boundary.main.display.default-message",
    "sourceFile": "/src/platform/ui/registry/features/error-boundary.ts",
    "sourceComponent": "ERROR_BOUNDARY",
    "sourceLine": 15,
    "feature": "error-boundary"
  },
  "UI_ERROR_BOUNDARY_RELOAD": {
    "id": "UI_ERROR_BOUNDARY_RELOAD",
    "path": "error-boundary.main.actions.reload-button",
    "sourceFile": "/src/platform/ui/registry/features/error-boundary.ts",
    "sourceComponent": "ERROR_BOUNDARY",
    "sourceLine": 23,
    "feature": "error-boundary"
  },
  "UI_HOME_LANG_ENGLISH": {
    "id": "UI_HOME_LANG_ENGLISH",
    "path": "home.language-switcher.buttons.english-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 4,
    "feature": "home"
  },
  "UI_HOME_LANG_ARABIC": {
    "id": "UI_HOME_LANG_ARABIC",
    "path": "home.language-switcher.buttons.arabic-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 14,
    "feature": "home"
  },
  "UI_SPLASH_LOGO_HEADING": {
    "id": "UI_SPLASH_LOGO_HEADING",
    "path": "splash.logo.display.heading",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 16,
    "feature": "splash"
  },
  "UI_SPLASH_LOGO_TAGLINE": {
    "id": "UI_SPLASH_LOGO_TAGLINE",
    "path": "splash.logo.display.tagline",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 24,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_CONTAINER": {
    "id": "UI_SPLASH_MAINTENANCE_CONTAINER",
    "path": "splash.maintenance.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 38,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_ICON_CONTAINER": {
    "id": "UI_SPLASH_MAINTENANCE_ICON_CONTAINER",
    "path": "splash.maintenance.layout.icon-container",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 56,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_TITLE": {
    "id": "UI_SPLASH_MAINTENANCE_TITLE",
    "path": "splash.maintenance.display.title",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 68,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_DEFAULT_MESSAGE": {
    "id": "UI_SPLASH_MAINTENANCE_DEFAULT_MESSAGE",
    "path": "splash.maintenance.display.default-message",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 78,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_INVALID_CODE": {
    "id": "UI_SPLASH_MAINTENANCE_INVALID_CODE",
    "path": "splash.maintenance.display.invalid-code",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 86,
    "feature": "splash"
  },
  "UI_SPLASH_MAINT_PIN": {
    "id": "UI_SPLASH_MAINT_PIN",
    "path": "splash.maintenance.form.pin-input",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 97,
    "feature": "splash"
  },
  "UI_SPLASH_MAINT_SUBMIT": {
    "id": "UI_SPLASH_MAINT_SUBMIT",
    "path": "splash.maintenance.form.submit-button",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 109,
    "feature": "splash"
  },
  "UI_COMMON_CARD_CONTAINER": {
    "id": "UI_COMMON_CARD_CONTAINER",
    "path": "common.components.card.container",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 11,
    "feature": "common"
  },
  "UI_COMMON_CARD_TITLE": {
    "id": "UI_COMMON_CARD_TITLE",
    "path": "common.components.card.title",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 21,
    "feature": "common"
  },
  "UI_COMMON_MODAL_CONTAINER": {
    "id": "UI_COMMON_MODAL_CONTAINER",
    "path": "common.components.modal.container",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 33,
    "feature": "common"
  },
  "UI_COMMON_MODAL_TITLE": {
    "id": "UI_COMMON_MODAL_TITLE",
    "path": "common.components.modal.title",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 43,
    "feature": "common"
  },
  "UI_COMMON_MODAL_CLOSE": {
    "id": "UI_COMMON_MODAL_CLOSE",
    "path": "common.components.modal.close-button",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 53,
    "feature": "common"
  },
  "UI_COMMON_BADGE_LABEL": {
    "id": "UI_COMMON_BADGE_LABEL",
    "path": "common.components.badge.label",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 65,
    "feature": "common"
  },
  "UI_COMMON_FORMS_FORM": {
    "id": "UI_COMMON_FORMS_FORM",
    "path": "common.forms.form",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_FORMS_INPUT": {
    "id": "UI_COMMON_FORMS_INPUT",
    "path": "common.forms.input",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_FORMS_TEXTAREA": {
    "id": "UI_COMMON_FORMS_TEXTAREA",
    "path": "common.forms.textarea",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_FORMS_SELECT": {
    "id": "UI_COMMON_FORMS_SELECT",
    "path": "common.forms.select",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_FORMS_OPTION": {
    "id": "UI_COMMON_FORMS_OPTION",
    "path": "common.forms.option",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 52,
    "feature": "common"
  },
  "UI_COMMON_FORMS_BUTTON": {
    "id": "UI_COMMON_FORMS_BUTTON",
    "path": "common.forms.button",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_FORMS_LABEL": {
    "id": "UI_COMMON_FORMS_LABEL",
    "path": "common.forms.label",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 72,
    "feature": "common"
  },
  "UI_COMMON_FORMS_FIELDSET": {
    "id": "UI_COMMON_FORMS_FIELDSET",
    "path": "common.forms.fieldset",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 82,
    "feature": "common"
  },
  "UI_COMMON_FORMS_LEGEND": {
    "id": "UI_COMMON_FORMS_LEGEND",
    "path": "common.forms.legend",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 92,
    "feature": "common"
  },
  "UI_COMMON_FORMS_CHECKBOX": {
    "id": "UI_COMMON_FORMS_CHECKBOX",
    "path": "common.forms.checkbox",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 102,
    "feature": "common"
  },
  "UI_COMMON_FORMS_RADIO": {
    "id": "UI_COMMON_FORMS_RADIO",
    "path": "common.forms.radio",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 112,
    "feature": "common"
  },
  "UI_COMMON_FORMS_SWITCH": {
    "id": "UI_COMMON_FORMS_SWITCH",
    "path": "common.forms.switch",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 122,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_DIALOG": {
    "id": "UI_COMMON_INTERACTIVE_DIALOG",
    "path": "common.interactive.dialog",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_DETAILS": {
    "id": "UI_COMMON_INTERACTIVE_DETAILS",
    "path": "common.interactive.details",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_SUMMARY": {
    "id": "UI_COMMON_INTERACTIVE_SUMMARY",
    "path": "common.interactive.summary",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_A": {
    "id": "UI_COMMON_INTERACTIVE_A",
    "path": "common.interactive.a",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_CONTAINER": {
    "id": "UI_COMMON_LAYOUT_CONTAINER",
    "path": "common.layout.container",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 16,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_WRAPPER": {
    "id": "UI_COMMON_LAYOUT_WRAPPER",
    "path": "common.layout.wrapper",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 26,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_SPAN": {
    "id": "UI_COMMON_LAYOUT_SPAN",
    "path": "common.layout.span",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 36,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_HEADER": {
    "id": "UI_COMMON_LAYOUT_HEADER",
    "path": "common.layout.header",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 46,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_NAV": {
    "id": "UI_COMMON_LAYOUT_NAV",
    "path": "common.layout.nav",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 56,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_MAIN": {
    "id": "UI_COMMON_LAYOUT_MAIN",
    "path": "common.layout.main",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 66,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_SECTION": {
    "id": "UI_COMMON_LAYOUT_SECTION",
    "path": "common.layout.section",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 76,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_ARTICLE": {
    "id": "UI_COMMON_LAYOUT_ARTICLE",
    "path": "common.layout.article",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 86,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_ASIDE": {
    "id": "UI_COMMON_LAYOUT_ASIDE",
    "path": "common.layout.aside",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 96,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_FOOTER": {
    "id": "UI_COMMON_LAYOUT_FOOTER",
    "path": "common.layout.footer",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 106,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_SPACER": {
    "id": "UI_COMMON_DECORATIVE_SPACER",
    "path": "common.decorative.spacer",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 123,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_DIVIDER": {
    "id": "UI_COMMON_DECORATIVE_DIVIDER",
    "path": "common.decorative.divider",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 133,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_BACKGROUND": {
    "id": "UI_COMMON_DECORATIVE_BACKGROUND",
    "path": "common.decorative.background",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 143,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_OVERLAY": {
    "id": "UI_COMMON_DECORATIVE_OVERLAY",
    "path": "common.decorative.overlay",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 153,
    "feature": "common"
  },
  "UI_COMMON_LISTS_UL": {
    "id": "UI_COMMON_LISTS_UL",
    "path": "common.lists.ul",
    "sourceFile": "/src/platform/ui/registry/categories/lists.ts",
    "sourceComponent": "COMMON_LISTS",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_LISTS_OL": {
    "id": "UI_COMMON_LISTS_OL",
    "path": "common.lists.ol",
    "sourceFile": "/src/platform/ui/registry/categories/lists.ts",
    "sourceComponent": "COMMON_LISTS",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_LISTS_LI": {
    "id": "UI_COMMON_LISTS_LI",
    "path": "common.lists.li",
    "sourceFile": "/src/platform/ui/registry/categories/lists.ts",
    "sourceComponent": "COMMON_LISTS",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_IMG": {
    "id": "UI_COMMON_MEDIA_IMG",
    "path": "common.media.img",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_PICTURE": {
    "id": "UI_COMMON_MEDIA_PICTURE",
    "path": "common.media.picture",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_FIGURE": {
    "id": "UI_COMMON_MEDIA_FIGURE",
    "path": "common.media.figure",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_FIGCAPTION": {
    "id": "UI_COMMON_MEDIA_FIGCAPTION",
    "path": "common.media.figcaption",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_VIDEO": {
    "id": "UI_COMMON_MEDIA_VIDEO",
    "path": "common.media.video",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 52,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_AUDIO": {
    "id": "UI_COMMON_MEDIA_AUDIO",
    "path": "common.media.audio",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_IFRAME": {
    "id": "UI_COMMON_MEDIA_IFRAME",
    "path": "common.media.iframe",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 72,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_CANVAS": {
    "id": "UI_COMMON_MEDIA_CANVAS",
    "path": "common.media.canvas",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 82,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_SVG": {
    "id": "UI_COMMON_MEDIA_SVG",
    "path": "common.media.svg",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 92,
    "feature": "common"
  },
  "UI_COMMON_SPACING_BR": {
    "id": "UI_COMMON_SPACING_BR",
    "path": "common.spacing.br",
    "sourceFile": "/src/platform/ui/registry/categories/spacing.ts",
    "sourceComponent": "COMMON_SPACING",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_SPACING_HR": {
    "id": "UI_COMMON_SPACING_HR",
    "path": "common.spacing.hr",
    "sourceFile": "/src/platform/ui/registry/categories/spacing.ts",
    "sourceComponent": "COMMON_SPACING",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TABLE": {
    "id": "UI_COMMON_TABLES_TABLE",
    "path": "common.tables.table",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_TABLES_THEAD": {
    "id": "UI_COMMON_TABLES_THEAD",
    "path": "common.tables.thead",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TBODY": {
    "id": "UI_COMMON_TABLES_TBODY",
    "path": "common.tables.tbody",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TR": {
    "id": "UI_COMMON_TABLES_TR",
    "path": "common.tables.tr",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TH": {
    "id": "UI_COMMON_TABLES_TH",
    "path": "common.tables.th",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TD": {
    "id": "UI_COMMON_TABLES_TD",
    "path": "common.tables.td",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_TEMPLATE_TEMPLATE": {
    "id": "UI_COMMON_TEMPLATE_TEMPLATE",
    "path": "common.template.template",
    "sourceFile": "/src/platform/ui/registry/categories/template.ts",
    "sourceComponent": "COMMON_TEMPLATE",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_TEMPLATE_SLOT": {
    "id": "UI_COMMON_TEMPLATE_SLOT",
    "path": "common.template.slot",
    "sourceFile": "/src/platform/ui/registry/categories/template.ts",
    "sourceComponent": "COMMON_TEMPLATE",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H1": {
    "id": "UI_COMMON_TYPOGRAPHY_H1",
    "path": "common.typography.h1",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H2": {
    "id": "UI_COMMON_TYPOGRAPHY_H2",
    "path": "common.typography.h2",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H3": {
    "id": "UI_COMMON_TYPOGRAPHY_H3",
    "path": "common.typography.h3",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H4": {
    "id": "UI_COMMON_TYPOGRAPHY_H4",
    "path": "common.typography.h4",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H5": {
    "id": "UI_COMMON_TYPOGRAPHY_H5",
    "path": "common.typography.h5",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 52,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H6": {
    "id": "UI_COMMON_TYPOGRAPHY_H6",
    "path": "common.typography.h6",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_P": {
    "id": "UI_COMMON_TYPOGRAPHY_P",
    "path": "common.typography.p",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 72,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_STRONG": {
    "id": "UI_COMMON_TYPOGRAPHY_STRONG",
    "path": "common.typography.strong",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 82,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_EM": {
    "id": "UI_COMMON_TYPOGRAPHY_EM",
    "path": "common.typography.em",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 92,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_CODE": {
    "id": "UI_COMMON_TYPOGRAPHY_CODE",
    "path": "common.typography.code",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 102,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_PRE": {
    "id": "UI_COMMON_TYPOGRAPHY_PRE",
    "path": "common.typography.pre",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 112,
    "feature": "common"
  },
  "UI_SETTINGS_TITLE": {
    "id": "UI_SETTINGS_TITLE",
    "path": "settings.page.display.title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 5,
    "feature": "settings"
  },
  "UI_SETTINGS_DESCRIPTION": {
    "id": "UI_SETTINGS_DESCRIPTION",
    "path": "settings.page.display.description",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 15,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_TITLE": {
    "id": "UI_SETTINGS_APP_SETTINGS_TITLE",
    "path": "settings.app-settings.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 26,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_ACTIVE": {
    "id": "UI_SETTINGS_APP_SETTINGS_ACTIVE",
    "path": "settings.app-settings.status.active",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 36,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_STATUS_TITLE": {
    "id": "UI_SETTINGS_APP_SETTINGS_STATUS_TITLE",
    "path": "settings.app-settings.status.status-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 46,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_STATUS_DESCRIPTION": {
    "id": "UI_SETTINGS_APP_SETTINGS_STATUS_DESCRIPTION",
    "path": "settings.app-settings.status.description",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 56,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_MAINTENANCE_TITLE": {
    "id": "UI_SETTINGS_APP_SETTINGS_MAINTENANCE_TITLE",
    "path": "settings.app-settings.maintenance.maintenance-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 66,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_MAINTENANCE_DESCRIPTION": {
    "id": "UI_SETTINGS_APP_SETTINGS_MAINTENANCE_DESCRIPTION",
    "path": "settings.app-settings.maintenance.maintenance-description",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 76,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_FEATURE_FLAGS_TITLE": {
    "id": "UI_SETTINGS_APP_SETTINGS_FEATURE_FLAGS_TITLE",
    "path": "settings.app-settings.feature-flags.feature-flags-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 86,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_AI": {
    "id": "UI_SETTINGS_APP_SETTINGS_AI",
    "path": "settings.app-settings.feature-flags.ai",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 96,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_ANALYTICS": {
    "id": "UI_SETTINGS_APP_SETTINGS_ANALYTICS",
    "path": "settings.app-settings.feature-flags.analytics",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 106,
    "feature": "settings"
  },
  "UI_SETTINGS_APP_SETTINGS_PDF": {
    "id": "UI_SETTINGS_APP_SETTINGS_PDF",
    "path": "settings.app-settings.feature-flags.pdf",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 116,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_TITLE": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_TITLE",
    "path": "settings.language-region.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 128,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_LANGUAGE_TITLE": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_LANGUAGE_TITLE",
    "path": "settings.language-region.language.language-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 138,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_LANGUAGE_DESCRIPTION": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_LANGUAGE_DESCRIPTION",
    "path": "settings.language-region.language.description",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 148,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_ARABIC": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_ARABIC",
    "path": "settings.language-region.language.arabic-button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 158,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_ENGLISH": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_ENGLISH",
    "path": "settings.language-region.language.english-button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 168,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_DIRECTION_PREVIEW": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_DIRECTION_PREVIEW",
    "path": "settings.language-region.direction.preview-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 178,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_DIRECTION_RTL": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_DIRECTION_RTL",
    "path": "settings.language-region.direction.rtl-preview",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 188,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_DIRECTION_LTR": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_DIRECTION_LTR",
    "path": "settings.language-region.direction.ltr-preview",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 198,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_TIMEZONE": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_TIMEZONE",
    "path": "settings.language-region.timezone.timezone-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 208,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_CAIRO": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_CAIRO",
    "path": "settings.language-region.timezone.cairo",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 218,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_MECCA": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_MECCA",
    "path": "settings.language-region.timezone.mecca",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 228,
    "feature": "settings"
  },
  "UI_SETTINGS_LANGUAGE_REGION_DUBAI": {
    "id": "UI_SETTINGS_LANGUAGE_REGION_DUBAI",
    "path": "settings.language-region.timezone.dubai",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 238,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_TITLE": {
    "id": "UI_SETTINGS_APPEARANCE_TITLE",
    "path": "settings.appearance.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 250,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_THEME_TITLE": {
    "id": "UI_SETTINGS_APPEARANCE_THEME_TITLE",
    "path": "settings.appearance.theme.theme-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 260,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_LIGHT": {
    "id": "UI_SETTINGS_APPEARANCE_LIGHT",
    "path": "settings.appearance.theme.light",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 270,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_DARK": {
    "id": "UI_SETTINGS_APPEARANCE_DARK",
    "path": "settings.appearance.theme.dark",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 280,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_SYSTEM": {
    "id": "UI_SETTINGS_APPEARANCE_SYSTEM",
    "path": "settings.appearance.theme.system",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 290,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_FONT_SIZE_TITLE": {
    "id": "UI_SETTINGS_APPEARANCE_FONT_SIZE_TITLE",
    "path": "settings.appearance.font-size.font-size-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 300,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_DENSITY_TITLE": {
    "id": "UI_SETTINGS_APPEARANCE_DENSITY_TITLE",
    "path": "settings.appearance.density.density-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 310,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_COMPACT": {
    "id": "UI_SETTINGS_APPEARANCE_COMPACT",
    "path": "settings.appearance.density.compact",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 320,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_COMFORTABLE": {
    "id": "UI_SETTINGS_APPEARANCE_COMFORTABLE",
    "path": "settings.appearance.density.comfortable",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 330,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_SPACIOUS": {
    "id": "UI_SETTINGS_APPEARANCE_SPACIOUS",
    "path": "settings.appearance.density.spacious",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 340,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_PREVIEW_TITLE": {
    "id": "UI_SETTINGS_APPEARANCE_PREVIEW_TITLE",
    "path": "settings.appearance.preview.preview-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 350,
    "feature": "settings"
  },
  "UI_SETTINGS_APPEARANCE_BUTTON": {
    "id": "UI_SETTINGS_APPEARANCE_BUTTON",
    "path": "settings.appearance.preview.button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 360,
    "feature": "settings"
  },
  "UI_SETTINGS_ACCESSIBILITY_TITLE": {
    "id": "UI_SETTINGS_ACCESSIBILITY_TITLE",
    "path": "settings.accessibility.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 372,
    "feature": "settings"
  },
  "UI_SETTINGS_ACCESSIBILITY_HIGH_CONTRAST_TITLE": {
    "id": "UI_SETTINGS_ACCESSIBILITY_HIGH_CONTRAST_TITLE",
    "path": "settings.accessibility.high-contrast.high-contrast-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 382,
    "feature": "settings"
  },
  "UI_SETTINGS_ACCESSIBILITY_HIGH_CONTRAST_DESCRIPTION": {
    "id": "UI_SETTINGS_ACCESSIBILITY_HIGH_CONTRAST_DESCRIPTION",
    "path": "settings.accessibility.high-contrast.high-contrast-description",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 392,
    "feature": "settings"
  },
  "UI_SETTINGS_ACCESSIBILITY_REDUCED_MOTION_TITLE": {
    "id": "UI_SETTINGS_ACCESSIBILITY_REDUCED_MOTION_TITLE",
    "path": "settings.accessibility.reduced-motion.reduced-motion-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 402,
    "feature": "settings"
  },
  "UI_SETTINGS_ACCESSIBILITY_REDUCED_MOTION_DESCRIPTION": {
    "id": "UI_SETTINGS_ACCESSIBILITY_REDUCED_MOTION_DESCRIPTION",
    "path": "settings.accessibility.reduced-motion.reduced-motion-description",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 412,
    "feature": "settings"
  },
  "UI_SETTINGS_DEVELOPER_TOOLS_TITLE": {
    "id": "UI_SETTINGS_DEVELOPER_TOOLS_TITLE",
    "path": "settings.developer-tools.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 424,
    "feature": "settings"
  },
  "UI_SETTINGS_DEVELOPER_TOOLS_SSOT_GUARD_TITLE": {
    "id": "UI_SETTINGS_DEVELOPER_TOOLS_SSOT_GUARD_TITLE",
    "path": "settings.developer-tools.ssot-guard.ssot-guard-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 434,
    "feature": "settings"
  },
  "UI_SETTINGS_DEVELOPER_TOOLS_SSOT_GUARD_DESCRIPTION": {
    "id": "UI_SETTINGS_DEVELOPER_TOOLS_SSOT_GUARD_DESCRIPTION",
    "path": "settings.developer-tools.ssot-guard.ssot-guard-description",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 444,
    "feature": "settings"
  },
  "UI_SETTINGS_DEVELOPER_TOOLS_DIAGNOSTICS": {
    "id": "UI_SETTINGS_DEVELOPER_TOOLS_DIAGNOSTICS",
    "path": "settings.developer-tools.diagnostics.diagnostics-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 454,
    "feature": "settings"
  },
  "UI_SETTINGS_DEVELOPER_TOOLS_START_TEST": {
    "id": "UI_SETTINGS_DEVELOPER_TOOLS_START_TEST",
    "path": "settings.developer-tools.start-test.button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 464,
    "feature": "settings"
  },
  "UI_SETTINGS_STORAGE_TITLE": {
    "id": "UI_SETTINGS_STORAGE_TITLE",
    "path": "settings.storage.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 476,
    "feature": "settings"
  },
  "UI_SETTINGS_STORAGE_LOCAL_STORAGE": {
    "id": "UI_SETTINGS_STORAGE_LOCAL_STORAGE",
    "path": "settings.storage.local-storage.local-storage-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 486,
    "feature": "settings"
  },
  "UI_SETTINGS_STORAGE_USAGE": {
    "id": "UI_SETTINGS_STORAGE_USAGE",
    "path": "settings.storage.usage.usage-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 496,
    "feature": "settings"
  },
  "UI_SETTINGS_STORAGE_COOKIES": {
    "id": "UI_SETTINGS_STORAGE_COOKIES",
    "path": "settings.storage.cookies.cookies-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 506,
    "feature": "settings"
  },
  "UI_SETTINGS_STORAGE_CLEAR_ALL": {
    "id": "UI_SETTINGS_STORAGE_CLEAR_ALL",
    "path": "settings.storage.clear-all.button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 516,
    "feature": "settings"
  },
  "UI_SETTINGS_SUMMARY_TITLE": {
    "id": "UI_SETTINGS_SUMMARY_TITLE",
    "path": "settings.summary.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 528,
    "feature": "settings"
  },
  "UI_SETTINGS_SUMMARY_LANGUAGE": {
    "id": "UI_SETTINGS_SUMMARY_LANGUAGE",
    "path": "settings.summary.language.language-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 538,
    "feature": "settings"
  },
  "UI_SETTINGS_SUMMARY_THEME": {
    "id": "UI_SETTINGS_SUMMARY_THEME",
    "path": "settings.summary.theme.theme-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 548,
    "feature": "settings"
  },
  "UI_SETTINGS_SUMMARY_DENSITY": {
    "id": "UI_SETTINGS_SUMMARY_DENSITY",
    "path": "settings.summary.density.density-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 558,
    "feature": "settings"
  },
  "UI_SETTINGS_SUMMARY_TIMEZONE": {
    "id": "UI_SETTINGS_SUMMARY_TIMEZONE",
    "path": "settings.summary.timezone.timezone-label",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 568,
    "feature": "settings"
  },
  "UI_SETTINGS_ACTIONS_SAVE": {
    "id": "UI_SETTINGS_ACTIONS_SAVE",
    "path": "settings.actions.save.save-button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 580,
    "feature": "settings"
  },
  "UI_SETTINGS_ACTIONS_RESET_PREFERENCES": {
    "id": "UI_SETTINGS_ACTIONS_RESET_PREFERENCES",
    "path": "settings.actions.reset-preferences.reset-button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 590,
    "feature": "settings"
  },
  "UI_SETTINGS_ACTIONS_RESTORE_DEFAULTS": {
    "id": "UI_SETTINGS_ACTIONS_RESTORE_DEFAULTS",
    "path": "settings.actions.restore-defaults.restore-button",
    "sourceFile": "/src/platform/ui/registry/features/settings.ts",
    "sourceComponent": "SETTINGS",
    "sourceLine": 600,
    "feature": "settings"
  },
  "UI_SHARED_SIDEBAR_LOGIN": {
    "id": "UI_SHARED_SIDEBAR_LOGIN",
    "path": "shared-layout.sidebar.actions.login-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 236,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_LANGUAGE": {
    "id": "UI_SHARED_SIDEBAR_LANGUAGE",
    "path": "shared-layout.sidebar.actions.language-toggle",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 246,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_THEME": {
    "id": "UI_SHARED_SIDEBAR_THEME",
    "path": "shared-layout.sidebar.actions.theme-toggle",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 256,
    "feature": "shared-layout"
  }
};
