/**
 * Automatically generated by audit-unified-ui-i18n.ts.
 * Do not edit this file manually.
 */

export interface UiSourceLocation {
  id: string;
  path: string;
  sourceFile: string;
  sourceComponent: string;
  sourceLine: number;
  feature: string;
}

export const UI_SOURCE_INDEX: Record<string, UiSourceLocation> = {
  "UI_HOME_CATEGORIES_GRID_TOGGLE": {
    "id": "UI_HOME_CATEGORIES_GRID_TOGGLE",
    "path": "home.categories-grid.actions.toggle-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 246,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_ITEM": {
    "id": "UI_HOME_CATEGORIES_GRID_ITEM",
    "path": "home.categories-grid.actions.category-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 112,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_CATEGORY_IMAGE": {
    "id": "UI_HOME_CATEGORIES_GRID_CATEGORY_IMAGE",
    "path": "home.categories-grid.display.category-image",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 372,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_CATEGORY_NAME": {
    "id": "UI_HOME_CATEGORIES_GRID_CATEGORY_NAME",
    "path": "home.categories-grid.display.category-name",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 382,
    "feature": "home"
  },
  "UI_HOME_CATEGORIES_GRID_SECTION_TITLE": {
    "id": "UI_HOME_CATEGORIES_GRID_SECTION_TITLE",
    "path": "home.categories-grid.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 394,
    "feature": "home"
  },
  "UI_SPLASH_LOGO_IMAGE": {
    "id": "UI_SPLASH_LOGO_IMAGE",
    "path": "splash.logo.display.logo-image",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 4,
    "feature": "splash"
  },
  "UI_HOME_CURATED_OFFERS_CONTAINER": {
    "id": "UI_HOME_CURATED_OFFERS_CONTAINER",
    "path": "home.curated-offers.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 100,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_HEADER": {
    "id": "UI_HOME_CURATED_OFFERS_HEADER",
    "path": "home.curated-offers.layout.header",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 110,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_GRID": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_GRID",
    "path": "home.curated-offers.layout.product-grid",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 118,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_CARD": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_CARD",
    "path": "home.curated-offers.layout.product-card",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 128,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE_CONTAINER": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE_CONTAINER",
    "path": "home.curated-offers.layout.product-image-container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 138,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_INFO": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_INFO",
    "path": "home.curated-offers.layout.product-info",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 148,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRICE_ROW": {
    "id": "UI_HOME_CURATED_OFFERS_PRICE_ROW",
    "path": "home.curated-offers.layout.price-row",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 158,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_SHOW_MORE_CONTAINER": {
    "id": "UI_HOME_CURATED_OFFERS_SHOW_MORE_CONTAINER",
    "path": "home.curated-offers.layout.show-more-container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 168,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_MORE": {
    "id": "UI_HOME_CURATED_OFFERS_MORE",
    "path": "home.curated-offers.actions.show-more-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 168,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_ADD_TO_CART": {
    "id": "UI_HOME_CURATED_OFFERS_ADD_TO_CART",
    "path": "home.curated-offers.actions.add-to-cart-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 188,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_FAVORITE": {
    "id": "UI_HOME_CURATED_OFFERS_FAVORITE",
    "path": "home.curated-offers.actions.add-to-favorites-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 198,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_IMAGE",
    "path": "home.curated-offers.display.product-image",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 138,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_CATEGORY_LABEL": {
    "id": "UI_HOME_CURATED_OFFERS_CATEGORY_LABEL",
    "path": "home.curated-offers.display.category-label",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 218,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRODUCT_TITLE": {
    "id": "UI_HOME_CURATED_OFFERS_PRODUCT_TITLE",
    "path": "home.curated-offers.display.product-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 228,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PRICE_LABEL": {
    "id": "UI_HOME_CURATED_OFFERS_PRICE_LABEL",
    "path": "home.curated-offers.display.price-label",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 238,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_SECTION_TITLE": {
    "id": "UI_HOME_CURATED_OFFERS_SECTION_TITLE",
    "path": "home.curated-offers.display.section-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 250,
    "feature": "home"
  },
  "UI_HOME_CURATED_OFFERS_PROMO_TAG": {
    "id": "UI_HOME_CURATED_OFFERS_PROMO_TAG",
    "path": "home.curated-offers.display.promo-tag",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 258,
    "feature": "home"
  },
  "UI_SPLASH_MAINTENANCE_CARD": {
    "id": "UI_SPLASH_MAINTENANCE_CARD",
    "path": "splash.maintenance.layout.card",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 46,
    "feature": "splash"
  },
  "UI_HOME_HERO_SLIDER_CONTAINER": {
    "id": "UI_HOME_HERO_SLIDER_CONTAINER",
    "path": "home.hero-slider.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 272,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDER_TRACK": {
    "id": "UI_HOME_HERO_SLIDER_SLIDER_TRACK",
    "path": "home.hero-slider.layout.slider-track",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 280,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE",
    "path": "home.hero-slider.layout.slide",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 269,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_CONTENT": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_CONTENT",
    "path": "home.hero-slider.layout.slide-content",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 300,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_INDICATORS": {
    "id": "UI_HOME_HERO_SLIDER_INDICATORS",
    "path": "home.hero-slider.layout.indicators",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 310,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_IMAGE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_IMAGE",
    "path": "home.hero-slider.display.slide-image",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 320,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_TITLE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_TITLE",
    "path": "home.hero-slider.display.slide-title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 330,
    "feature": "home"
  },
  "UI_HOME_HERO_SLIDER_SLIDE_BADGE": {
    "id": "UI_HOME_HERO_SLIDER_SLIDE_BADGE",
    "path": "home.hero-slider.display.slide-badge",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 340,
    "feature": "home"
  },
  "UI_SHARED_SIDEBAR_CONTENT": {
    "id": "UI_SHARED_SIDEBAR_CONTENT",
    "path": "shared-layout.sidebar.layout.content",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 206,
    "feature": "shared-layout"
  },
  "UI_HOME_PROMO_BANNER_CONTAINER": {
    "id": "UI_HOME_PROMO_BANNER_CONTAINER",
    "path": "home.promo-banner.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 28,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_CONTENT_WRAPPER": {
    "id": "UI_HOME_PROMO_BANNER_CONTENT_WRAPPER",
    "path": "home.promo-banner.layout.content-wrapper",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 36,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_ACTION": {
    "id": "UI_HOME_PROMO_BANNER_ACTION",
    "path": "home.promo-banner.actions.banner-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 46,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_TITLE": {
    "id": "UI_HOME_PROMO_BANNER_TITLE",
    "path": "home.promo-banner.display.title",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 58,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_DESCRIPTION": {
    "id": "UI_HOME_PROMO_BANNER_DESCRIPTION",
    "path": "home.promo-banner.display.description",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 66,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_LOGO": {
    "id": "UI_HOME_PROMO_BANNER_LOGO",
    "path": "home.promo-banner.display.logo",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 78,
    "feature": "home"
  },
  "UI_HOME_PROMO_BANNER_DECORATIVE_BACKGROUND": {
    "id": "UI_HOME_PROMO_BANNER_DECORATIVE_BACKGROUND",
    "path": "home.promo-banner.decorative.background",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 86,
    "feature": "home"
  },
  "UI_AUTH_LOGIN_HEADING": {
    "id": "UI_AUTH_LOGIN_HEADING",
    "path": "auth.login.display.heading",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 16,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SUBHEADING": {
    "id": "UI_AUTH_LOGIN_SUBHEADING",
    "path": "auth.login.display.subheading",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 24,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_PHONE_INPUT": {
    "id": "UI_AUTH_LOGIN_PHONE_INPUT",
    "path": "auth.login.form.phone-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 34,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_PASSWORD_INPUT": {
    "id": "UI_AUTH_LOGIN_PASSWORD_INPUT",
    "path": "auth.login.form.password-input",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 44,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_TOGGLE_PASSWORD": {
    "id": "UI_AUTH_LOGIN_TOGGLE_PASSWORD",
    "path": "auth.login.form.toggle-password-visibility",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 54,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_FORGOT_PASSWORD": {
    "id": "UI_AUTH_LOGIN_FORGOT_PASSWORD",
    "path": "auth.login.form.forgot-password-link",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 64,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SUBMIT": {
    "id": "UI_AUTH_LOGIN_SUBMIT",
    "path": "auth.login.form.submit-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 76,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_GUEST": {
    "id": "UI_AUTH_LOGIN_GUEST",
    "path": "auth.login.actions.guest-login-button",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 84,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_SIGNUP_LINK": {
    "id": "UI_AUTH_LOGIN_SIGNUP_LINK",
    "path": "auth.login.actions.signup-link",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 94,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_ENGLISH_LANG": {
    "id": "UI_AUTH_LOGIN_ENGLISH_LANG",
    "path": "auth.login.footer.english-language-link",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 104,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_DARK_MODE": {
    "id": "UI_AUTH_LOGIN_DARK_MODE",
    "path": "auth.login.footer.dark-mode-toggle",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 114,
    "feature": "auth"
  },
  "UI_AUTH_LOGIN_COPYRIGHT": {
    "id": "UI_AUTH_LOGIN_COPYRIGHT",
    "path": "auth.login.footer.copyright",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 124,
    "feature": "auth"
  },
  "UI_SHARED_HEADER_CONTAINER": {
    "id": "UI_SHARED_HEADER_CONTAINER",
    "path": "shared-layout.header.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 6,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_INNER_WRAPPER": {
    "id": "UI_SHARED_HEADER_INNER_WRAPPER",
    "path": "shared-layout.header.layout.inner-wrapper",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 14,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_BRAND_SECTION": {
    "id": "UI_SHARED_HEADER_BRAND_SECTION",
    "path": "shared-layout.header.layout.brand-section",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 24,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_ACTIONS_SECTION": {
    "id": "UI_SHARED_HEADER_ACTIONS_SECTION",
    "path": "shared-layout.header.layout.actions-section",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 36,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_MENU": {
    "id": "UI_SHARED_HEADER_MENU",
    "path": "shared-layout.header.menu.menu-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 45,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_BRAND_LINK": {
    "id": "UI_SHARED_HEADER_BRAND_LINK",
    "path": "shared-layout.header.brand.brand-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 57,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_BUTTON": {
    "id": "UI_SHARED_HEADER_SEARCH_BUTTON",
    "path": "shared-layout.header.actions.search-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 69,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_CART_BUTTON": {
    "id": "UI_SHARED_HEADER_CART_BUTTON",
    "path": "shared-layout.header.actions.cart-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 79,
    "feature": "shared-layout"
  },
  "UI_SHARED_HEADER_SEARCH_INPUT": {
    "id": "UI_SHARED_HEADER_SEARCH_INPUT",
    "path": "shared-layout.header.actions.search-input",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 89,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_CONTAINER": {
    "id": "UI_SHARED_SIDEBAR_CONTAINER",
    "path": "shared-layout.sidebar.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 168,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_OVERLAY": {
    "id": "UI_SHARED_SIDEBAR_OVERLAY",
    "path": "shared-layout.sidebar.layout.overlay",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 176,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_PANEL": {
    "id": "UI_SHARED_SIDEBAR_PANEL",
    "path": "shared-layout.sidebar.layout.panel",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 186,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_HEADER": {
    "id": "UI_SHARED_SIDEBAR_HEADER",
    "path": "shared-layout.sidebar.layout.header",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 198,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_ACTIONS_SECTION": {
    "id": "UI_SHARED_SIDEBAR_ACTIONS_SECTION",
    "path": "shared-layout.sidebar.layout.actions-section",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 218,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_CLOSE": {
    "id": "UI_SHARED_SIDEBAR_CLOSE",
    "path": "shared-layout.sidebar.actions.close-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 226,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_LOGIN": {
    "id": "UI_SHARED_SIDEBAR_LOGIN",
    "path": "shared-layout.sidebar.actions.login-button",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 238,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_LANGUAGE": {
    "id": "UI_SHARED_SIDEBAR_LANGUAGE",
    "path": "shared-layout.sidebar.actions.language-toggle",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 246,
    "feature": "shared-layout"
  },
  "UI_SHARED_SIDEBAR_THEME": {
    "id": "UI_SHARED_SIDEBAR_THEME",
    "path": "shared-layout.sidebar.actions.theme-toggle",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 256,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_CONTAINER": {
    "id": "UI_SHARED_BOTTOM_NAV_CONTAINER",
    "path": "shared-layout.bottom-nav.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 104,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_HOME": {
    "id": "UI_SHARED_BOTTOM_NAV_HOME",
    "path": "shared-layout.bottom-nav.items.home-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 113,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS": {
    "id": "UI_SHARED_BOTTOM_NAV_NOTIFICATIONS",
    "path": "shared-layout.bottom-nav.items.notifications-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 123,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_FAVORITES": {
    "id": "UI_SHARED_BOTTOM_NAV_FAVORITES",
    "path": "shared-layout.bottom-nav.items.favorites-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 133,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_ORDERS": {
    "id": "UI_SHARED_BOTTOM_NAV_ORDERS",
    "path": "shared-layout.bottom-nav.items.orders-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 143,
    "feature": "shared-layout"
  },
  "UI_SHARED_BOTTOM_NAV_PROFILE": {
    "id": "UI_SHARED_BOTTOM_NAV_PROFILE",
    "path": "shared-layout.bottom-nav.items.profile-link",
    "sourceFile": "/src/platform/ui/registry/features/shared-layout.ts",
    "sourceComponent": "SHARED_LAYOUT",
    "sourceLine": 153,
    "feature": "shared-layout"
  },
  "UI_ERROR_BOUNDARY_TITLE": {
    "id": "UI_ERROR_BOUNDARY_TITLE",
    "path": "error-boundary.main.display.title",
    "sourceFile": "/src/platform/ui/registry/features/error-boundary.ts",
    "sourceComponent": "ERROR_BOUNDARY",
    "sourceLine": 5,
    "feature": "error-boundary"
  },
  "UI_ERROR_BOUNDARY_DEFAULT_MESSAGE": {
    "id": "UI_ERROR_BOUNDARY_DEFAULT_MESSAGE",
    "path": "error-boundary.main.display.default-message",
    "sourceFile": "/src/platform/ui/registry/features/error-boundary.ts",
    "sourceComponent": "ERROR_BOUNDARY",
    "sourceLine": 15,
    "feature": "error-boundary"
  },
  "UI_ERROR_BOUNDARY_RELOAD": {
    "id": "UI_ERROR_BOUNDARY_RELOAD",
    "path": "error-boundary.main.actions.reload-button",
    "sourceFile": "/src/platform/ui/registry/features/error-boundary.ts",
    "sourceComponent": "ERROR_BOUNDARY",
    "sourceLine": 23,
    "feature": "error-boundary"
  },
  "UI_HOME_LANG_ENGLISH": {
    "id": "UI_HOME_LANG_ENGLISH",
    "path": "home.language-switcher.buttons.english-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 4,
    "feature": "home"
  },
  "UI_HOME_LANG_ARABIC": {
    "id": "UI_HOME_LANG_ARABIC",
    "path": "home.language-switcher.buttons.arabic-button",
    "sourceFile": "/src/platform/ui/registry/features/home.ts",
    "sourceComponent": "HOME",
    "sourceLine": 14,
    "feature": "home"
  },
  "UI_SPLASH_LOGO_HEADING": {
    "id": "UI_SPLASH_LOGO_HEADING",
    "path": "splash.logo.display.heading",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 16,
    "feature": "splash"
  },
  "UI_SPLASH_LOGO_TAGLINE": {
    "id": "UI_SPLASH_LOGO_TAGLINE",
    "path": "splash.logo.display.tagline",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 24,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_CONTAINER": {
    "id": "UI_SPLASH_MAINTENANCE_CONTAINER",
    "path": "splash.maintenance.layout.container",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 38,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_ICON_CONTAINER": {
    "id": "UI_SPLASH_MAINTENANCE_ICON_CONTAINER",
    "path": "splash.maintenance.layout.icon-container",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 56,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_TITLE": {
    "id": "UI_SPLASH_MAINTENANCE_TITLE",
    "path": "splash.maintenance.display.title",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 68,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_DEFAULT_MESSAGE": {
    "id": "UI_SPLASH_MAINTENANCE_DEFAULT_MESSAGE",
    "path": "splash.maintenance.display.default-message",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 78,
    "feature": "splash"
  },
  "UI_SPLASH_MAINTENANCE_INVALID_CODE": {
    "id": "UI_SPLASH_MAINTENANCE_INVALID_CODE",
    "path": "splash.maintenance.display.invalid-code",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 86,
    "feature": "splash"
  },
  "UI_SPLASH_MAINT_PIN": {
    "id": "UI_SPLASH_MAINT_PIN",
    "path": "splash.maintenance.form.pin-input",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 97,
    "feature": "splash"
  },
  "UI_SPLASH_MAINT_SUBMIT": {
    "id": "UI_SPLASH_MAINT_SUBMIT",
    "path": "splash.maintenance.form.submit-button",
    "sourceFile": "/src/platform/ui/registry/features/splash.ts",
    "sourceComponent": "SPLASH",
    "sourceLine": 107,
    "feature": "splash"
  },
  "UI_COMMON_CARD_CONTAINER": {
    "id": "UI_COMMON_CARD_CONTAINER",
    "path": "common.components.card.container",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 11,
    "feature": "common"
  },
  "UI_COMMON_CARD_TITLE": {
    "id": "UI_COMMON_CARD_TITLE",
    "path": "common.components.card.title",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 21,
    "feature": "common"
  },
  "UI_COMMON_MODAL_CONTAINER": {
    "id": "UI_COMMON_MODAL_CONTAINER",
    "path": "common.components.modal.container",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 33,
    "feature": "common"
  },
  "UI_COMMON_MODAL_TITLE": {
    "id": "UI_COMMON_MODAL_TITLE",
    "path": "common.components.modal.title",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 43,
    "feature": "common"
  },
  "UI_COMMON_MODAL_CLOSE": {
    "id": "UI_COMMON_MODAL_CLOSE",
    "path": "common.components.modal.close-button",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 53,
    "feature": "common"
  },
  "UI_COMMON_BADGE_LABEL": {
    "id": "UI_COMMON_BADGE_LABEL",
    "path": "common.components.badge.label",
    "sourceFile": "/src/platform/ui/registry/categories/components.ts",
    "sourceComponent": "COMMON_COMPONENTS",
    "sourceLine": 65,
    "feature": "common"
  },
  "UI_COMMON_FORMS_FORM": {
    "id": "UI_COMMON_FORMS_FORM",
    "path": "common.forms.form",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_FORMS_INPUT": {
    "id": "UI_COMMON_FORMS_INPUT",
    "path": "common.forms.input",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_FORMS_TEXTAREA": {
    "id": "UI_COMMON_FORMS_TEXTAREA",
    "path": "common.forms.textarea",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_FORMS_SELECT": {
    "id": "UI_COMMON_FORMS_SELECT",
    "path": "common.forms.select",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_FORMS_OPTION": {
    "id": "UI_COMMON_FORMS_OPTION",
    "path": "common.forms.option",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 52,
    "feature": "common"
  },
  "UI_COMMON_FORMS_BUTTON": {
    "id": "UI_COMMON_FORMS_BUTTON",
    "path": "common.forms.button",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_FORMS_LABEL": {
    "id": "UI_COMMON_FORMS_LABEL",
    "path": "common.forms.label",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 72,
    "feature": "common"
  },
  "UI_COMMON_FORMS_FIELDSET": {
    "id": "UI_COMMON_FORMS_FIELDSET",
    "path": "common.forms.fieldset",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 82,
    "feature": "common"
  },
  "UI_COMMON_FORMS_LEGEND": {
    "id": "UI_COMMON_FORMS_LEGEND",
    "path": "common.forms.legend",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 92,
    "feature": "common"
  },
  "UI_COMMON_FORMS_CHECKBOX": {
    "id": "UI_COMMON_FORMS_CHECKBOX",
    "path": "common.forms.checkbox",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 102,
    "feature": "common"
  },
  "UI_COMMON_FORMS_RADIO": {
    "id": "UI_COMMON_FORMS_RADIO",
    "path": "common.forms.radio",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 112,
    "feature": "common"
  },
  "UI_COMMON_FORMS_SWITCH": {
    "id": "UI_COMMON_FORMS_SWITCH",
    "path": "common.forms.switch",
    "sourceFile": "/src/platform/ui/registry/categories/forms.ts",
    "sourceComponent": "COMMON_FORMS",
    "sourceLine": 122,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_DIALOG": {
    "id": "UI_COMMON_INTERACTIVE_DIALOG",
    "path": "common.interactive.dialog",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_DETAILS": {
    "id": "UI_COMMON_INTERACTIVE_DETAILS",
    "path": "common.interactive.details",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_SUMMARY": {
    "id": "UI_COMMON_INTERACTIVE_SUMMARY",
    "path": "common.interactive.summary",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_INTERACTIVE_A": {
    "id": "UI_COMMON_INTERACTIVE_A",
    "path": "common.interactive.a",
    "sourceFile": "/src/platform/ui/registry/categories/interactive.ts",
    "sourceComponent": "COMMON_INTERACTIVE",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_CONTAINER": {
    "id": "UI_COMMON_LAYOUT_CONTAINER",
    "path": "common.layout.container",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 16,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_WRAPPER": {
    "id": "UI_COMMON_LAYOUT_WRAPPER",
    "path": "common.layout.wrapper",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 26,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_SPAN": {
    "id": "UI_COMMON_LAYOUT_SPAN",
    "path": "common.layout.span",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 36,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_HEADER": {
    "id": "UI_COMMON_LAYOUT_HEADER",
    "path": "common.layout.header",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 46,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_NAV": {
    "id": "UI_COMMON_LAYOUT_NAV",
    "path": "common.layout.nav",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 56,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_MAIN": {
    "id": "UI_COMMON_LAYOUT_MAIN",
    "path": "common.layout.main",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 66,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_SECTION": {
    "id": "UI_COMMON_LAYOUT_SECTION",
    "path": "common.layout.section",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 76,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_ARTICLE": {
    "id": "UI_COMMON_LAYOUT_ARTICLE",
    "path": "common.layout.article",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 86,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_ASIDE": {
    "id": "UI_COMMON_LAYOUT_ASIDE",
    "path": "common.layout.aside",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 96,
    "feature": "common"
  },
  "UI_COMMON_LAYOUT_FOOTER": {
    "id": "UI_COMMON_LAYOUT_FOOTER",
    "path": "common.layout.footer",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 106,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_SPACER": {
    "id": "UI_COMMON_DECORATIVE_SPACER",
    "path": "common.decorative.spacer",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 123,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_DIVIDER": {
    "id": "UI_COMMON_DECORATIVE_DIVIDER",
    "path": "common.decorative.divider",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 133,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_BACKGROUND": {
    "id": "UI_COMMON_DECORATIVE_BACKGROUND",
    "path": "common.decorative.background",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 143,
    "feature": "common"
  },
  "UI_COMMON_DECORATIVE_OVERLAY": {
    "id": "UI_COMMON_DECORATIVE_OVERLAY",
    "path": "common.decorative.overlay",
    "sourceFile": "/src/platform/ui/registry/categories/layout.ts",
    "sourceComponent": "COMMON_LAYOUT",
    "sourceLine": 153,
    "feature": "common"
  },
  "UI_COMMON_LISTS_UL": {
    "id": "UI_COMMON_LISTS_UL",
    "path": "common.lists.ul",
    "sourceFile": "/src/platform/ui/registry/categories/lists.ts",
    "sourceComponent": "COMMON_LISTS",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_LISTS_OL": {
    "id": "UI_COMMON_LISTS_OL",
    "path": "common.lists.ol",
    "sourceFile": "/src/platform/ui/registry/categories/lists.ts",
    "sourceComponent": "COMMON_LISTS",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_LISTS_LI": {
    "id": "UI_COMMON_LISTS_LI",
    "path": "common.lists.li",
    "sourceFile": "/src/platform/ui/registry/categories/lists.ts",
    "sourceComponent": "COMMON_LISTS",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_IMG": {
    "id": "UI_COMMON_MEDIA_IMG",
    "path": "common.media.img",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_PICTURE": {
    "id": "UI_COMMON_MEDIA_PICTURE",
    "path": "common.media.picture",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_FIGURE": {
    "id": "UI_COMMON_MEDIA_FIGURE",
    "path": "common.media.figure",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_FIGCAPTION": {
    "id": "UI_COMMON_MEDIA_FIGCAPTION",
    "path": "common.media.figcaption",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_VIDEO": {
    "id": "UI_COMMON_MEDIA_VIDEO",
    "path": "common.media.video",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 52,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_AUDIO": {
    "id": "UI_COMMON_MEDIA_AUDIO",
    "path": "common.media.audio",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_IFRAME": {
    "id": "UI_COMMON_MEDIA_IFRAME",
    "path": "common.media.iframe",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 72,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_CANVAS": {
    "id": "UI_COMMON_MEDIA_CANVAS",
    "path": "common.media.canvas",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 82,
    "feature": "common"
  },
  "UI_COMMON_MEDIA_SVG": {
    "id": "UI_COMMON_MEDIA_SVG",
    "path": "common.media.svg",
    "sourceFile": "/src/platform/ui/registry/categories/media.ts",
    "sourceComponent": "COMMON_MEDIA",
    "sourceLine": 92,
    "feature": "common"
  },
  "UI_COMMON_SPACING_BR": {
    "id": "UI_COMMON_SPACING_BR",
    "path": "common.spacing.br",
    "sourceFile": "/src/platform/ui/registry/categories/spacing.ts",
    "sourceComponent": "COMMON_SPACING",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_SPACING_HR": {
    "id": "UI_COMMON_SPACING_HR",
    "path": "common.spacing.hr",
    "sourceFile": "/src/platform/ui/registry/categories/spacing.ts",
    "sourceComponent": "COMMON_SPACING",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TABLE": {
    "id": "UI_COMMON_TABLES_TABLE",
    "path": "common.tables.table",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_TABLES_THEAD": {
    "id": "UI_COMMON_TABLES_THEAD",
    "path": "common.tables.thead",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TBODY": {
    "id": "UI_COMMON_TABLES_TBODY",
    "path": "common.tables.tbody",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TR": {
    "id": "UI_COMMON_TABLES_TR",
    "path": "common.tables.tr",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TH": {
    "id": "UI_COMMON_TABLES_TH",
    "path": "common.tables.th",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TABLES_TD": {
    "id": "UI_COMMON_TABLES_TD",
    "path": "common.tables.td",
    "sourceFile": "/src/platform/ui/registry/categories/tables.ts",
    "sourceComponent": "COMMON_TABLES",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_TEMPLATE_TEMPLATE": {
    "id": "UI_COMMON_TEMPLATE_TEMPLATE",
    "path": "common.template.template",
    "sourceFile": "/src/platform/ui/registry/categories/template.ts",
    "sourceComponent": "COMMON_TEMPLATE",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_TEMPLATE_SLOT": {
    "id": "UI_COMMON_TEMPLATE_SLOT",
    "path": "common.template.slot",
    "sourceFile": "/src/platform/ui/registry/categories/template.ts",
    "sourceComponent": "COMMON_TEMPLATE",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H1": {
    "id": "UI_COMMON_TYPOGRAPHY_H1",
    "path": "common.typography.h1",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 12,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H2": {
    "id": "UI_COMMON_TYPOGRAPHY_H2",
    "path": "common.typography.h2",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 22,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H3": {
    "id": "UI_COMMON_TYPOGRAPHY_H3",
    "path": "common.typography.h3",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 32,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H4": {
    "id": "UI_COMMON_TYPOGRAPHY_H4",
    "path": "common.typography.h4",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 42,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H5": {
    "id": "UI_COMMON_TYPOGRAPHY_H5",
    "path": "common.typography.h5",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 52,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_H6": {
    "id": "UI_COMMON_TYPOGRAPHY_H6",
    "path": "common.typography.h6",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 62,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_P": {
    "id": "UI_COMMON_TYPOGRAPHY_P",
    "path": "common.typography.p",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 72,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_STRONG": {
    "id": "UI_COMMON_TYPOGRAPHY_STRONG",
    "path": "common.typography.strong",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 82,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_EM": {
    "id": "UI_COMMON_TYPOGRAPHY_EM",
    "path": "common.typography.em",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 92,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_CODE": {
    "id": "UI_COMMON_TYPOGRAPHY_CODE",
    "path": "common.typography.code",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 102,
    "feature": "common"
  },
  "UI_COMMON_TYPOGRAPHY_PRE": {
    "id": "UI_COMMON_TYPOGRAPHY_PRE",
    "path": "common.typography.pre",
    "sourceFile": "/src/platform/ui/registry/categories/typography.ts",
    "sourceComponent": "COMMON_TYPOGRAPHY",
    "sourceLine": 112,
    "feature": "common"
  },
  "UI_AUTH_LOGIN_LOGO": {
    "id": "UI_AUTH_LOGIN_LOGO",
    "path": "auth.login.display.logo",
    "sourceFile": "/src/platform/ui/registry/features/auth.ts",
    "sourceComponent": "AUTH",
    "sourceLine": 6,
    "feature": "auth"
  }
};
