import type { MerchantProfileData } from './types';

export const mockMerchantProfile: MerchantProfileData = {
  merchant: {
    id: 'merch-001',
    name: 'Lumière Atelier',
    logo: 'https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=150',
    banner: 'https://images.pexels.com/photos/994234/pexels-photo-994234.jpeg?auto=compress&cs=tinysrgb&w=1600',
    verified: true,
    category: 'Fashion & Apparel',
    status: 'active',
    joinedDate: '2022-03-15T00:00:00Z',
    location: {
      city: 'Paris',
      country: 'France',
    },
    metrics: {
      productsCount: 847,
      ordersCount: 12847,
      customersCount: 4521,
      rating: 4.9,
      reviewCount: 3287,
      revenue: 2450000,
      completionRate: 98.5,
      responseRate: 99.2,
    },
    social: {
      followers: 125000,
      following: 892,
    },
  },

  overview: {
    productsCount: 847,
    ordersCount: 12847,
    customersCount: 4521,
    rating: 4.9,
    revenue: 2450000,
    completionRate: 98.5,
    responseRate: 99.2,
  },

  quickActions: [
    { id: 'action-add-product', label: 'Add Product', icon: 'Plus', href: '/merchant/products/new', variant: 'primary' },
    { id: 'action-manage-products', label: 'Manage Products', icon: 'Package', href: '/merchant/products', badge: 847 },
    { id: 'action-orders', label: 'Orders', icon: 'ShoppingBag', href: '/merchant/orders', badge: 23 },
    { id: 'action-messages', label: 'Messages', icon: 'MessageSquare', href: '/merchant/messages', badge: 8 },
    { id: 'action-analytics', label: 'Analytics', icon: 'BarChart3', href: '/merchant/analytics' },
    { id: 'action-promotions', label: 'Promotions', icon: 'Megaphone', href: '/merchant/promotions' },
    { id: 'action-inventory', label: 'Inventory', icon: 'Warehouse', href: '/merchant/inventory', badge: 12 },
  ],

  storeInformation: {
    about: 'Lumière Atelier is a premium fashion brand dedicated to creating timeless, elegant pieces that transcend seasonal trends. Founded in Paris, we combine traditional craftsmanship with contemporary design.',
    description: 'We specialize in sustainable luxury fashion, offering curated collections of clothing, accessories, and footwear for the modern sophisticate. Each piece is crafted with meticulous attention to detail using ethically sourced materials.',
    categories: ['Women\'s Fashion', 'Men\'s Fashion', 'Accessories', 'Footwear', 'Sustainable Wear', 'Luxury Items'],
    shippingCoverage: ['United States', 'Canada', 'European Union', 'United Kingdom', 'Australia', 'Japan'],
    returnPolicy: '30-day hassle-free returns on all unworn items. Full refund guaranteed if item doesn\'t meet expectations.',
    specialties: ['Sustainable Materials', 'Handcrafted Details', 'Limited Editions', 'Custom Tailoring'],
  },

  performance: {
    revenueToday: 8420,
    revenueThisMonth: 245000,
    ordersToday: 24,
    ordersThisMonth: 687,
    conversionRate: 4.8,
    averageOrderValue: 185,
    bestSellingCategory: 'Women\'s Dresses',
    inventoryHealth: 'healthy',
  },

  collections: [
    {
      id: 'col-001',
      name: 'Spring Elegance',
      coverImage: 'https://images.pexels.com/photos/1462630/pexels-photo-1462630.jpeg?auto=compress&cs=tinysrgb&w=600',
      itemCount: 45,
      type: 'seasonal',
    },
    {
      id: 'col-002',
      name: 'Urban Minimalist',
      coverImage: 'https://images.pexels.com/photos/1537641/pexels-photo-1537641.jpeg?auto=compress&cs=tinysrgb&w=600',
      itemCount: 32,
      type: 'fashion',
    },
    {
      id: 'col-003',
      name: 'Evening Luxe',
      coverImage: 'https://images.pexels.com/photos/1594811/pexels-photo-1594811.jpeg?auto=compress&cs=tinysrgb&w=600',
      itemCount: 28,
      type: 'fashion',
    },
    {
      id: 'col-004',
      name: 'Sustainable Essentials',
      coverImage: 'https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg?auto=compress&cs=tinysrgb&w=600',
      itemCount: 56,
      type: 'trending',
    },
  ],

  bestSellingProducts: [
    {
      id: 'prod-001',
      name: 'Silk Midi Dress - Midnight Blue',
      image: 'https://images.pexels.com/photos/1595237/pexels-photo-1595237.jpeg?auto=compress&cs=tinysrgb&w=400',
      price: 325,
      salesCount: 1847,
      rating: 4.9,
      reviewCount: 423,
      stockStatus: 'in_stock',
      stockCount: 127,
      category: 'Women\'s Dresses',
    },
    {
      id: 'prod-002',
      name: 'Cashmere Blend Overcoat',
      image: 'https://images.pexels.com/photos/769267/pexels-photo-769267.jpeg?auto=compress&cs=tinysrgb&w=400',
      price: 580,
      originalPrice: 720,
      salesCount: 982,
      rating: 4.8,
      reviewCount: 287,
      stockStatus: 'low_stock',
      stockCount: 18,
      category: 'Women\'s Outerwear',
    },
    {
      id: 'prod-003',
      name: 'Tailored Wool Blazer',
      image: 'https://images.pexels.com/photos/1018944/pexels-photo-1018944.jpeg?auto=compress&cs=tinysrgb&w=400',
      price: 420,
      salesCount: 756,
      rating: 4.7,
      reviewCount: 198,
      stockStatus: 'in_stock',
      stockCount: 89,
      category: 'Men\'s Suits',
    },
    {
      id: 'prod-004',
      name: 'Le Crossbody Bag - Cognac',
      image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=400',
      price: 285,
      salesCount: 1432,
      rating: 4.9,
      reviewCount: 312,
      stockStatus: 'in_stock',
      stockCount: 64,
      category: 'Accessories',
    },
    {
      id: 'prod-005',
      name: 'Linen Summer Trousers',
      image: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=400',
      price: 165,
      salesCount: 678,
      rating: 4.6,
      reviewCount: 145,
      stockStatus: 'out_of_stock',
      stockCount: 0,
      category: 'Men\'s Pants',
    },
    {
      id: 'prod-006',
      name: 'Merino Wool Sweater - Ivory',
      image: 'https://images.pexels.com/photos/1040925/pexels-photo-1040925.jpeg?auto=compress&cs=tinysrgb&w=400',
      price: 245,
      salesCount: 534,
      rating: 4.8,
      reviewCount: 167,
      stockStatus: 'in_stock',
      stockCount: 52,
      category: 'Women\'s Tops',
    },
  ],

  recentOrders: [
    {
      id: 'ORD-2024-8547',
      customer: {
        name: 'Emma Thompson',
        avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      value: 485,
      status: 'processing',
      createdAt: '2024-01-15T14:30:00Z',
      items: 3,
    },
    {
      id: 'ORD-2024-8546',
      customer: {
        name: 'James Chen',
        avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      value: 720,
      status: 'shipped',
      createdAt: '2024-01-15T12:15:00Z',
      items: 2,
    },
    {
      id: 'ORD-2024-8545',
      customer: {
        name: 'Sophie Martin',
        avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      value: 298,
      status: 'delivered',
      createdAt: '2024-01-15T09:45:00Z',
      items: 1,
    },
    {
      id: 'ORD-2024-8544',
      customer: {
        name: 'Michael Brown',
        avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      value: 1150,
      status: 'pending',
      createdAt: '2024-01-15T08:20:00Z',
      items: 5,
    },
    {
      id: 'ORD-2024-8543',
      customer: {
        name: 'Isabella Garcia',
        avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      value: 165,
      status: 'delivered',
      createdAt: '2024-01-14T16:30:00Z',
      items: 1,
    },
  ],

  reviews: [
    {
      id: 'rev-001',
      customer: {
        name: 'Alexandra Williams',
        avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      rating: 5,
      comment: 'Absolutely stunning piece! The quality exceeded my expectations. The silk feels luxurious and the fit is perfect. Will definitely be ordering again.',
      createdAt: '2024-01-14T18:30:00Z',
      productName: 'Silk Midi Dress - Midnight Blue',
      helpful: 47,
    },
    {
      id: 'rev-002',
      customer: {
        name: 'David Park',
        avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      rating: 5,
      comment: 'The cashmere overcoat is incredible. Perfect for the Paris weather. Fast shipping and excellent packaging. True to size.',
      createdAt: '2024-01-13T15:20:00Z',
      productName: 'Cashmere Blend Overcoat',
      helpful: 32,
    },
    {
      id: 'rev-003',
      customer: {
        name: 'Marie Laurent',
        avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=80',
      },
      rating: 4,
      comment: 'Beautiful bag with great craftsmanship. The leather is soft but durable. Slightly smaller than expected but still very functional.',
      createdAt: '2024-01-12T10:15:00Z',
      productName: 'Le Crossbody Bag - Cognac',
      helpful: 18,
    },
  ],

  ratingDistribution: {
    five: 2847,
    four: 312,
    three: 89,
    two: 28,
    one: 11,
  },

  trustCredentials: [
    {
      id: 'trust-001',
      type: 'verified',
      title: 'Verified Merchant',
      description: 'Identity and business credentials verified',
      icon: 'ShieldCheck',
    },
    {
      id: 'trust-002',
      type: 'secure_payments',
      title: 'Secure Payments',
      description: 'SSL encrypted transactions',
      icon: 'Lock',
    },
    {
      id: 'trust-003',
      type: 'fast_shipping',
      title: 'Fast Shipping',
      description: 'Average 2-4 day delivery',
      icon: 'Truck',
    },
    {
      id: 'trust-004',
      type: 'return_policy',
      title: 'Easy Returns',
      description: '30-day return guarantee',
      icon: 'RefreshCw',
    },
  ],

  achievements: [
    {
      id: 'ach-001',
      name: 'Top Seller 2023',
      description: 'Ranked in top 1% of merchants',
      icon: 'Trophy',
      earnedAt: '2023-12-31T00:00:00Z',
      rarity: 'legendary',
    },
    {
      id: 'ach-002',
      name: 'Customer Favorite',
      description: '5000+ 5-star reviews',
      icon: 'Star',
      earnedAt: '2023-08-15T00:00:00Z',
      rarity: 'epic',
    },
    {
      id: 'ach-003',
      name: 'Fast Responder',
      description: 'Average response time under 1 hour',
      icon: 'Zap',
      earnedAt: '2023-06-01T00:00:00Z',
      rarity: 'rare',
    },
    {
      id: 'ach-004',
      name: 'Eco Conscious',
      description: 'Sustainable packaging certified',
      icon: 'Leaf',
      earnedAt: '2023-04-20T00:00:00Z',
      rarity: 'common',
    },
  ],

  badges: [
    {
      id: 'badge-001',
      name: 'Premium Seller',
      description: 'Exclusive premium tier merchant',
      icon: 'Crown',
      earned: true,
    },
    {
      id: 'badge-002',
      name: 'Style Expert',
      description: 'Featured in style collections',
      icon: 'Palette',
      earned: true,
    },
    {
      id: 'badge-003',
      name: 'Global Seller',
      description: 'Ships to 10+ countries',
      icon: 'Globe',
      earned: true,
    },
    {
      id: 'badge-004',
      name: 'Flash Seller',
      description: '500+ orders in single day',
      icon: 'Flame',
      earned: true,
    },
  ],
};

export default mockMerchantProfile;
